### ISSUE TITLE
setting CSS font size too large causes UI elements to disappear

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#10]
Setting the root size (on which rem is based to e.g. 200% using `html {font-size:200%}` causes the UI elements to disappear on the touchscreen (and probably on all displays). I suspect this is something to do with `overflow: hidden` on the `body` element (see https://github.com/OneZoom/OZtree/issues/9)

**Comment by jrosindell** [comment]
@lentinj does this still happen and is there any easy solution?

**Comment by hyanwong** [comment]
This seems OK now, although obviously the UIkit icons don't scale (so should possibly be defined using sizes of `rem` not px).
