### ISSUE TITLE
Set node.theme based on tree

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#102]
...so the OTOP theme can pick it up and style based on theme category

> OTT 2 (bacteria) - def needs a special theme!
> OTT 759129 (all animals) set water theme - easiest to do like this
> then cut out non water animals separately.  Sea / freshwater
> separation probably too difficult (near impossible right now!)
> OTT 834746 (amniotes = mammals + reptiles + birds) set land theme
> OTT 834747 (mammals) set land mammal theme 
> OTT 1000400 (arthropods) set land theme (though still contains many
> sea creatures)
> OTT 850059 (crocodiles and relatives) set special theme?
> OTT 850081 (birds) set land bird theme
> OTT 836042 (seals walrus erc.) set sea theme which overrides mammals
> theme of ancestor node
> OTT 835571(whales, dolphins, hippos) set water theme (yes they are a
> group!)
> OTT 836106 (otters) set water theme
> OTT 10732 (polar bear - leaf test case there will be more of these
> e.g. platypus….) set water theme
> OTT 835091 (dougong and manatees) set water theme
> OTT 1120735 (pancrustacea) set water theme for this group which sits
> within arthropods and contains shrimp, lobster, crabs etc.
> OTT 1191377 (hexapods incl. insects)- set land theme - sits within
> pancrustacea.

**Comment by jrosindell** [comment]
Sounds good!

**Comment by lentinj** [comment]
@jrosindell Whilst you said OTT in the above, the values are actually metacodes. Which do you want in the lookup?

It doesn't make a huge difference, although some nodes don't have OTT (e.g. seals / otters).

**Comment by hyanwong** [comment]
Metacodes (IDs) are subject to change with new tree versions. OTTs are supposed to be stable. So OTTs here, I guess.

**Comment by lentinj** [comment]
Okay, the above sorts this with OTT. However, the tree is very prone to colours jumping about as node details (including OTT) are loaded. It could be worth translating the mapping to metacodes by asking the server for each of the nodes that change colours early on.

However, this is mostly a problem when in flight mode, as detail isn't loaded until the flight stops (see #91). That probably has to be fixed first.

**Comment by jrosindell** [comment]
Ah sorry I got this wrong - was copying the ID from the URL thinking it was OTT but now I remember that it's not.  I'll post some translations later.

**Comment by lentinj** [comment]
The detail is now loaded, so this is a lot better. Although e.g. flying to insects you will see distant detail start off blue and switch once the flight has stopped. Possibly ``get_details_of_nodes_in_view_during_fly()``'s hard-coded breadth parameter should be changed.

It'd also be nice if the colour changes weren't quite so violent, maybe the "no detail" colour should be transparent?

**Comment by jrosindell** [comment]
I completely agree with the violent colour changes - this always bothered me before as well.  I think completely transparent would be weird so presume you mean 50% transparency or something that makes it look a bit ghostly until the detail is there to load properly.
