### ISSUE TITLE
OTOP: Background particles should react to flights

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#104]
When in flight modes, the particles should zoom in/out in sync with tree.

**Comment by jrosindell** [comment]
Naziha requested this again on the latest call with some kind of elastic zoom in and out. Probably best to do this by rescaling the underlying image rather than modelling the individual particles.

**Comment by lentinj** [comment]
> rescaling the underlying image

Yes, my main aim here is to not clutter OneZoom with a full-blown starfield simulator.

I think the way to do this is to:

* Remove the trails from the original image, so it just becomes a bunch of dots.
* Rotate a series of these with different opacities, so we can control the direction of the trails
* Normal mode they end up just behind each other on the same animation path
* Panning nudges the trails that direction
* Zooming in / out they shrink / expand from the centre of the screen.

**Comment by lentinj** [comment]
Lots of stuff here. Infrastructure-wise the most interesting bits are poking around in the hook mechanism to make it suitable for plumbing the particles to. Whilst it is abusing it somewhat, seemed like the most useful mechanism to use.

**Comment by lentinj** [comment]
1. I like the pan, but maybe it should move less. Is it always the same distance each time, but in the opposite direction of your finger ?

2. Strangely I don't manage to zoom in with my two fingers. Do you know why?

3. When we use the flight mode at the end it stop and looks strange. Maybe we should zoom in the image and then zoom out. And the three images corresponding to the trail should not disappear abruptly.

**Comment by jrosindell** [comment]
I liked the particles implementation a lot.

> 2\. Strangely I don't manage to zoom in with my two fingers. Do you know why?

Did we get to the bottom of the reason for this?  It seems quite important, but also probably easy to solve.
