### ISSUE TITLE
OTOP rings should adjust size

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#107]
> Concerning the circles, there is a maximum of 7 colors (I'll send them to you ) and each thickness (for example: 1 pixel ) corresponds to a level in of the challenges. The maximum number of pixels is 51 (including 1 space of 1 pixel between each of the seven colors)

We need to know how to get this from the JSON, and render it.

**Comment by lentinj** [comment]
![image](https://user-images.githubusercontent.com/586911/41811342-e25db42c-7705-11e8-8419-03b04a1714ee.png)

**Comment by jrosindell** [comment]
Following on from this I want to post a few comments from Naziha which were e-mailed in about this...

> For the rendering of the Homo sapiens leaf, can we get closer to the images I sent you? 
Actually what I would do, is put the last blue light I gave you as a first layer, then the spheres and the circles and in the end a blue transparent light on the to of everything (maybe more as a color layer).

**Comment by jrosindell** [comment]
![homo sapiens leaf2](https://user-images.githubusercontent.com/3009279/41833801-646dfc4a-7884-11e8-82d8-149b7b114390.jpg)

**Comment by lentinj** [comment]
Yep. I've struggled with replicating this given the layers I got. I think Naziah is using a blend mode to get the colouration of the globe, but not entirely sure.

Worst-case we use an image for the entire thing, which I'd like to avoid but makes for a very simple fix :)

**Comment by jrosindell** [comment]
I agree - however what is really wanted is for the rings around each person in the image to be programmable.  This would be hard to achieve with rebuilt images as there are many combinations.  Hopefully some layering of images and arcs will be OK without a blend provided that the ordering of the layers is OK.  Maybe the blue haze could be a semi-transparent image in its own right that sits on top of the lot (maybe that's actually what you meant)

**Comment by lentinj** [comment]
> Maybe the blue haze could be a semi-transparent image in its own right that sits on top of the lot (maybe that's actually what you meant)

Correct. Currently I'm trying to generate the background with a collection of radial gradients and an image that just has the wireframe globes. I was hoping this would be a trivial insertion, but the image I got looks more like an alpha channel.

**Comment by lentinj** [comment]
The globe was sorted a while ago, I need to know how to adjust the width of the rings, waiting on David.
