### ISSUE TITLE
Signpost text and image bug at the end of fans for large polytomies.

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#110]
<img width="956" alt="capture d ecran 2018-06-22 a 15 24 56" src="https://user-images.githubusercontent.com/3009279/41833860-a576b664-7884-11e8-86c4-2891b9cfed39.png">

**Comment by jrosindell** [comment]
Naziha pointed this out but I've seen it too in multiple places.  I actually think it's related to #108 because this is trying to render additional data on the tips of the visible tree (in this case they are nodes and hence we're talking about signposts etc.) when really it should know to skip rendering here.  I think this is related to two things... 1.) signposts do not scale at all with size of the part of the tree they represent - this was not the case with classic OneZoom or the original polytomy view. 2.) if thresholds are working correctly (see #108 again) then it would know not to draw signposts at all.  I suspect the threshold test is related to the rendered size of the SP and thus if the SP does not get smaller with size of clade then the threshold will never be hit because they're constant size and thus always pass the threshold test.  In the context of #108 it might be that the problems are on nodes that have large numbers of children **that are also nodes** and hence large numbers of signposts being drawn around the tips (thousands even) when they should not be.

**Comment by jrosindell** [comment]
I think this is possibly closable now, but as it's definitely related to OTOP I'm levelling it 3.3

**Comment by lentinj** [comment]
I remember fixing this in the last chunk of work. It's not a threshold problem as you might initially think, IIRC the signpost size was being calculated based on the radius of the parent node, not the node in question. In cases with little branching the difference wasn't great, so it looked like everything was working. In the case above the difference between the radius of the parent and child is obviously very different. Hilarity ensued.
