### ISSUE TITLE
pop service returns fungus that OT does not recognize

### ISSUE THREAD

**Issue by arlin** [OneZoom/OZtree#112]
Looking for some popular fungi: 

 http://beta.onezoom.org/popularity/list?key=0&otts=352914&expand_taxa=True&max=10&names=True&sort=rank

I get OT 1187135, "Pseudaphelidium drebesii".  But OT does not seem to know about this, whether I search by name or ID.  The name search, even just the genus, says "not found", and the id search actually gives an exception.  

https://tree.opentreeoflife.org/taxonomy/browse?name=1187135

**Comment by arlin** [comment]
Related to this, I get OT 1199202, "vouchered mycorrhizae Ascomycota" (which seems an unlikely candidate for popularity) and the result of trying to find this on OpenTree are the same.

**Comment by arlin** [comment]
And the same thing goes for (in a search of plants) id 1187451, "Equisetum font-queri".

**Comment by hyanwong** [comment]
Yes, I noticed this recently. I think the problem is because of the logarithmic weighting given to numbers of nodes in the tree. This means that many obscure or fossil species, which tend to float to higher nodes, benefit from having relatively few nodes between themselves and the root.

I need to discuss with you (and maybe James) how to improve the scheme so this doesn't happen. The simplest would be simply to add up all popularities at all nodes - the reason I didn't do this before was because I was worried that deep nodes would gain popularity simply by virtue of being deep.

I agree this needs to be sorted though. Presumably we can test the API functionality even if the actual popularity values are a bit weird in some cases. We can then test some corrections to the weighting algorithm.

**Comment by jar398** [comment]
I’m confident that id 1187135 was never assigned in any previous version of OTT. It lies in the OTT1.0 id range and I just looked at OTT1.0 and it’s not in there.

**Comment by hyanwong** [comment]
OK, that's a bug then. Will investigate.

**Comment by hyanwong** [comment]
@arlin - those numbers you quoted are the popularity rank. I must be returning the wrong headers. E.g. `Equisetum font-queri` should be OTT 3865876, popularity 56858.13184327758, popularity rank 1187451

**Comment by hyanwong** [comment]
@arlin - I _think_ my API is returning the correct terms (apart from them being rubbish measures of popularity, which we will fix). E.g. the example you gave returns:

```
{"max_taxa_out":100,"n_taxa":249504,"header":["ott","popularity","popularity_rank","name"],"tot_spp":2123183,"max_taxa_in":5,"data":[[null,56879.21109278531,1187135,"Pseudaphelidium drebesii"],[3791314,56749.53543505613,1189796,"Morchella meiliensis"],[5303017,56677.79310184638,1191164,"Morchella rete"],[349523,56285.22721776738,1199202,"vouchered mycorrhizae Ascomycota"],[339440,56229.43392854333,1200259,"Morchella elata"],[4083876,56136.5986584366,1201996,"Morilla olivea"],[5303026,56136.5986584366,1201996,"Morchella americana"],[3791273,55676.37286813932,1211050,"Morchella pragensis"],[3791267,55622.34599025908,1212206,"Morchella alba"],[276362,55461.64877315146,1215356,"Antonospora psocopterae"]]}
```

where _Pseudaphelidium drebesii_ has an OTT of `null` (which explains why you can't find it). _vouchered mycorrhizae Ascomycota_ (yes, I know it's crap) has an OTT of 349523.

**Comment by hyanwong** [comment]
NB: _Pseudaphelidium drebesii_ is one of the (very very few) species on my tree which have been grafted on by hand and are not present in OTT (in this case, from http://journal.frontiersin.org/Journal/10.3389/fmicb.2014.00112/, which I guess may eventually get into the OpenTree). It's obscurely documented in https://github.com/OneZoom/OZtree/blob/master/OZprivate/data/OZTreeBuild/AllLife/BespokeTree/include_noAutoOTT/Opisthosporidia_from_draftversion3.PHY

**Comment by hyanwong** [comment]
FYI there are 220 / 2.2 million, or 0.01% of species in the OneZoom tree without OTTs. Here they are:

Pseudaphelidium drebesii
Aphelidium chlorococcarum
Amoeboaphelidium chlorellavorum
Amoeboaphelidium radiatum
Clathrina sueziana
Clathrina darwini
Leucosolenia somesi
Porifera incertae sedis
Corticium diamentese
Plakortis edwarsi
Hyalonema ovatum1
Hyalonema ovatum2
Hyalonema {Phialonemiella} brevancora
Hyalonema {Thamnonemiella} thamnophorum
Eurete schmidti
Anoxycalyx {Scolymastra} joubini
Caulophacus {Oxydiscus} weddelli
Crateromorpha {Caledochone} caledoniensis
Crateromorpha {Craterochone} bermudensis
Aaptos confertus
Aaptos globosum
Aaptos tentum
Polymastia aurantium
Xestospongia mammillata
Aka trachys
Callyspongia ridleyi2
Callyspongia elegans
Callyspongia ridleyi1
Haliclona foraminosa2
Haliclona glacialis2
Haliclona irregularis2
Haliclona laxa2
Haliclona arctica2
Haliclona varia2
Haliclona fragilis2
Haliclona pedunculata2
Haliclona digitata2
Haliclona perforata1
Haliclona strongylata1
Haliclona tenella2
Haliclona fistulosa2
Haliclona perforata2
Haliclona pedunculata
Haliclona strongylata2
Haliclona arctica1
Haliclona digitata1
Haliclona schmidti
Haliclona varia1
Haliclona tenella1
Haliclona fragilis1
Haliclona irregularis1
Haliclona foraminosa1
Haliclona glacialis1
Haliclona laxa1
Haliclona pedunculata1
Haliclona fistulosa1
Haliclona cylindrica
Strongylacidon intermedia
Strongylacidon mollissima
Strongylacidon chelospinata
Cladorhiza fristedti
Biemna parthenopea
Mycale levii1
Mycale toxifera1
Mycale toxifera2
Mycale levii2
Raspailia {Hymeraphiopsis} irregularis
Clathria compressa
Clathria flabellata1
Clathria flabellata2
Geodia normani
Fangophilina kirkpatricki
Demospongiae incertae sedis
Spongia {Australospongia} gracilis
Myotis occultus
Galeopterus borneanus
Avahi ramanantsoavani
Lepilemur wrighti
Lepilemur tymerlachsoni
Microcebus sp nova300Radespiel800
Microcebus spDWW201000aManantantel
Microcebus spDWW201000aMarolambo
Microcebus sp nova100Louis600
Microcebus sp nova300Louis600
Alouatta nigerrima
Presbytis fredericae
Spermophilus saturatus
Oxymycterus roberti
Acomys airensis
Elseya latisternum
Peltocephalus dumeriliana
Testudo weissingeri
Homopus bergeri
Dipsochelys dussumieri
Geochelone nigra ephippium
Geochelone nigra guntheri
Geochelone nigra microphyes
Geochelone nigra vandenburghi
Cyclemys orbiculata
Cyclemys ovata
Ocadia glyphistoma
Ortalis superciliaris
Lophura hoogerwerfi
Caprimulgus heterurus
Apus toulsoni
Collocalia rogersi
Collocalia unicolor
Collocalia orientalis
Collocalia papuensis
Collocalia infuscata
Collocalia amelis
Collocalia palawanensis
Collocalia inquieta
Collocalia germani
Collocalia leucophaea
Collocalia pelewensis
Collocalia nuditarsus
Collocalia ocista
Collocalia spodiopygia
Collocalia mearnsi
Ducula spilorrhoa
Ducula luctuosa
Ducula subflavescens
Coccycua cinerea
Coccycua pumila
Chrysococcyx russatus
Pachyptila crassirostris
Phalacrocorax colensoi
Thaumatibis gigantea
Esacus giganteus
Vanellus malarbaricus
Catharacta lonnbergi
Bucorvus cafer
Todiramphus saurophaga
Picumnus dorbignyanus
Picumnus cinnamomeus
Picumnus nigropunctatus
Picumnus olivaceus
Picumnus limae
Picumnus granadensis
Picumnus pumilus
Picumnus squamulatus
Picumnus minutissimus
Picumnus castelnau
Picumnus subtilis
Picumnus fulvescens
Picumnus varzeae
Picumnus steindachneri
Picumnus sclateri
Picumnus albosquamatus
Picumnus fuscus
Mesopicos griseocephalus
Mesopicos goertae
Thripias namaquus
Thripias xantholophus
Thripias pyrrhogaster
Mesopicos elliotii
Pyrilia pulchra
Pyrilia haematotis
Pyrilia aurantiocephala
Pyrilia pyrilia
Pitta dohertyi
Onychorhynchus mexicanus
Laniisoma buckleyi
Tolmomyias viridiceps
Phelpsia inornatus
Phyllomyias zeledoni
Phaeomyias tumbezana
Furnarius longirostris
Phacellodomus inornatus
Hylacola cauta
Colluricincla tenebrosa
Monarcha godeffroyi
Monarcha castus
Parus hypermelaenus
Parus davidi
Eurochelidon sirintarae
Cettia canturians
Bernieria tenebrosa
Bernieria apperti
Bernieria cinereiceps
Cisticola nanus
Camaroptera simplex
Camaroptera fasciolata
Camaroptera undosa
Amaurocichla bocagei
Alcippe danisi
Alcippe formosana
Alcippe manipurensis
Paradoxornis margaritae
Stachyris pygmaea
Zosterops chloronothus
Macronous bornensis
Turdinus marmorata
Turdinus macrodactylus
Turdinus atrigularis
Turdinus rufipectus
Trichastoma buettikoferi
Trichastoma tickelli
Garrulax melanostigma
Garrulax chrysopterus
Garrulax ngoclinhensis
Garrulax peninsulae
Cinclus schulzi
Tarsiger hyperythrus
Oenanthe bifasciata
Myrmecocichla cinnamomeiventris
Myrmecocichla arnoti
Anthreptes aurantium
Nectarinia chalcomelas
Nectarinia neergardi
Histurgops ruficaudus
Petronia brachydactyla
Macronyx fuellebornii
Eremopsaltria mongolicus
Rhodopechys obsoletus
Vermivora pinus
Dendroica aestiva
Cacicus microrhynchus
Poospiza nigrorufa

**Comment by arlin** [comment]
that's embarrassing for me.  I searched with the names first, and then upon failure of a name, I went back into the json to get the numbers that look like OT ids.  So I picked the wrong numbers for these three.

**Comment by hyanwong** [comment]
Yep - probably simplest to look up the column number in the header field. Actually, perhaps I should return the header as a dict of name=>col_index, so you can just do

`data[header['ott']]`

Would that work better?

**Comment by arlin** [comment]
Go head, just let us know of any changes.  Our team at NMSU already put the popularity service into the dev version of our portal so that we can play with it:  

  http://phylo.cs.nmsu.edu:3001/taxonomies/new

It says "population" here instead of "popularity".   Sample result below is a DateLife-scaled tree of 20 popular cats with thumbnails from EOL. 

![53](https://user-images.githubusercontent.com/1659198/41944684-13614692-7977-11e8-9c72-4dfcbfab71c8.png)

**Comment by hyanwong** [comment]
@arlin - I have changed the header property so that it maps the column headers to index numbers, and  changed the documentation accordingly. So now you can do e.g. `data[2][header.popularity_rank]`. Does that make sense?

**Comment by hyanwong** [comment]
By the way, the top fungi are now a bit more reasonable, although still not quite right.
