### ISSUE TITLE
OTOP should fetch image directly from app for human leaf

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#116]
You can give a guid with 0 only (32 times 0)
`http://40.115.43.52/userprofiles/00000000000000000000000000000000/random`
And we will return random profiles anyway.In this case, if a user hasn’t been yet created, we propose you to give you the profile picture we have locally by using a `WebViewBridge` object for communication between the web view and the app.
We will sent you a `userPhoto` message with base64 encoded picture in `data` property :

```
if (WebViewBridge) {
  WebViewBridge.onMessage = function (rawMessage) {
    var message = JSON.parse(rawMessage)
    if (message.type === "userPhoto") {
      var dataUri = 'data:image/png;base64,' + message.data
      var img = document.createElement('img')
      img.src = dataUri
      document.body.appendChild(img)
    }
  }
}
```

**Comment by jrosindell** [comment]
I'm adding a note to this issue just to highlight more broadly that the human leaf needs to be completed to look as Naziha requested.

**Comment by lentinj** [comment]
I didn't realise there was a task for this. But the following commits finish the job:

* https://github.com/OneZoom/OZtree/commit/3676684ddbaf6b382e8cba1c0be2ea8c285f5eb9
* https://github.com/OneZoom/OZtree/commit/2a5db3bb9dfa1c4e04139a55f29a97cfc4d12f63
* https://github.com/OneZoom/OZtree/commit/6a69f8837373faf29032eaef6eb39a17f137cf92
