### ISSUE TITLE
Gift aid address fields

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#117]
I think we need to add these to the sponsor leaf page so that people don't have to use the PayPal box ticking route to provide us with their address. This will require adding fields to the database for user filled out street address including postcode and adding boxes and validations to the sponsorship form

**Comment by hyanwong** [comment]
For gift aid we only need: "Title", "First name", "Second Name", "House name or number", "Postcode". 

* We need to separate out the current donor name box into "first name" & "second name"
* We need to add the "house name or number" and "UK postcode" to the grey "gift aid" box. There should also be a "I don't have a UK postcode but I do pay UK tax" - which allows submission even if the postcode field is not filled out.

We will switch to using the PP_postcode and PP_address to save this, and *never* save those from paypal (for GDPR reasons).

**Comment by hyanwong** [comment]
@jrosindell - we haven't implemented this. Is it vital for the new homepage changes?

**Comment by jrosindell** [comment]
Postcode, house number, country should be in the gift aid grey box
should use auto complete and give a warning message if country is not the UK. page should require it to be correct before submission.

**Comment by jrosindell** [comment]
There is one decision to be made about this - should the postcode, house name / number, and country be entered in new database fields (making downstream git aid scripts require an update) or should they be entered in existing PP database fields (making these fields incorrectly named as they say PP in front, and also meaning we have to change the PP post script so that these fields are only over written if gift aid does not apply.  A final option is to simply switch off the PP posting of address in the first place.  Overall, I'd suggest that new database fields is probably the best way to go but @hyanwong I'd like to hear your opinion too

**Comment by lentinj** [comment]
New DB fields seem like the way to go, as well as being less confusing, it allows for a smooth migration path.

Questions @jrosindell :

* When we renew, we assume gift-aid details don't change (i.e. we're keeping the paypal details). Does this assumption hold in light of the above?
* Does the renewal process try and copy details from the PP fields to the new fields, or just both sets of fields as before?

> should use auto complete

As in country? Seems like an excessive complication of the form and a list to maintain. By checking the gift-aid box you've already told us that you pay UK tax and would like to contribute Gift Aid. If you don't then we don't need to ask for any address and the fields are hidden.

**Comment by jrosindell** [comment]
`When we renew, we assume gift-aid details don't change (i.e. we're keeping the paypal details). Does this assumption hold in light of the above?`

The easy solution is to say that this assumption does hold and to put a note on the page saying that we're assuming no change to gift aid status - and to e-mail if they want a change - which we will then do by hand.

This might be clunky because e.g. what if a high value donor with 30 leaves moves home - we'd need a script to change them all anyway so there is an argument to say that we give them to chance to re enter their address and make a new gift aid declaration on renewal.  BUT we assume no change if they leave it blank.

One question arising.... is it secure enough to remind them of the address we have on file and the gift aid status on the page or might that be too easily hacked for others to see the page and extract personal details.

**Comment by lentinj** [comment]
> This might be clunky because e.g. what if a high value donor with 30 leaves moves home

This would be solved if on renewal time we take the gift aid details for the most recent sponsorship, not the same as before. That way they only have to change their address once, even if they responsor in several batches.

>  is it secure enough to remind them of the address we have on file

Should be, they've proven who they are via. an e-mail loop at this point. We could offer them the same form as sponsor_leaf, pre-populated with their last gift aid details.

**Comment by lentinj** [comment]
@hyanwong https://github.com/OneZoom/OZtree/commit/638f79442bf1bdb9e71477ffe1d8a5c85b6f557d adds the DB fields.

I've not added an explicit "I don't have a UK postcode but I do pay UK tax" field, my plan is to validate the form such that ether the postcode box is empty or the box is checked. Once it makes it to the database it's equivalent to ``user_giftaid`` being true and ``user_addr_postcode`` being NULL.

**Comment by lentinj** [comment]
Also note we recycle ``user_donor_name`` as second name. This makes the migration a bit easier I think.

**Comment by jrosindell** [comment]
@hyanwong and I have been chatting about all this.  We agree that there is no need to go back and update previous entries with a new address - there is only a need to declare a new address with a new donation.

In the sponsor leaf page address fields, if a new address is entered then we don't care it's just recorded as normal

In the renewals page, there are two cases - 1) that username has agreed to gift aid at least once in the past 2) that username has never agreed to gift aid.

In case 1) we tell them the last three characters of their most recent postcode used for gift aid (that would be the new fields just created or if they are null the PP fields) - we then give them the chance to enter a new postcode and house name/number if they wish.

In case 2) we tell them that they have not claimed gift aid in the past and give them the chance to declare now - in which case use the same logic as the sponsor leaf page

In either case the old reservation table rows are copied unchanged to the expired_reservations table and the new rows created in the reservations table reflect the new information if it has been changed (otherwise retain the original information)

**Comment by jrosindell** [comment]
> we tell them the last three characters of their most recent postcode used for gift aid

This is for extra security even though not necessary

**Comment by jrosindell** [comment]
> Also note we recycle `user_donor_name` as second name. This makes the migration a bit easier I think.

We're not sure what you mean by this.

**Comment by lentinj** [comment]
> Also note we recycle user_donor_name as second name.

The alternative would be a separate ``user_donor_secondname`` field, and we treat the old ``user_donor_name`` as a derived value for backward compatibility.

**Comment by jrosindell** [comment]
Regarding the non UK address question.... we've found this...

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/797959/gift_aid_schedule_version_3.ods

you don't need to click unless you wish but the bottom line is that we'll need the full address (in 40 characters max).  Therefore we'd suggest a radio button for 'UK tax payer with UK address' / 'UK tax payer with non-UK address' (obviously the UK address is the default).  

If they leave it on UK address then the fields are house name / number (40 chars or less) and postcode.  

If they switch to non-UK address then relabel the text above the same fields to read 'full address' (still 40 characters or less) and pre fill the postcode with an X and don't allow that to be edited.

In either case, on submit they are filled into the same two database fields.

**Comment by jrosindell** [comment]
> > Also note we recycle user_donor_name as second name.
> 
> The alternative would be a separate `user_donor_secondname` field, and we treat the old `user_donor_name` as a derived value for backward compatibility.

We're using the PayPal first and second name fields for Gift Aid.  These fields will always be returned by PayPal even though the address can no longer be relied upon.

**Comment by jrosindell** [comment]
The only thing we will need to add in the section where gift aid address is entered, is a short statement "Your first and second name used for the purposes of gift aid will be those returned by PayPal."

**Comment by lentinj** [comment]
Right, the above should cover the changes required for new sponsorships. Next up renewals.

**Comment by lentinj** [comment]
There's now an identical gift aid declaration on the renewal form.

Displaying the whole declaration in all cases is a bit ugly, but the easiest thing at this stage. Nicer would be to combine the work of the button on sponsor_leaf and the checkboxes, "I am UK resident and agree to gift aid", "I am not UK resident but pay UK tax and agree to gift aid", "I don't or cannot agree to gift aid".

All renewed items will get the updated address details. Telling people that you can't update your details on this form (message at the bottom) whilst requesting details for updating seems a bit perverse now. Maybe we want to give up and include the rest of the fields too whilst we're here?

If any of the renewal items include a partner, then all possible partners are displayed on the form, even if you're not necessarily renewing the OTTs that are for that partner. The alternative would be rigging up the partner names with JS and doesn't seem worth it.

@hyanwong This also assumes a migration step for the paypal address fields to new address fields.

**Comment by hyanwong** [comment]
> Telling people that you can't update your details on this form (message at the bottom) whilst requesting details for updating seems a bit perverse now. Maybe we want to give up and include the rest of the fields too whilst we're here?

Sorry, I'm losing the context here. Could you bung in a screenshot?

**Comment by hyanwong** [comment]
> @hyanwong This also assumes a migration step for the paypal address fields to new address fields.

I think we can do that, in cases where gifted is true. Does that seem OK @jrosindell ?

**Comment by lentinj** [comment]
> Sorry, I'm losing the context here. Could you bung in a screenshot?

![screen](https://user-images.githubusercontent.com/586911/143610531-4d0e1465-4847-4bb5-958b-90d07333adde.png)

(portrait monitors are the best)

**Comment by hyanwong** [comment]
It just says that you can't change your sponsorship details (i.e. the text on the leaves) on this form. So I don't think that's a contradiction is it?

I think we should have fewer asterisks in the "house name or number": maybe just 3?

**Comment by hyanwong** [comment]
> I think we should have fewer asterisks in the "house name or number": maybe just 3?

Or maybe we should not have asterisks, but put grey text in the background using the `placeholder` attribute of the text field that says something like

1. `<by default use the previous house name or number you gave us>` and
2. `<by default use the previous postcode you gave us (ends in "4LY")>`

(shorter text would be better, if we can phrase it right)

**Comment by lentinj** [comment]
Remaining TODOs:

- [ ] Gift aid form collapses after any rerouting back to the error page, should appear iff "I agree" is checked
- [ ] Renewals gift aid form should work equivalently, appearing iff "I agree" has been checked from previous sponsorship (if not show button)
- [ ] Renewals page with no images should have a "no image" image

**Comment by jrosindell** [comment]
A quick note to say that the HMRC length for the address field is 40 characters - this applies to whether it's a house name in the UK or a full address outside the UK.

**Comment by hyanwong** [comment]
This is done and tested
