### ISSUE TITLE
Re-enable display of endangered status / sponsorship

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#120]
We need to display endangerment of leaves as well as sponsorship.

Ideas for this...

Sponsorship should use the same logic as on the leaves in the normal tree scribing around the curve of the node

endangerment could either override the colour of the leaf to choose a special colour for endangerment or put a red ring around the outside of the leaf or place a semi transparent red circular haze behind the leaf in the rendering order - in the case of the haze the radius for it could be substantially larger than the leaves themselves as it would sit behind the tree, almost as part of the background.

**Comment by lentinj** [comment]
- [ ] We should hide the "please sponsor me" text

**Comment by lentinj** [comment]
Endangered leaves:
* Ring behind an otherwise unadultered leaf
  * Try both, and we experiment on experiment day
* Red or not red, no endangered brown
* Zooming out, it's just going to look like a ring
  * Can we get away with just a ring?
  * Naziah still reasonably happy with coloured dots.

* Happy with sponsorship rings.

**Comment by jrosindell** [comment]
Relating to endangered species visualisations - the (c) symbol related to images remains in an inappropriate position (and with inappropriate colours) considering that these leaves have full circular images inside them instead.

**Comment by jrosindell** [comment]
<img width="791" alt="yan" src="https://user-images.githubusercontent.com/3009279/45718115-df8dd100-bb93-11e8-9196-1c12a5015fd1.png">

**Comment by lentinj** [comment]
Position-wise I didn't have any better answers so left it there. I don't think there's anywhere it would sit natually and be associated with the image. It can't live near the text, and there are no corners for it to sit in.

What about just ditching it entirely and having an image copyright tab?

**Comment by jrosindell** [comment]
I'm happy to ditch and have an image copyright tab - that is probably the best solution for this view on the whole.

**Comment by jrosindell** [comment]
This seems like an appropriate place to record that the sponsorship text on OTOP should only be shown if the leaf has actually been sponsored (so no 'your name could go here' texts or anything like that - just leave blank in that case without changing the functionality on other views of course)

**Comment by lentinj** [comment]
The above hides the sponsorship text for OTOP, and moved the image copyright stuff to #144
