### ISSUE TITLE
Signpost in normal OneZoom view not quite right

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#124]
The blended rings around the SP no longer sit at the edge of the SP and instead sit inside with the wrong diameter. I'm pretty sure this used not to be the case so something changed for the OTOP view that has introduced this bug. See attached file.

**Comment by jrosindell** [comment]
![oz sp bug](https://user-images.githubusercontent.com/3009279/45026965-f1ba2c00-b037-11e8-98a2-ce15f7bcd213.png)

**Comment by lentinj** [comment]
It's not that the rings are the wrong radius, it's that several signposts are stacked atop each other, as the custom calc_center_point was putting signposts on top of the wrong node.
