### ISSUE TITLE
Colour glow jerking off and on

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#127]
Naziha (and I'm fairly sure I have) has noticed that the OTOP background haze can occasionally jerk onto full

**Comment by jrosindell** [comment]
I just discussed this with Naziha and we're not sure what is meant.

**Comment by jrosindell** [comment]
I've noticed that sometimes the rotating dynamic background spins too fast - is this the issue here?

**Comment by lentinj** [comment]
The dynamic background (from hazy memory), has 3 layers:

* A rotating set of stars
* A bunch of floating tree objects
* A translucent haze

All of which are implemented by javascript setting a random value for (in the case of the haze) translucency and colour every 10s and CSS animation gradually changing from the current value to the new target. In some case the haze ends up with high opacity suddenly.

The rotating stars are a similar case, that may be because it's going from (e.g.) 360deg to 10deg the wrong way around. But these need looking into anyway.

**Comment by jrosindell** [comment]
Thanks @lentinj for the details.....

**Comment by jrosindell** [comment]
This seems like a good place to record that Naziha also wants a full day of graphic design related decision making and associated tweaks to colours etc in the code.

**Comment by jrosindell** [comment]
Part of this requires uploading of custom images provided by Naziha.  I expect this will be something done at the level of the global database and we'll have the same images everywhere so not work likely to be needed from Jamie on this. However it has to be recorded

**Comment by lentinj** [comment]
> Part of this requires uploading of custom images provided by Naziha.

I did ask Naziha for a reworked star grid so I could implement my latest ideas for #104. Is this what this means, or is this something else, e.g. replacing the various ferns that float about?

**Comment by lentinj** [comment]
This could be a race condition between adding element to page, and firing off animation.

I also wonder here if it's really worth having a haze with a centre that moves about. It's soaking up ~10% of GPU thread to do so, for an incredibly subtle effect.

**Comment by jrosindell** [comment]
> > Part of this requires uploading of custom images provided by Naziha.
> I did ask Naziha for a reworked star grid so I could implement my latest ideas for #104. Is this what this means, or is this something else, e.g. replacing the various ferns that float about?

Not sorry, I wasn't clear again - Naziha wants custom images of animals etc. to be put on the tree it's not related to the star field but rather I turned this into a thread on graphic design issues more generally.  @lentinj I think it will not be you that has to implement these custom images as they can just be added to the database.

**Comment by lentinj** [comment]
Moved other comments to https://github.com/OneZoom/OZtree/issues/141

**Comment by lentinj** [comment]
The above increases the time between adding elements and setting opacity, which should cure any jerking of haze.

It also greatly simplifies the haze, instead of constantly regenerating it only changes when there is a new colour to use, this saves a lot of GPU time for what was a pretty subtle effect anyway.
