### ISSUE TITLE
Switch to Python3 for web2py?

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#129]
Now that it's been over  a year since web2py has "officially" supported python3 (>=3.6), I wonder if we should switch to python3 for everything? We already require it for other OneZoom scripts, so this would reduce the number of dependencies in our code. I'd be interested to know what @lentinj thinks - is it a good idea to make a (relatively) major switch like this, or just let sleeping dogs lie.

**Comment by hyanwong** [comment]
Thanks @lentinj . I think giving it a try in another branch (perhaps for 3.4) is probably the way forward. I don't think integer division is an issue. I think unicode might be (but in a good way). I'll try it out some time soon, and see what errors we hit.

**Comment by hyanwong** [comment]
By the way, when you try running under python3, it then becomes hard to switch back to python2 (several errors of the form "unsupported pickle protocol: 3"). This is possibly caused by session files or what-have-you. But otherwise OneZoom under python3 should work.

**Comment by kz12** [comment]
There are several errors if I'm running under python3.

When the schema is not loaded, the following error occurs: 'ModuleNotFoundError: No module named 'applications.OZTree'.

When the schema is loaded, it works well on the landing page. But the life.html page says that there is an OneZoom version error. And I can't load the appadmin page, it throws an error on Line 270 of that file.

**Comment by hyanwong** [comment]
I have python3 web2py working on my machine. Note, however, that we should change the `python2` command in `Gruntfile.js` to python3 too.

**Comment by hyanwong** [comment]
All now running under python3, apart from production which will be moved soon. Closing
