### ISSUE TITLE
Simple variable undeclared bug (config) in controller_anim.js

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#136]
When I try to go to a particular species via the URL, I am getting an error because the `fly_to_node` function can't access `config`. I'm not sure if this is a change brought about by @lentinj or @jrosindell, but it's a trivial fix for one of you two, I suspect.
```
[Error] Unhandled Promise Rejection: ReferenceError: Can't find variable: config 
(controller_anim.js: line 282)
	is_node_near_root (OZentry.js:26435)
	(anonymous function) (OZentry.js:26446)
	(anonymous function)
	promiseReactionJob
```

**Comment by lentinj** [comment]
Yup, https://github.com/OneZoom/OZtree/commit/49a028b67872630d4d1b9181f8dc85bcf09a3bfc didn't drag over the relevant import.

How can you trigger it?

**Comment by hyanwong** [comment]
Thanks Jamie. It happened when I clicked on the "violescent sea whip" link on the home page in the latest OneZoom version, on my laptop using safari. The link is `http://127.0.0.1:8000/life/@=115764`
