### ISSUE TITLE
OTOP view for creating screen casts (and initial dive from totem to human)

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#139]
There needs to be a version of the OTOP view from which screencasts can be generated.

Perhaps this should be a new URL OTOP_expert in which the settings icon is put back (so that image sources can be changed to public domain only from the default)

Also, add an option to the settings bar to make menus hide when mouse pointer leaves the window and come back say 1 second after mouse returns to the window - this will enable flights to be recorded.

Other features requested on this would be the option to turn off background elements so that the screencast can be done without them and they can be added back at the next step.

**Comment by jrosindell** [comment]
I personally think it would be nice if we're going to add flight animation settings to the settings bar that we have an option to turn on and off flights around the tree (when users search etc) and to be able to adjust the speed of the flight and the delay before the flight starts.  These settings would permit better screencasts - though I guess the delay and speed could be done via the console with written instructions to Naziha.

**Comment by lentinj** [comment]
So this is for generating the flight animations that get overlaid onto other video in OTOP, rather than a museum demo-mode like thing, correct?

I would have thought the most useful thing to do would be to have a page without any UI, entirely configured by URL:

* Re-triggering the animation is just reloading the page, which can be done via. keyboard (possibly it would be better to have a restart key). Either way, easily done without a UI getting in the way of your recording.
* Animations can be saved and shared with just the URL: This would also be very useful for reproducing errors for us, as well as for OTOP
* A relatively simple admin page (Like we were thinking for the museum stuff) could construct the URLs as required.

Aside from this, are we just doing a start/dest flight or are multiple hops desired?

**Comment by jrosindell** [comment]
> So this is for generating the flight animations that get overlaid onto other video in OTOP, rather than a museum demo-mode like thing, correct?

Yes it's not for the museum display it's for OTOP - the same applies to all things marked with label 3.3. Also, yes it's for remaking the films that you've already seen with the background elements being done by Naziha rather than in real time in OneZoom

> I would have thought the most useful thing to do would be to have a page without any UI, entirely configured by URL

One of the reasons why I suggests extra control buttons in the way described was that I think users might want to adjust the flight speed and whether or not to fly and hence they could be in the settings menu. There is less case for turning on and off graphic layers in there, but for the expert view with SVG capture I can see how having a layer display switch would be good.

Having said this I think you're right that for recording a screencast for any purpose you want to reload to start based on settings in the URL, I agree. Also, if we had the settings in the control bar on any views then the professional thing would be to make those settings be reflected in the URL as well so that reloading doesn't loose the settings. Please can you comment on whether you agree with this sentiment.

> Aside from this, are we just doing a start/dest flight or are multiple hops desired?

Yes it's just from A to B though this can require a zoom out and then a zoom in again.

My final thought on this is a mild concern about making the URL too long and complex given that there is already quite a lot in the URL and the back button features suggest problems with this part of the code as it is #140.  Please can we have a discussion about what the URL format should be so that it's consistent with the existing format and future proof

**Comment by jrosindell** [comment]
Things to consider

`http://www.onezoom.org/life.html/@Mammalia?init=zoom`
`http://www.onezoom.org/life.html/@cellular_organisms=93302`

the @ parameter gives the start position and we use an = within this to distinguish between the name of the place and the OTTID - the latter being more stable whilst the former being easier to construct for a lay user and providing some degree of redundancy if both are used together.

There is already a problem that we cannot target areas which don't have an OTTID and that will require more complex logic which is not for now but definitely involving more complex aspects.

Use of the parameters 

`http://www.onezoom.org/life.html/@cellular_organisms=93302?init=zoom`

can be used to specify things like the behaviour on load so this would be the place to specify that we want init=flyto or something like this. Except where then do we specify the destination of the flight. It's inelegant that we can't use the same method for specifying the start and end point of the flight with the same syntax.

**Comment by lentinj** [comment]
I think the way to do this is to overload the init parameter, e.g. ``@Mammalia?init=541928:fly`` suggests that OneZoom starts at Elephant and zooms out to rest at Mammalia, the second parameter determining the type of flight. The ``@`` part of the query always determines the final point.

We could expand this for multi-hop flights easily enough: ``@Mammalia?init=541928:fly&init=782900:pan``

> It's inelegant that we can't use the same method for specifying the start and end point of the flight with the same syntax.

Agreed, doing ``life/@Elephant=541928/@Mammalia`` would be neater as a series of instructions, but this won't play nice with the updating of history for the current location.

> the back button features suggest problems with this part of the code as it is #140

That's irrelevant to this discussion, the deeper problem there is that the history management is using it's own flight code.

> One of the reasons why I suggests extra control buttons in the way described was that I think users might want to adjust the flight speed and whether or not to fly and hence they could be in the settings menu. 

Given the intended output, I don't think just speed is necessarily most interesting tweakable. Rather "real-time flight" or "high-quality flight". Where the latter not only moves less in each animation step, but develops much more of the flight path before starting. From a video editor's point of view they just want lots of high-quality frames. they can then worry about the speed afterwards.

>  Also, if we had the settings in the control bar on any views then the professional thing would be to make those settings be reflected in the URL as well so that reloading doesn't loose the settings.

Yes, definitely.

**Comment by jrosindell** [comment]
> Agreed, doing life/@Elephant=541928/@Mammalia would be neater as a series of instructions, but this won't play nice with the updating of history for the current location.

I wonder if this is in fact preferable because it enables

 `life/@Elephant=541928/@Mammalia=834747` for consistency and robustness between the start point `@Mammalia=834747` and the end point `@Elephant=541928` also it enables the `@Elephant=541928` syntax to be updated later for something else more robust that works everywhere.

My idea would be that if one goes to `life/@Elephant=541928/@Mammalia=834747?init=fly`

then you get a flight from mammals to elephants and the moment you reach elephants the URL / history is updated to show that the user is at life/@Elephant=541928 hence if the user explores from here and pressed back they get back to elephant but if they press back enough they see the flight again - of course the URL should not be updated during the flight itself.

`@Mammalia?init=541928:fly`

is not ideal because the `541928` part cannot be changed to say `init=Elephant=541928:fly` because of the effect of the second = sign.

> Given the intended output, I don't think just speed is necessarily most interesting tweakable. Rather "real-time flight" or "high-quality flight". Where the latter not only moves less in each animation step, but develops much more of the flight path before starting. From a video editor's point of view they just want lots of high-quality frames. they can then worry about the speed afterwards.

Very good point - if possible let's have real time and high quality options in the URL and a flight on/off option in the control panel for the ordinary OneZoom

**Comment by jrosindell** [comment]
Another advantage of the `life/@Elephant=541928/@Mammalia=834747?init=fly` assuming that it's allowed in URL rules is that the concept could later (not as part of OTOP) be extended to encode tours e.g.

`life/@Elephant=541928/@Mammalia=834747/=823607?init=fly` would give a three point tour.

**Comment by lentinj** [comment]
@jrosindell The above re-jigs the fly_to_node() code to make this easier to add in, but we lose is_node_near_root() as a result. In theory zoomout() will also check that we don't go too far out as well, but it's boundaries are far more broad than is_node_near_root(). is_node_near_root() feels far too over-engineered to me, especially given how much of an edge case this is.

* Is the configuration value, config.minimum_ratio_for_zoom, get set to anything other than the default?
* How much of an issue is this, generally? Are people regularly pzooming to anything above Opisthokonta?
* If we do need something here, can we add it to zoomout() (and deprecate config.minimum_ratio_for_zoom in the process)?

**Comment by lentinj** [comment]
@jrosindell The above re-jigs the fly_to_node() code to make this easier to add in, but we lose is_node_near_root() as a result. In theory zoomout() will also check that we don't go too far out as well, but it's boundaries are far more broad than is_node_near_root(). is_node_near_root() feels far too over-engineered to me, especially given how much of an edge case this is.

* Is the configuration value, config.minimum_ratio_for_zoom, get set to anything other than the default?
* How much of an issue is this, generally? Are people regularly pzooming to anything above Opisthokonta?
* If we do need something here, can we add it to zoomout() (and deprecate config.minimum_ratio_for_zoom in the process)?

**Comment by jrosindell** [comment]
> * Is the configuration value, config.minimum_ratio_for_zoom, get set to anything other than the default?

Not at present

> * How much of an issue is this, generally? Are people regularly pzooming to anything above Opisthokonta?

pzoom is the standard entry method for e.g. new sponsors of leaves.  Is there a strong reason to lose this functionality?  Having said this, I wonder if ideally we want to just make the normal zoom able to be fast or clear enough for longer journeys without using pzoom

> * If we do need something here, can we add it to zoomout() (and deprecate config.minimum_ratio_for_zoom in the process)?

I see what you mean, you'd like the starting point of a pzoom to be enforced as not being too far out using the same logic that prevents zoomout from zooming out too far - this seems sensible to me.

**Comment by jrosindell** [comment]
What I'm more concerned about pinning down from this issue is the answer to the format for URL parsing... @lentinj do you have any further thoughts on this further to my suggestions above?

**Comment by hyanwong** [comment]
I don't know how web2py will deal with a URL like `onezoom.org/life/@Elephant=541928/@Mammalia=834747`. I think it should cope fine if there is a 'default' in there, like `onezoom.org/default/life/@Elephant=541928/@Mammalia=834747`, as it treats this as `server/controller/function/arg1/arg2/arg3`, but I don't know how it decides that the first form is `server/function_in_default_controller/arg1/arg2/arg3`, and doesn't mistake arg1 for the controller.

**Comment by hyanwong** [comment]
Also @jrosindell I thought we had decided *not* to encode tour points in the URL, but instead have them saved on the server?

**Comment by lentinj** [comment]
@jrosindell:

> pzoom is the standard entry method for e.g. new sponsors of leaves. Is there a strong reason to lose this functionality?

I'm not suggesting losing pzoom, obviously that get used, I'm suggesting losing ``config.minimum_ratio_for_zoom`` / ``is_node_near_root`` to stop pzoom from starting too far out. For it to be useful, you have to set pzoom into very early levels, which I can't imagine happening very often. The logic could be replaced with "don't pzoom into the root itself" and I don't think anyone would notice.

> I wonder if ideally we want to just make the normal zoom able to be fast or clear enough for longer journeys without using pzoom

I think in the bulk of cases, speeding up the zoom to a few seconds (so people don't get bored waiting) would have to go so fast that the blur would be meaningless. pzoom feels like the right compromise to me.

> What I'm more concerned about pinning down from this issue is the answer to the format for URL parsing... @lentinj do you have any further thoughts on this further to my suggestions above?

All valid, I suspect that there's going to be a technical restriction that pushes it one way or another (like @hyanwong has suggested), which is why I've been pushing ahead with the implementation, coming back to the URL parsing at the end, which is fairly well contained anyway, and I'm making it more contained with the above.

My biggest worry at this point is that expecting for the flight to run on startup is creating far more work for ourselves. Generating a projector-quality flight at start-up means we *have* to make sure that all nodes are developed/detailed as required before the flight starts. In particular:

* We don't wait for node details before displaying the tree, it's currently just hidden for a few seconds after load has notionally finished in OTOP and we hope that's enough. But in this case that means we miss the start of the flight. We'd have to change the loading to wait for node_details to arrive, then display the tree and consider starting the flight.
* Nodes after the end point are often not developed in polytomy. I think I know why, but if I triggered the zoom manually I can zoom around and develop whatever needs to be developed first.

None of this is wasted work, but it isn't seeming the easy path any more.

**Comment by jrosindell** [comment]
> I'm not suggesting losing pzoom, obviously that get used, I'm suggesting losing `config.minimum_ratio_for_zoom` / `is_node_near_root` to stop pzoom from starting too far out. For it to be useful, you have to set pzoom into very early levels, which I can't imagine happening very often. The logic could be replaced with "don't pzoom into the root itself" and I don't think anyone would notice.

Thanks for clarifying, I see what you mean and I agree with this decision.

**Comment by jrosindell** [comment]
> * We don't wait for node details before displaying the tree, it's currently just hidden for a few seconds after load has notionally finished in OTOP and we hope that's enough. But in this case that means we miss the start of the flight. We'd have to change the loading to wait for node_details to arrive, then display the tree and consider starting the flight.
* Nodes after the end point are often not developed in polytomy. I think I know why, but if I triggered the zoom manually I can zoom around and develop whatever needs to be developed first.

None of this is wasted work, but it isn't seeming the easy path any more.

Hmmm, I see exactly what you mean by these issues.  The only thing is I'm not sure there is a reasonable alternative.  If we didn't access the flight by URL then we'd still have the same issues, unless we provided a control panel of some kind with buttons to preload different things and select the flight points then start.

**Comment by jrosindell** [comment]
> Also @jrosindell I thought we had decided _not_ to encode tour points in the URL, but instead have them saved on the server?

Yes we had decided this and I agree with this decision - however the conversation has come about because Naziha wants a way to record high quality screencasts between a predefined pair of points and Jamie thought that a URL parsed way to defining the required flight was the easiest way to manage it.

**Comment by lentinj** [comment]
NB: We also need this so the app can use it to fly to the human leaf

**Comment by jrosindell** [comment]
The initial dive should already be functional using `/@Homo_sapiens=770315?init=zoom` unless something has changed

**Comment by lentinj** [comment]
...but not from the totem animal to the Human leaf. The app should probably be doing the above for now though.

**Comment by jrosindell** [comment]
Ah OK I see now what you mean.  I think we should leave it for now until some testing has been done.

**Comment by lentinj** [comment]
Removing essential mark in that case.
