### ISSUE TITLE
Add custom images to OTOP tree

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#141]
From the desk of jrosindell -

> This seems like a good place to record that Naziha also wants a full day of graphic design related decision making and associated tweaks to colours etc in the code.

> Part of this requires uploading of custom images provided by Naziha. I expect this will be something done at the level of the global database and we'll have the same images everywhere so not work likely to be needed from Jamie on this. However it has to be recorded

> Naziha wants custom images of animals etc. to be put on the tree it's not related to the star field but rather I turned this into a thread on graphic design issues more generally. @lentinj I think it will not be you that has to implement these custom images as they can just be added to the database.

**Comment by jrosindell** [comment]
Thanks @lentinj I think you're right that this is better in a separate issue.  One thing though is that I think Naziha wants to involve you in this graphic design day as well during the current sprint.

**Comment by jrosindell** [comment]
I think the outstanding issue here is getting the custom images into OneZoom

**Comment by hyanwong** [comment]
What species this hummingbird? It's one of the images I think Naziha wanted.
![27294431](https://user-images.githubusercontent.com/4699014/54624136-b5df3500-4a64-11e9-95ec-fb00979103d0.jpg)

**Comment by jrosindell** [comment]
I think this is done now via e-mails so I'm tentatively closing the issue
