### ISSUE TITLE
Branch-drawing artifacts at some zoom levels

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#143]
For example:-

![cy2](https://user-images.githubusercontent.com/3009279/51949100-27b2df00-2423-11e9-959d-734dd2905015.jpg)

Something like the OTOP branch code ignoring the fact that the node is off-screen and not properly developed, but I'm not sure.

**Comment by jrosindell** [comment]
Please note that exactly the same artefacts occur in the polytomy view too in case that helps find the cause

**Comment by lentinj** [comment]
The lines in question come from the "fans" from fake nodes. A node off-screen has a very unrealistic node radius.

One part of this could be that currently, ``radius = node.rvar + node.arcr * 0.9`` (note ``+`` not ``*``). This seems wrong in comparison to circle_leaf_shapes() say, but largely gives the right answer. "Fixing" it results in fake fans that are way too small. The answer is probably somewhere in the initialisation (or lack thereof) of rvar/arcr.

**Comment by jrosindell** [comment]
is this formula being used only for fake fan sizes and not anywhere else? If so then I think it would be OK to change it to use the same formula that would determine a real fan size.

In the past there have been numerous issues where items that are far away / off screen end up getting printed on screen erroneously due to some numerical error - I think this is what is happening here - there needs to be some logic involving the horizon areas of the nodes, and maybe involving their scale too that prevents them from being drawn.  Something similar is done for node arcs I think - if they are radically huge in size we don't draw them.

**Comment by lentinj** [comment]
I considered something like that, but the problem is fake fans can genuinely be this big too, it's not as simple as saying "if radius > lots, ignore".

But I shall rummage and see what I come up with.

**Comment by jrosindell** [comment]
> I considered something like that, but the problem is fake fans can genuinely be this big too, it's not as simple as saying "if radius > lots, ignore".

Agreed!  We need to determine if the fake fan is being drawn on an ancestor node to the nodes actually on screen (in which case it's wrong to draw a fake fan in the first place) or if the fake fan is a cousin to the nodes on screen (in which case the next step is to determine why it passes the test to be drawn at all when it should be off screen)

I suspect that what is happening is that the fake node is a long distance away from what is on screen in terms of the hierarchy, it's a very distant cousin, and machine error in the tests for whether it intersects with the viewport are what is causing the bug.  I had exactly this bug with the node circles themselves a very long time ago.  I cannot recall what the solution was, but I think it implemented to test for drawing that required nodes to be sufficiently close to the root node or sufficiently close to the nodes on screen in terms of their position in the hierarchy.

**Comment by lentinj** [comment]
Zooming into Boreoeutheria, the artifact is fairly obviously coming from the Mammals node when it goes off-screen.

**Comment by lentinj** [comment]
There's 2 problems here.

* As noted, the distance calculated is incorrect.
* We don't take child node richness into account when spacing branches, they're just spaced equally. Whilst when generating a little fan this is fine, but if it's large (especially large and offscreen) we generate artefacts as the fake fan puts a branch on-screen that shouldn't be there.

**Comment by lentinj** [comment]
Right, I think this is fixed with the above. Details in the commit messages, but basically the fake fans were a little too naive.

This is all getting a bit ugly with rendering of branches spilling into leaves, and would appreciate a rethink at some point, but out of the woods for now.
