### ISSUE TITLE
Move image copyright to tabs

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#144]
From https://github.com/OneZoom/OZtree/issues/120:

> Relating to endangered species visualisations - the (c)  symbol related to images remains in an inappropriate position (and with  inappropriate colours) considering that these leaves have full circular  images inside them instead.

> Position-wise I didn't have any better answers so left it there. I don't think there's anywhere it would sit natually and be associated with the image. It can't live near the text, and there are no corners for it to sit in.

> What about just ditching it entirely and having an image copyright tab?

**Comment by lentinj** [comment]
The above adds an image copyright tab for OTOP, but it's a lot messier than I originally expected it to be:

* Alter the definition of ``OZ_leaf_json_url_func`` to take a node object, not a OTT (This seems cleaner to me anyway, but the rest of the functions ought be changed).
* Define a ozpicinfo tab
* Add node's pic_src / pic_fn to the end of the leaf_linkouts URL, if present create a ozpicinfo tab URL.

The other choice would be for leaf_linkouts and/or pic_info derive which image was chosen based on OTT, but how to do that (if possible) isn't obvious.

I don't really like changing the definitions of 2 public functions either.

Any other suggestions? Or feel for how urgent this is?

**Comment by jrosindell** [comment]
I think it's not urgent - I would worry about removing the copyright to an image copyright tab because we don't want to be accused of infringing the CC-BY licences which require fair acknowledgement of the author.

**Comment by lentinj** [comment]
OTOP aside, I think that it would be more consistent for Image information to be in a tab. The © can link direct to that tab, like sponsorship does.

**Comment by hyanwong** [comment]
The reason why it isn't in the tabs is that one node can potentially be associated with many different images. So they seem like different sorts of things to us - I think of the popup tabs as showing stuff uniquely to do with a node or tip. 

It's true that this might not be obvious to the user. But it seems weird to have different tabs depending on whether e.g. you toggle public domain images or not.

**Comment by hyanwong** [comment]
Re: using node IDs not OTTs, the main (only) reason for using OTTs is that they are persistent across tree versions, whereas node IDs can change. That means we shouldn't really use URLs that contain node IDs as identifiers, as they are not guaranteed to go to the same place in the future. That's why we defaulted to always using OTTs where possible. Since every leaf (but not every internal node) should have an OTT, we used OTTs for identifying which leaf had tabs open.

**Comment by lentinj** [comment]
> The reason why it isn't in the tabs is that one node can potentially be associated with many different images

I think there'd be one "image information" tab that listed all potential images, rather than a tab per-image.

Listing all images (including ones that weren't actually used) might be a bit confusing, but OTOH could demonstrate what you would have got if you turned on public domain images, e.g.

**Comment by hyanwong** [comment]
Also some images are not valid for display in some settings. E.g. we might have Linnean-society-only images which are only displayed in a bespoke tree, but are nevertheless present in the DB. So we'd have to implement extra logic in the tab to decide which are relevant to show. It's all very complicated, and indirect. Much better to pop up just a single thing for that particular image (which the user could possible rate, etc)

**Comment by hyanwong** [comment]
I think we should close this - I'm not convinced about moving the image copyrights into a tab - what do you think @lentinj ?

**Comment by lentinj** [comment]
@hyanwong the origins of this is simply that the © gets in the way in the OTOP circular leaf design. We have lived with it thus far, so given how controversial it is it can just be ditched.

**Comment by hyanwong** [comment]
Yes, my thought too. Will close, thanks
