### ISSUE TITLE
Image fetching infinite loop

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#147]
Whilst zoomed into ``/otop/@Deilephila_elpenor=3093426#x6932,y-10801,w1.9192``, I've noticed that my browser is stuck in an infinite loop of requesting ``/API/image_details.json?2=25808649``. It's obvious why looking at the response.

```
{"headers":{"src":0,"src_id":1,"licence":3,"rights":2},"image_details":[]}
```

If the server didn't know about the image, we shouldn't just ask again. Not sure if this is something for server-side or client-side though.

@hyanwong I thought you might find this interesting. I'm not sure which node is asking for the image though, unfortunately.

**Comment by hyanwong** [comment]
Ah, that's a good catch. Thanks. You can find the node by looking for `src_id = 25808649` in images_by_ott. In my local database, this gives `ott=3093426`, which is `Deilephila elpenor` itself (looked up in ordered_leaves).

**Comment by hyanwong** [comment]
p.s. this image should now have `src=99`, not `src=2` (i.e. the call should be `/API/image_details.json?99=25808649`. I'm not quite sure why it's got this wrong.

**Comment by lentinj** [comment]
> I'm not quite sure why it's got this wrong.

This was on my local setup, so it could just be my database being horribly out of date.

**Comment by hyanwong** [comment]
At, true. Still, we should avoid infinite loops, even on broken setups.

**Comment by hyanwong** [comment]
I assume it would be sensible to implement a client-side fix in the js codebase, as it's a bit fragile to rely on (just) server side stuff. Is this something that @lentinj can do, or should I see if either myself or @jrosindell can do it?

**Comment by lentinj** [comment]
The main thing is to make the error visible I guess. The easiest thing could be that if the server doesn't have anything for any of the requested images, it could return an error rather than miss it out. Then it should be obvious in the server logs that there's an inconsistency somewhere that needs looking into, and the client won't infinite loop because we're guaranteed to get results (or a 500 response).

This said, it wouldn't be a big deal to stop the infinite loop as is, if it's easier to log the missing item for example.

**Comment by hyanwong** [comment]
@lentinj is this fixed now?

**Comment by lentinj** [comment]
Actually, it turned out to be fiddlier than I thought to stop the infinite loop, since nothing clientside records what was requested from the server. Then I forgot about it.

You can trigger this on beta, which I hadn't realised before, by zooming in very close to a node e.g. http://beta.onezoom.org/life/@Ornithorhynchus_anatinus=962377 Presumably it's more obvious on OTOP because the images are larger, and it's fetching a particular resolution that's failing.

Having a quick look at this:-

https://github.com/OneZoom/OZtree/blob/master/OZprivate/rawJS/OZTreeModule/src/api/image_details.js#L26--L30

...is fairly obviously nonsense, and would easily explain why it's fetching with ``2=123456789`` instead of ``99=123456789``.

Is there a reason to assume that ``pic_src`` is 2 if unrecognised? Or can we just assume that ``pic_src`` is valid, and replace all this with something like ``data[node.pic_src] += node.pic_filename``?

**Comment by hyanwong** [comment]
Thanks @lentinj. With the most recent release we shouldn't assume `pic_src` is 2 if unrecognised, no. In fact there are now several more values that `src` can take, so it looks like this needs to be generalised such that we don't refer to `src_id_with_src_1` and `src_id_with_src_2` any more, but store both the src_id (which is the image filename) *and* the proper `src` (now changed to (usually) 2, 3, 30, or 99 (see [here](https://github.com/OneZoom/OZtree/blob/5e71611ee77c9c90d8231dad87b004198cc999e5/models/_OZglobals.py#L55)

**Comment by hyanwong** [comment]
I'm not sure why we don't just do:

```
  let data = {};
  for (let i=0; i<length; i++) {
      if data.hasOwnProperty(image_data[i].src) {
          data[image_data[i].src].push(image_data[i].src_id);
       } else {
         data[image_data[i].src] = [image_data[i].src_id];
    }
  }
```

**Comment by hyanwong** [comment]
And having looked at this, I have no idea why images are carrying on working on the main website, as nearly all images on OneZoom now have `src=99` (old EoL images). Weird...

**Comment by lentinj** [comment]
> I'm not sure why we don't just do:

Indeed. I'll rewrite it later this week.

> I have no idea why images are carrying on working on the main website

image_details don't seem required to display images, or their copyright. As you say, image_details is basically entirely broken, but there's no obvious problems bar the infinite requests. It could be that the whole mechanism is redundant.

**Comment by hyanwong** [comment]
@lentinj I'm not sure how this relates to the infinite loop, though? I could change the image API to return a list of unmatched image too - I assume that would help?

**Comment by lentinj** [comment]
> I'm not sure how this relates to the infinite loop, though?

It goes back to being a hidden non-issue.

> I could change the image API to return a list of unmatched images too - I assume that would help?

Yeah, returning null rows for missing entries would definitely help.

**Comment by hyanwong** [comment]
> > I'm not sure how this relates to the infinite loop, though?
> 
> It goes back to being a hidden non-issue.

Ah, I see.

> > I could change the image API to return a list of unmatched images too - I assume that would help?

OK, that seems clean too. I will do this too, just to make sure.

Now that you mention it, I think I remember why image_details is separate: we don't need the copyright etc information for all images on the OZ canvas, only once we zoom in to high enough level to show the copyright text. So we didn't want to make loads of requests for (potentially) long strings for many images that we were never going to show.

**Comment by hyanwong** [comment]
@lentinj : the API just makes an SQL call where `src_id IN(1,2,3...)`, so it's not a single-liner to output null rows. I'm wondering if it would be easier anyway to return a keyed object rather than an array of image_details, like 

```
image_details = {'2':{'1234':[rights1,licence2],'5678':[rights1,licence2]},'99':{'2345':null}}
```

**Comment by hyanwong** [comment]
@lentinj like this: https://github.com/OneZoom/OZtree/tree/image_details-repair

Obviously the javascript code will need to be changed to parse this structure.

**Comment by hyanwong** [comment]
@lentinj - do you want to change the js code to parse the new JSON return value from `image_details.json` (as [above](https://github.com/OneZoom/OZtree/issues/147#issuecomment-478632274)), then I can push the API change?

**Comment by lentinj** [comment]
Yeah I will once I've looked into some of the other problems lurking about. Won't take very long.

**Comment by lentinj** [comment]
@hyanwong I've merged this into 3.3 and changed the JS to match. So when 3.3 gets merged to master (which should happen soon) this can be pulled in too.

Sound good?

**Comment by hyanwong** [comment]
Perfect, thanks!

**Comment by hyanwong** [comment]
(I guess it works on your setup now?)

**Comment by lentinj** [comment]
> (I guess it works on your setup now?)

Yeah, all good. There wasn't anything wonky about my database after all, just needed the changes above.
