### ISSUE TITLE
Search box should be reduced to magnifying glass button on mobile-sized screens

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#152]
When there's a partner logo, there's currently not enough room for both. Without, the dropdown isn't particulary roomy anyway.

On mobile, search should be a button that expands to the width of the screen on expanding.

**Comment by jrosindell** [comment]
Yes I agree, this is a great solution and it should be implemented ultimately across all OneZoom pages, not just the OTOP page

**Comment by lentinj** [comment]
Should be done, I think it's worth doing.

**Comment by jrosindell** [comment]
the mouse over / clicking is strange but needs to be tested on mobiles to be sure it's OK

**Comment by lentinj** [comment]
Yes, there's safari mouseover issues. However, now at least the OTOP logo won't be there, this isn't strictly necessary.

Do we want to try and fix it up, or just revert it?

**Comment by lentinj** [comment]
This is only a problem with desktop Safari 10 and below, where unless you enlarge fonts significantly you can't actually trigger it anyway, since browser windows won't go small enough. Chrome/Firefox/IE/Mobile Safari are all fine.

I don't think it's worth spending time on.

**Comment by jrosindell** [comment]
Agreed, I think this is all good and thus I'm closing the issue
