### ISSUE TITLE
non unique OTTids cause break down on URL parse

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#160]
I've noticed that OTT 641033 is not uniquely mapped to a node in our database and this causes an error when we go to 

http://www.onezoom.org/life.html/@=641033

**Comment by hyanwong** [comment]
Oh, well found. We need to squash this sort of thing.

**Comment by hyanwong** [comment]
Fails with `<type 'exceptions.KeyError'> 'real_parent'` on the line starting:

```
if tt_info[root_id]['real_parent']:
```

in life.html

**Comment by jrosindell** [comment]
Great!  I wondered though do we not want to avoid having non unique OTTids at all in the tree data itself?

**Comment by hyanwong** [comment]
We probably do, but it's unavoidable sometimes.

**Comment by hyanwong** [comment]
As we have to do taxon mapping for all the bespoke species, and sometimes they map to the same OTT. So which do we choose to include if so?

**Comment by hyanwong** [comment]
So problem (a) is that the text version of the tree doesn't like it. I can fix this, which then reveals the second problem, which is the URL parser doesn't like it either! You can see this because the `life_MD` version doesn't have an underlying text tree, so the next bug is revealed. See 

http://www.onezoom.org/life_MD/@=641033

**Comment by hyanwong** [comment]
Any idea what's causing that?

**Comment by hyanwong** [comment]
I think the "Error: Sorry the species or groups you asked for is not on the tree" dialog box is popped up by the javascript code, so perhaps @lentinj could see why this is triggered if the ott matches 2 separate rows (we should probably just take the first returned value)

**Comment by lentinj** [comment]
> I think the "Error: Sorry the species or groups you asked for is not on the tree" dialog box is popped up by the javascript code

Yes, and it's also triggered by **any** javascript error in the search process, not just a failure to find anything. IIRC I've added in some log messages for the actual error message now instead of it just being eaten, but don't let it mislead you.

**Comment by hyanwong** [comment]
Ah, that makes sense. @lentinj: would it be an easy fix to simply zoom in to the first of the OTT hits? (A bit hack, but this is very much an edge case)

**Comment by jrosindell** [comment]
> As we have to do taxon mapping for all the bespoke species, and sometimes they map to the same OTT. So which do we choose to include if so?

I see what you mean, but we're using OTTids in a special way e.g. for sponsorship and other operations of the site.  I incline to think they should be unique in the database and that when repeated IDs appear the IDs are removed to enforce uniqueness.  I terms of how to remove, I'd suggest either see whether the assurance of the mapping is greater in one case than another and otherwise retain whichever OTTid is higher up the tree.

It's worth bearing in mind that if we move over in future to a tree that's 100% provided by open tree then this issue should not occur

**Comment by jrosindell** [comment]
I've labelled this as a v 3.3 thing mostly to keep recent / prominent bugs on our radar - only v3.3 essential labels will be fixed before the release of v 3.3 and the rest will probably get pushed back to v 3.4

**Comment by hyanwong** [comment]
Sure. I'm pretty sure we catered for this in sponsorship, and we have banned sponsoring any species with duplicate OTTs. 

It might also be the case that we only have duplicate OTTs for nodes, not leaves. I think we should code defensively and assume that we *might* have a few (rare) duplicate OTT nodes. Or at least, if we do, we cope with it relatively gracefully (hence my comment about hacking round the javascript 'badOTT' problem).

**Comment by lentinj** [comment]
> would it be an easy fix to simply zoom in to the first of the OTT hits?

What (should) happen when ``search_init`` is asked to find an OTT with duplicates? Asking for 641033 currently seems to produce ``{"empty":"641033"}``.

If it returned an array of IDs, the javascript could just grab the first easily enough.

**Comment by hyanwong** [comment]
Ah, OK. I can fix that. I assumed it would return an array, but I see at https://github.com/OneZoom/OZtree/blob/c1f97e63ba62c4698873eeffe04cbd7dffb58ae2/controllers/API.py#L233 that it bombs out instead. I'll change that. Thanks for the triage.

**Comment by hyanwong** [comment]
I've altered this to return an array, sorted by ID. Fixes are in https://github.com/OneZoom/OZtree/tree/fix-multiple-ott-hits. @lentinj: I'm not familiar with the JS, which will need to be altered since we now return an array of ids. I've attempted to correct it in https://github.com/OneZoom/OZtree/commit/99839389169b8ea0bb81a709ebaaa31feea4bdc8#diff-178bff657fe0dcdb3c1d8fc0f3450edd - but I think I've got it wrong. Can you suggest corrections?

**Comment by lentinj** [comment]
> if ((res.ids) && length(res.ids)) {

``Array.isArray(res.ids)`` is probably what you're looking for, also any lookup in an object will return ``undefined`` if something isn't there, as opposed to KeyError in Python, so you don't need the former part of this condition.

Although having 2 places to look seems a bit ugly to me, maybe either:

* Make a breaking API change, always return ids and we look up the first item in the array regardless.
* Always return ids, and id is always the first item in that array.

**Comment by hyanwong** [comment]
I agree about 2 places. Happy to make a braking API change and always look up the 1st item (I had intended this)

**Comment by hyanwong** [comment]
Fixed with https://github.com/OneZoom/OZtree/pull/164 (it worked, but I forgot to clear caches on testing)
