### ISSUE TITLE
OTOP Intro / help links

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#162]
- [x] "How to use" re-displays the slideshow
- [x] Make it more obvious in the slideshow that this is OneZoom(tm) @jrosindell can you provide some text?
- [x] Ditch rest of (i) menu

**Comment by lentinj** [comment]
Here we recycle the singleInfoButton, but display our slideshow instead.

The right way of doing this would have been to override the ``about_plus_data.load`` include, that singleInfoButton populates it's modal with, but there isn't a override mechanism for this, and regardless to get the slideshow as required we'd need to jiggle about with the modal structure a fair bit, so in the end wouldn't necessarily be cleaner.

Remaining item is to insert required text into the slideshow

**Comment by lentinj** [comment]
jrosindell:

> Along with the following text "Tree of life explorer provided by" (and then the logo)

**Comment by lentinj** [comment]
@jrosindell kinda like that?

**Comment by jrosindell** [comment]
Thanks @lentinj, this looks great but a few quick suggestions...

the 'titles' of each section should be centred
"you can freely explore it" would be better wording to "freely navigate in it" for page 1

**Comment by lentinj** [comment]
> "you can freely explore it" would be better wording to "freely navigate in it" for page 1

It's Naziha's wording, so probably best to check with her (not that I can imagine it being a huge problem).

**Comment by jrosindell** [comment]
I've asked Naziha about this - will post response later.

Meanwhile please change the image source to 

OZ_logo5_grey3_inv.png

which is inverted to work as white on black (the original logo was a black on white one)

**Comment by jrosindell** [comment]
The change is approved

> Yes of course. Jamie has to integrate the new sentence.

**Comment by jrosindell** [comment]
Thanks @lentinj this is all good now.  Closing issue

**Comment by jrosindell** [comment]
I've reopened this because Naziha has said she would like a way to show or not show the intro and for this to be reflected in the URL.  It could be an entirely different page with no help screen if that's easier but I suspect it would be better to have a URL flag for showing (or not) to introductory help slides.

**Comment by lentinj** [comment]
Done with the above, ``?otop_init_slideshow=off`` to get rid of it.
