### ISSUE TITLE
Polytomy view switch hack repair

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#163]
I've implemented this in a commit just now, it works but is a bit hacky as I have to reload the page when switching from polytomy view back to any of the other views.  Without a page reload the switch doesn't work properly.  Obviously this can be made better, but it will have to do for now.

**Comment by jrosindell** [comment]
Related to this - when switching to a different view - the new view should be centred on the same OTTid that appears in the URL (i.e. - it's close enough to staying in the same rough position but with a new view type)

**Comment by lentinj** [comment]
Commit in question: https://github.com/OneZoom/OZtree/commit/0a98e8b54ec61fdc589f71e89618667d36793745

**Comment by lentinj** [comment]
The above fixes the bugs I could find, then removes the force-page-reload hack.

It still doesn't center on the previous OTTid yet, I'll look at that next.

**Comment by lentinj** [comment]
...and that's done too, after a little refactoring. Like you say, it's effectiveness depends on the node, but gets you in the rough neighborhood.

**Comment by jrosindell** [comment]
Hmmm, It seems to reload the page still when switching from polytomy back to another view type.  Also, I don't find that it recanters the tree in an appropriate place after the view change.

**Comment by jrosindell** [comment]
Fixed!  Thanks @lentinj closing the issue now.
