### ISSUE TITLE
Sponsorship text for case where sponsored and awaiting verification

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#167]
If you look here you can (at the time of writing) see an example of the text that should appear

http://www.onezoom.org/life.html/@Daubentonia_madagascariensis=5072

in cases where verified_time is NULL whilst reserve_time is in the recent past.

I suspect that in editing this code for OTOP some logic has got lost that captures this case and puts different text on there "THIS LEAF HAS BEEN SPONSORED, TEXT AWAITING CONFIRMATION"

**Comment by jrosindell** [comment]
I'm labelling it as essential just to distinguish it out as requiring some thought at least - if this is a new thing introduced by OTOP then it should be solved

**Comment by hyanwong** [comment]
This will be a test of the cron job that moves expired reservations to the `expired_reservations` table (version 3.5), and so can be closed here.
