### ISSUE TITLE
Issues on initial TOL load for OTOP

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#170]
When I click on the x button after loading the TOL the search sometimes comes up and this causes a problem.  This happens when the x ends up on top of the search icon due to small screen size.

Another thing is that the OTOP initial flight seems to be zoom out from a strange location to humans.  Better is to zoom in with init=pzoom so that the tree is on screen the whole time.

**Comment by lentinj** [comment]
> Another thing is that the OTOP initial flight seems to be zoom out from a strange location to humans. Better is to zoom in with init=pzoom so that the tree is on screen the whole time.

That'll be down to whatever querystring the app is using, I don't have control over that.

**Comment by lentinj** [comment]
> When I click on the x button after loading the TOL the search sometimes comes up and this causes a problem. This happens when the x ends up on top of the search icon due to small screen size.

Is this only in the iOS app? All seems to work fine in iOS safari and other browsers.

**Comment by lentinj** [comment]
The closest I can get to replicating this is on a shruken window of a desktop browser, where after clicking the X the mouseover is over the search icon, so it expands. This isn't really anything going wrong though, just unfortunate. And an extreme edge case. All mobile browsers I've tried don't have any show-on-hover behaviour, so can't trigger anything similar.

Regardless, moved the (x) to the top-left corner.

**Comment by jrosindell** [comment]
Thanks I think we can close this
