### ISSUE TITLE
Missing image on EOL

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#173]
On this page

http://beta.onezoom.org/sponsor_leaf?lang=&ott=399295

An example image doesn't load 

![](https://content.eol.org/data/media/65/61/f1/509.59240478.580x360.jpg)

possibly because of an EOL error

**Comment by hyanwong** [comment]
And it's a super cute one! https://commons.wikimedia.org/wiki/File:Dendropsophus_branneri_Santa_Luzia.jpg

**Comment by hyanwong** [comment]
Pointed out to EoL. Nothing we can do on our end, as there's no way of knowing whether it's missing from EoL until the client tries to download it.

**Comment by hyanwong** [comment]
These EoL URLs have all changed now anyway. This one is now at https://eol.org/media/7568093. It can be got using `./OZprivate/ServerScripts/Utilities/EoLQueryPicsNames.py -ott 399295` but will require the rating to be hand hacked before it appears as the default image.
