### ISSUE TITLE
sponsor.html slow to load

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#174]
I'm not sure why, but https://www.onezoom.org/sponsor.html is a touch slow to load - I suspect it is hitting out DB with a difficult query, so could cause blockages.

It might be to do with getting all the languages (https://github.com/OneZoom/OZtree/blob/5e71611ee77c9c90d8231dad87b004198cc999e5/controllers/default.py#L657)

**Comment by jrosindell** [comment]
This might be an easy thing for @lentinj to comment on and possibly close

**Comment by lentinj** [comment]
The code @hyanwong was pointing a finger at was removed with https://github.com/OneZoom/OZtree/commit/ab984d43ef49eda53377402def9016acb39e6bc7, and the page response time seems as sprightly as we're going to get, so closing.
