### ISSUE TITLE
Add new fields to database tables for expired reservations etc

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#177]
We need to add the following columns:

RESERVATIONS TABLE

*   ~~Partner paid field - date paid or null (DONE)~~
*   ~~Gift aid claimed date which is set manually by extracting the ids from the giftaid CSV (DONE)~~
*  ~~New entry in the database for number of days purchased (DONE as sponsorship_duration_days)~~
*   ~~Replacements for live_time (currently used to mean "time we emailed"):~~
     * ~~Emailed_re_sponsorship~~
     * ~~Tweeted_re_sponsorship~~
     * ~~Emailed_re_renewal_initial~~
     * ~~Emailed_re_renewal_final~~
*   ~~New flag for don’t send reminders~~
*  ~~new field in the database for acceptability of sponsorship text: e.g. NULL =  not reviewed. 0 = not great. 1 = happy with name text. 2 = more info OK but not quite standard / too personal. 3 perfectly OK to anyone or other org (set the bar high). NB we will show the 0-3 to some others decide what to do. Now as sponsorship_text_level~~
* sponsorship story text
* sponsorship story quality score
* A 'username' to reservations table that will be used to generate that person's donor page. 
* ~~Note for whether this was gratis or not - this will be in admin comment~~

EXPIRED_RESERVATIONS TABLE
*   Everything that's in the RESERVATIONS table 
*   flag for was_renewed (in expired reservations table only)
*  "wiped" - see below
* OTTid should not be unique in this table - as things can be renewed more than once (this is the case already)

~~PRICES TABLE~~
*   ~~Add prices for infinite renewal~~

**Comment by hyanwong** [comment]
@jrosindell - a slight issue - the price is set on `ordered_leaves` - it seems wasteful and unnecessary to add another column for the infinite price band (and I don't like hacking with ordered_leaves). My suggestion is to add another column to the prices table (which is only 5 rows long). Essentially, the prices table then acts as a map, so we look up the price for a leaf in the `order_leaves` table, find the equivalent infinite price, and use that.

**Comment by hyanwong** [comment]
I also think we should not use the word "infinite", but instead use "in perpetuity", or simply "perpetuity".

**Comment by jrosindell** [comment]
Probably the infinite renewal price should be a set multiple of the 4 year renewal price.  But we won't do this just now

**Comment by jrosindell** [comment]
After discussion today, we realised that we also need a 'wiped' field in the expired reservations table.  This would be used if we really want this past sponsorship to be fully removed and not shown, even in the history.  This might, for example, happen at the special request of the sponsor.

**Comment by jrosindell** [comment]
#365 may be relevant for extra fields needed as part of this job.

I now think that we shouldn't do an infinite sponsorship function as it requires extra effort to get working and leads to a whole range of further governance issues.

**Comment by jrosindell** [comment]
New flag for don’t send reminders is "restrict_all_contact"

**Comment by jrosindell** [comment]
Behaviour of the 'donor_username' field - should be copied to all reservations with the same e-mail but not to any with another e-mail. We need to discuss this later - how it interacts with the renewals and initial donation page, how it interacts with the donor show and the interpretation around setting the name in the first place. it is auto set, or blank and they type it in.  Probably it should their name with a number if necessary to make it unique.

**Comment by hyanwong** [comment]
Looking at the "wiped" field, I wonder if actually we want a whole table: "wiped_reservations", in which we park any reservations we never wish to reveal? Then we don't need any special logic (which we could easily forget) when displaying rows in the expired reservations table.

**Comment by jrosindell** [comment]
@lentinj Please cherry pick Yan's work on this into V3.5 branch when you're ready to include it - thanks.

**Comment by hyanwong** [comment]
> Behaviour of the 'donor_username' field - should be copied to all reservations with the same e-mail but not to any with another e-mail. 

@jrosindell: do you mean `user_donor_name` or `username`? We have both fields in the reservations table. The first need not be unique. The second, I think, should be (and should be what we use in the URL).

**Comment by jrosindell** [comment]
Yan and I discussed and think this is now done
