### ISSUE TITLE
search functionality is slow again

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#178]

**Comment by hyanwong** [comment]
An initial investigation seems to imply that the python search function (specifically the SQL commands in e.g. https://github.com/OneZoom/OZtree/blob/4dd9c6ab0cb4b43d592ed6fe65a83b5ba2d2206a/controllers/API.py#L297 ) are being called twice, even when a single keypress is used.

**Comment by jrosindell** [comment]
This is a problem that has somehow regressed back, I'm sure it's been solved before so it might be worth comparing to V3.3.

In terms of how to fix, I think

- [ ] Increase the amount of time before it starts live searching on type

- [ ] Make it that only one search command is sent at a time

- [ ] If the user continues to type after a search command has been sent but not received back yet, consider increasing the waiting time yet further to prevent a search for every new character typed

- [ ] When results come back from searches check that the string searched still matches the search string in the expected way before displaying the results

**Comment by hyanwong** [comment]
There is a benchmarking test for the API side of the search (I don't think the API is the problem here, though) at https://github.com/OneZoom/OZtree/blob/master/tests/benchmarking/API/test_textsearch.py

The tests at https://github.com/OneZoom/OZtree/tree/master/tests/site_setup will check that indexes are set up correctly, I hope.

You can run these using nose, e.g. `nosetests -vs tests/benchmarking/API/test_textsearch.py`

**Comment by jrosindell** [comment]
Having experimented with this and discussed with Kai - it's been hard to replicate any slow search behaviour.

**Comment by hyanwong** [comment]
Some feedback from Eric, as some searches (e.g. for "rat") are killing the DB:

> mysql> select 
>     ->   id,ott,name,popularity 
>     -> from 
>     ->   ordered_nodes 
>     -> where 
>     ->   match(name) against('+*Rat*' in boolean mode)  
>     -> union 
>     ->   select id,ott,name,popularity 
>     ->   from   ordered_nodes 
>     ->   where  ott 
>     ->   in     (select distinct ott from vernacular_by_ott where match(vernacular) against('+*Rat*' in boolean mode) and lang_primary='en' ) union select id,ott,name,popularity from ordered_nodes where name in (select distinct name from vernacular_by_name where match(vernacular) against('+*Rat*' in boolean mode) and lang_primary='en' );
> +---------+---------+---------------------------------+--------------------+
> | id      | ott     | name                            | popularity         |
> +---------+---------+---------------------------------+--------------------+
> |   26585 |  644564 | Rathayibacter                   |  24460.19942691062 |
> |  463372 |  837477 | Ratibida                        |  45835.06302185226 |
> |  816228 |  349953 | Rathkeidae                      | 50305.254312838195 |
> |  816236 |  349961 | Rathkea                         |  53988.85223533473 |
> |  874792 |  197414 | Rathbunella                     |   65182.5606049855 |
> |  887978 | 1054153 | Ratufa                          |  124895.8904792987 |
> | 1011510 | 1045676 | Ratnadvipia                     |  66972.40625094743 |
> | 1216561 | 6186896 | Rathbunaja                      |  74888.64413931739 |
> | 1219642 | 4666779 | Rathbunamon                     |  75198.71009370219 |
> | 1222648 | 4667969 | Rata                            |  72663.02872653221 |
> | 1262973 | 2945078 | Rataniidae                      |  70584.80658034972 |
> | 1339180 | 3439689 | Ratemiidae                      |   86399.6314984086 |
> | 1440867 | 4209872 | Ratburella                      |  92611.00805213678 |
> | 1562127 | 4548130 | Rattana                         |  87568.45952669658 |
> | 1635522 | 5797672 | Rathymus                        |  97899.46705343267 |
> | 2069970 | 4232427 | Ratarda                         |  87469.86081511484 |
> | 2130933 |  514506 | Rathinda                        |  84569.41887856188 |
> | 2146085 | 3158613 | Ratasa                          |  89173.38810923864 |
> |  889553 |  856142 | Dasymys                         | 110948.88138796063 |
> |  890107 |   81443 | Palaeognathae                   | 115104.90150482566 |
> |  888456 |  839752 | Muroidea                        | 140248.64921940604 |
> |  888822 |  576093 | Sigmodon                        | 109235.90917004846 |
> |  888522 |  741256 | Tachyoryctes                    | 109763.14505536514 |
> |  888201 |  692682 | Bathyergidae                    | 114734.08529144329 |
> |  889153 |  816251 | Spalax                          |  112173.2130039811 |
> |  888845 |  794268 | Neusticomys                     | 114619.61556323532 |
> |  888488 | 1018049 | Brachytarsomys                  |  117926.3498347176 |
> |  888483 |  276747 | Nesomys                         | 116762.22007303179 |
> |  889171 |  766446 | Beamys                          | 117316.88193023462 |
> |  889172 | 1068783 | Cricetomys                      | 116840.99988260046 |
> |  888936 |  310838 | Oligoryzomys                    | 106460.02071508339 |
> |  888838 | 3611169 | Ichthyomys                      | 115053.56674917882 |
> |  888490 |  441610 | Eliurus                         | 113193.96071381251 |
> |  888890 |   38055 | Sigmodontomys                   | 116121.70905624234 |
> |  889334 |  386294 | Parotomys                       |  115484.3318615578 |
> |  889365 | 3610624 | Thamnomys                       | 114467.41935059865 |
> |  889364 |  976847 | Oenomys                         | 115590.33124201655 |
> |  889374 |  170604 | Grammomys                       | 107327.85624709546 |
> |  889441 |  366060 | Berylmys                        | 113520.46368295744 |
> |  889475 |  742013 | Bunomys                         | 111802.99967307698 |
> |  889508 |  784791 | Nesokia                         | 115677.40989977987 |
> |  889445 |  686829 | Arvicanthis                     | 110719.01899982183 |
> |  888963 |  548603 | Oecomys                         | 105402.16568639631 |
> |  889402 |  989549 | Hydromys                        | 111734.79917305673 |
> |  889452 |  458646 | Tokudaia                        | 114687.42342888124 |
> |  889438 |  106788 | Bandicota                       | 114169.28726289727 |
> |  889534 |  474761 | Maxomys                         | 103706.25888421238 |
> |  889627 |  386289 | Pelomys                         | 111657.08862226772 |
> |  889679 |  474767 | Niviventer                      |  103955.3316602023 |
> |  889738 |  692528 | Macruromys                      |  114484.6030301542 |
> |  888898 |  526781 | Scapteromys                     | 114544.77842313869 |
> |  889696 |  159167 | Lophuromys                      | 104599.95319511558 |
> |  889809 |  156331 | Zyzomys                         | 111920.15454890451 |
> |  889740 |  692536 | Mallomys                        | 112185.94559638966 |
> |  888901 |  540520 | Bibimys                         | 113046.87386607417 |
> |  888900 |  526767 | Kunsia                          | 114098.67577732822 |
> |  888278 |  360965 | Isothrix                        |  112917.6060472955 |
> |  889528 |  402367 | Hapalomys                       | 113493.56272099206 |
> |  909794 |  913536 | Spilotes                        |   75563.6922575444 |
> |  888148 |  360876 | Thryonomyidae                   | 119268.64136356117 |
> |  888520 |  964578 | Rhizomys                        | 117769.38001369651 |
> |  888694 |  157070 | Neotoma                         | 107853.49764427092 |
> |  888206 |  118546 | Cryptomys                       |  112102.3019029351 |
> |  888205 |  118536 | Bathyergus                      | 117469.89101552241 |
> |  888814 |   15635 | Tylomys                         | 113615.16444997369 |
> |  888241 |  885698 | Dactylomys                      | 114016.52369498591 |
> |  888932 |   91084 | Reithrodon                      | 116226.58509130611 |
> |  888240 | 3611040 | Olallamys                       | 114840.83579321262 |
> |  888282 | 3610420 | Diplomys                        |  113010.9714447019 |
> |  889281 |  185330 | Leopoldamys                     | 112159.04418384148 |
> |  889733 |  156339 | Hyomys                          | 115055.29126823282 |
> |  888867 |  913871 | Nectomys                        | 112793.65480374041 |
> |  908093 |   27078 | Crotalus                        |   83385.4088685022 |
> |  885051 |  317162 | Bettongia                       | 106499.83139713253 |
> |  908091 |  755881 | Sistrurus                       |  84284.19916746207 |
> |  909548 |    6524 | Ptyas                           |  75264.70143506573 |
> |  909590 |  788008 | Gonyosoma                       |  75033.07771424315 |
> |  909517 | 1032601 | Bogertophis                     |  74847.38086530069 |
> | 1339186 | 1010451 | Polyplacidae                    | 61197.700413155275 |
> | 1981084 |  816779 | Syrphidae                       |  57198.10133814149 |
> |  840449 |  550659 | Chimaeridae                     |    59189.162993219 |
> |  840442 |  194656 | Rhinochimaeridae                |  68288.63612084158 |
> |  252640 |  762993 | Goodyera                        | 37918.745943251146 |
> |  371731 |  612457 | Crotalaria                      | 32001.826931164112 |
> |  220532 |  413239 | Briza                           | 45817.931295404946 |
> |  442234 |  475557 | Prenanthes                      |   43435.7695821966 |
> |  531977 |   83781 | Rhinanthus                      | 36246.440243922014 |
> |  888305 |  342249 | Dipodomys                       | 108997.76793727676 |
> |  888070 |    NULL | HystricomorphsMinusEarlyBranch_ | 119780.67271916592 |
> |  888164 |    NULL | Clade3167_                      | 115992.04974764695 |
> |  888229 |    NULL | Clade6618_                      |  91885.97950732739 |
> |  888238 |    NULL | Clade10951_                     | 112481.17745921477 |
> |  888301 |    NULL | Geomyoidea                      |  94260.68035027932 |
> |  888519 |    NULL | Clade5620_                      |  117328.2306371126 |
> |  888813 |    NULL | Clade4691_                      | 113248.92108850354 |
> |  888956 |    NULL | Clade12018_                     | 114362.54397075724 |
> |  888981 |    NULL | Clade14059_                     | 102342.13026811919 |
> |  889143 |    NULL | Clade3867_                      | 106565.12967880984 |
> |  889168 |    NULL | Clade6559_                      | 114110.90670423211 |
> |  889170 |    NULL | Clade7560_                      | 115432.71758006015 |
> |  889175 |    NULL | Clade5595_                      |  88665.75165878024 |
> |  889176 |    NULL | Clade6556_                      |  97700.44968850262 |
> |  889200 |    NULL | Clade11998_                     | 104573.23276326203 |
> |  889294 |    NULL | Clade10866_                     | 112950.43537187373 |
> |  889299 |    NULL | Clade10865_                     |  116081.6713097025 |
> |  889335 |    NULL | Clade11967_                     | 102365.67968725177 |
> |  889581 |    NULL | Clade17677_                     |  109696.2687646696 |
> |  889635 |    NULL | Clade14010_                     |  109937.6066471362 |
> |  889732 |    NULL | Clade11996_                     |  114562.8854353249 |
> +---------+---------+---------------------------------+--------------------+
> 109 rows in set (1 min 24.59 sec)
> 
> The first element of the search is quick:
> 
> mysql> select    id,ott,name,popularity  from    ordered_nodes  where    match(name) against('+*Rat*' in boolean mode);
> +---------+---------+---------------+--------------------+
> | id      | ott     | name          | popularity         |
> +---------+---------+---------------+--------------------+
> |   26585 |  644564 | Rathayibacter |  24460.19942691062 |
> |  463372 |  837477 | Ratibida      |  45835.06302185226 |
> |  816228 |  349953 | Rathkeidae    | 50305.254312838195 |
> |  816236 |  349961 | Rathkea       |  53988.85223533473 |
> |  874792 |  197414 | Rathbunella   |   65182.5606049855 |
> |  887978 | 1054153 | Ratufa        |  124895.8904792987 |
> | 1011510 | 1045676 | Ratnadvipia   |  66972.40625094743 |
> | 1216561 | 6186896 | Rathbunaja    |  74888.64413931739 |
> | 1219642 | 4666779 | Rathbunamon   |  75198.71009370219 |
> | 1222648 | 4667969 | Rata          |  72663.02872653221 |
> | 1262973 | 2945078 | Rataniidae    |  70584.80658034972 |
> | 1339180 | 3439689 | Ratemiidae    |   86399.6314984086 |
> | 1440867 | 4209872 | Ratburella    |  92611.00805213678 |
> | 1562127 | 4548130 | Rattana       |  87568.45952669658 |
> | 1635522 | 5797672 | Rathymus      |  97899.46705343267 |
> | 2069970 | 4232427 | Ratarda       |  87469.86081511484 |
> | 2130933 |  514506 | Rathinda      |  84569.41887856188 |
> | 2146085 | 3158613 | Ratasa        |  89173.38810923864 |
> +---------+---------+---------------+--------------------+
> 18 rows in set (0.00 sec)
> 
> So it must be all the joins and subqueries which are slowing it down.  This subquery is fast:
> 
> mysql> select distinct ott from vernacular_by_ott where match(vernacular) against('+*Rat*' in boolean mode) and lang_primary='en'
> ...
> 1112 rows in set (0.03 sec)
> 
> The larger union it is a member of is also quite fast:
> 
> mysql> select id,ott,name,popularity 
>     ->   from   ordered_nodes 
>     ->   where  ott 
>     ->   in     (select distinct ott from vernacular_by_ott where match(vernacular) against('+*Rat*' in boolean mode) and lang_primary='en' );
> +---------+---------+------------------+--------------------+
> | id      | ott     | name             | popularity         |
> +---------+---------+------------------+--------------------+
> |  889553 |  856142 | Dasymys          | 110948.88138796063 |
> |  890107 |   81443 | Palaeognathae    | 115104.90150482566 |
> |  888456 |  839752 | Muroidea         | 140248.64921940604 |
> |  888822 |  576093 | Sigmodon         | 109235.90917004846 |
> |  888522 |  741256 | Tachyoryctes     | 109763.14505536514 |
> |  888201 |  692682 | Bathyergidae     | 114734.08529144329 |
> |  889153 |  816251 | Spalax           |  112173.2130039811 |
> |  888845 |  794268 | Neusticomys      | 114619.61556323532 |
> |  888488 | 1018049 | Brachytarsomys   |  117926.3498347176 |
> |  888483 |  276747 | Nesomys          | 116762.22007303179 |
> |  889171 |  766446 | Beamys           | 117316.88193023462 |
> |  889172 | 1068783 | Cricetomys       | 116840.99988260046 |
> |  888936 |  310838 | Oligoryzomys     | 106460.02071508339 |
> |  888838 | 3611169 | Ichthyomys       | 115053.56674917882 |
> |  888490 |  441610 | Eliurus          | 113193.96071381251 |
> |  888890 |   38055 | Sigmodontomys    | 116121.70905624234 |
> |  889334 |  386294 | Parotomys        |  115484.3318615578 |
> |  889365 | 3610624 | Thamnomys        | 114467.41935059865 |
> |  889364 |  976847 | Oenomys          | 115590.33124201655 |
> |  889374 |  170604 | Grammomys        | 107327.85624709546 |
> |  889441 |  366060 | Berylmys         | 113520.46368295744 |
> |  889475 |  742013 | Bunomys          | 111802.99967307698 |
> |  889508 |  784791 | Nesokia          | 115677.40989977987 |
> |  889445 |  686829 | Arvicanthis      | 110719.01899982183 |
> |  888963 |  548603 | Oecomys          | 105402.16568639631 |
> |  889402 |  989549 | Hydromys         | 111734.79917305673 |
> |  889452 |  458646 | Tokudaia         | 114687.42342888124 |
> |  889438 |  106788 | Bandicota        | 114169.28726289727 |
> |  889534 |  474761 | Maxomys          | 103706.25888421238 |
> |  889627 |  386289 | Pelomys          | 111657.08862226772 |
> |  889679 |  474767 | Niviventer       |  103955.3316602023 |
> |  889738 |  692528 | Macruromys       |  114484.6030301542 |
> |  888898 |  526781 | Scapteromys      | 114544.77842313869 |
> |  889696 |  159167 | Lophuromys       | 104599.95319511558 |
> |  889809 |  156331 | Zyzomys          | 111920.15454890451 |
> |  889740 |  692536 | Mallomys         | 112185.94559638966 |
> |  888901 |  540520 | Bibimys          | 113046.87386607417 |
> |  888900 |  526767 | Kunsia           | 114098.67577732822 |
> |  888278 |  360965 | Isothrix         |  112917.6060472955 |
> |  889528 |  402367 | Hapalomys        | 113493.56272099206 |
> |  909794 |  913536 | Spilotes         |   75563.6922575444 |
> |  888148 |  360876 | Thryonomyidae    | 119268.64136356117 |
> |  888520 |  964578 | Rhizomys         | 117769.38001369651 |
> |  888694 |  157070 | Neotoma          | 107853.49764427092 |
> |  888206 |  118546 | Cryptomys        |  112102.3019029351 |
> |  888205 |  118536 | Bathyergus       | 117469.89101552241 |
> |  888814 |   15635 | Tylomys          | 113615.16444997369 |
> |  888241 |  885698 | Dactylomys       | 114016.52369498591 |
> |  888932 |   91084 | Reithrodon       | 116226.58509130611 |
> |  888240 | 3611040 | Olallamys        | 114840.83579321262 |
> |  888282 | 3610420 | Diplomys         |  113010.9714447019 |
> |  889281 |  185330 | Leopoldamys      | 112159.04418384148 |
> |  889733 |  156339 | Hyomys           | 115055.29126823282 |
> |  888867 |  913871 | Nectomys         | 112793.65480374041 |
> |  908093 |   27078 | Crotalus         |   83385.4088685022 |
> |  885051 |  317162 | Bettongia        | 106499.83139713253 |
> |  908091 |  755881 | Sistrurus        |  84284.19916746207 |
> |  909548 |    6524 | Ptyas            |  75264.70143506573 |
> |  909590 |  788008 | Gonyosoma        |  75033.07771424315 |
> |  909517 | 1032601 | Bogertophis      |  74847.38086530069 |
> | 1339186 | 1010451 | Polyplacidae     | 61197.700413155275 |
> | 1981084 |  816779 | Syrphidae        |  57198.10133814149 |
> |  840449 |  550659 | Chimaeridae      |    59189.162993219 |
> |  840442 |  194656 | Rhinochimaeridae |  68288.63612084158 |
> |  252640 |  762993 | Goodyera         | 37918.745943251146 |
> |  371731 |  612457 | Crotalaria       | 32001.826931164112 |
> |  220532 |  413239 | Briza            | 45817.931295404946 |
> |  442234 |  475557 | Prenanthes       |   43435.7695821966 |
> |  531977 |   83781 | Rhinanthus       | 36246.440243922014 |
> |  888305 |  342249 | Dipodomys        | 108997.76793727676 |
> +---------+---------+------------------+--------------------+
> 70 rows in set (0.02 sec)
> 
> Indeed doing the query which forms the last union
> 
> mysql> select id,ott,name,popularity from ordered_nodes where name in (select distinct name from vernacular_by_name where match(vernacular) against('+*Rat*' in boolean mode) and lang_primary='en' );
> +--------+------+---------------------------------+--------------------+
> | id     | ott  | name                            | popularity         |
> +--------+------+---------------------------------+--------------------+
> | 888070 | NULL | HystricomorphsMinusEarlyBranch_ | 119780.67271916592 |
> | 888164 | NULL | Clade3167_                      | 115992.04974764695 |
> | 888229 | NULL | Clade6618_                      |  91885.97950732739 |
> | 888238 | NULL | Clade10951_                     | 112481.17745921477 |
> | 888301 | NULL | Geomyoidea                      |  94260.68035027932 |
> | 888519 | NULL | Clade5620_                      |  117328.2306371126 |
> | 888813 | NULL | Clade4691_                      | 113248.92108850354 |
> | 888956 | NULL | Clade12018_                     | 114362.54397075724 |
> | 888981 | NULL | Clade14059_                     | 102342.13026811919 |
> | 889143 | NULL | Clade3867_                      | 106565.12967880984 |
> | 889168 | NULL | Clade6559_                      | 114110.90670423211 |
> | 889170 | NULL | Clade7560_                      | 115432.71758006015 |
> | 889175 | NULL | Clade5595_                      |  88665.75165878024 |
> | 889176 | NULL | Clade6556_                      |  97700.44968850262 |
> | 889200 | NULL | Clade11998_                     | 104573.23276326203 |
> | 889294 | NULL | Clade10866_                     | 112950.43537187373 |
> | 889299 | NULL | Clade10865_                     |  116081.6713097025 |
> | 889335 | NULL | Clade11967_                     | 102365.67968725177 |
> | 889581 | NULL | Clade17677_                     |  109696.2687646696 |
> | 889635 | NULL | Clade14010_                     |  109937.6066471362 |
> | 889732 | NULL | Clade11996_                     |  114562.8854353249 |
> +--------+------+---------------------------------+--------------------+
> 21 rows in set (1 min 24.20 sec)
> 
> Is slow.   The subquery used in the IN statement runs thus:
> 
> mysql> select distinct name from vernacular_by_name where match(vernacular) against('+*Rat*' in boolean mode) and lang_primary='en' 
>     -> ;
> +---------------------------------+
> | name                            |
> +---------------------------------+
> | Clade1220_                      |
> | Clade6618_                      |
> | Clade10951_                     |
> | HystricomorphsMinusEarlyBranch_ |
> | Clade3167_                      |
> | Clade3867_                      |
> | Clade4691_                      |
> | Clade5595_                      |
> | Clade5620_                      |
> | Clade6556_                      |
> | Clade6559_                      |
> | Clade7560_                      |
> | Clade10865_                     |
> | Clade10866_                     |
> | Clade11967_                     |
> | Clade11996_                     |
> | Clade11998_                     |
> | Clade12018_                     |
> | Geomyoidea                      |
> | Clade14010_                     |
> | Clade14059_                     |
> | Clade17677_                     |
> +---------------------------------+
> 22 rows in set (0.00 sec)
> 
> Doing the slow query with a manually expanded list is fast however:
> 
> mysql> select id,ott,name,popularity from ordered_nodes where name in ('Clade1220_','Clade6618_','Clade10951_','HystricomorphsMinusEarlyBranch_','Clade3167_','Clade3867_','Clade4691_','Clade5595_','Clade5620_','Clade6556_','Clade6559_','Clade7560_','Clade10865_','Clade10866_','Clade11967_','Clade11996_','Clade11998_','Clade12018_','Geomyoidea','Clade14010_','Clade14059_','Clade17677_');
> +--------+------+---------------------------------+--------------------+
> | id     | ott  | name                            | popularity         |
> +--------+------+---------------------------------+--------------------+
> | 889299 | NULL | Clade10865_                     |  116081.6713097025 |
> | 889294 | NULL | Clade10866_                     | 112950.43537187373 |
> | 888238 | NULL | Clade10951_                     | 112481.17745921477 |
> | 889335 | NULL | Clade11967_                     | 102365.67968725177 |
> | 889732 | NULL | Clade11996_                     |  114562.8854353249 |
> | 889200 | NULL | Clade11998_                     | 104573.23276326203 |
> | 888956 | NULL | Clade12018_                     | 114362.54397075724 |
> | 888071 | NULL | Clade1220_                      | 117735.33799541395 |
> | 889635 | NULL | Clade14010_                     |  109937.6066471362 |
> | 888981 | NULL | Clade14059_                     | 102342.13026811919 |
> | 889581 | NULL | Clade17677_                     |  109696.2687646696 |
> | 888164 | NULL | Clade3167_                      | 115992.04974764695 |
> | 889143 | NULL | Clade3867_                      | 106565.12967880984 |
> | 888813 | NULL | Clade4691_                      | 113248.92108850354 |
> | 889175 | NULL | Clade5595_                      |  88665.75165878024 |
> | 888519 | NULL | Clade5620_                      |  117328.2306371126 |
> | 889176 | NULL | Clade6556_                      |  97700.44968850262 |
> | 889168 | NULL | Clade6559_                      | 114110.90670423211 |
> | 888229 | NULL | Clade6618_                      |  91885.97950732739 |
> | 889170 | NULL | Clade7560_                      | 115432.71758006015 |
> | 888301 | NULL | Geomyoidea                      |  94260.68035027932 |
> | 888070 | NULL | HystricomorphsMinusEarlyBranch_ | 119780.67271916592 |
> +--------+------+---------------------------------+--------------------+
> 22 rows in set (0.00 sec)
> 
> So I don’t know why that subquery is really slowing things down.  It’s not obvious to me, I wonder if Jamie’s brain is less pickled after Christmas than mine?
> 
> If I run the full query with that subquery expanded it is fast:
> 
> mysql> select 
>     ->   id,ott,name,popularity 
>     -> from 
>     ->   ordered_nodes 
>     -> where 
>     ->   match(name) against('+*Rat*' in boolean mode)  
>     -> union 
>     ->   select id,ott,name,popularity 
>     ->   from   ordered_nodes 
>     ->   where  ott 
>     ->   in     (select distinct ott from vernacular_by_ott where match(vernacular) against('+*Rat*' in boolean mode) and lang_primary='en' ) union select id,ott,name,popularity from ordered_nodes where name in ('Clade1220_','Clade6618_','Clade10951_','HystricomorphsMinusEarlyBranch_','Clade3167_','Clade3867_','Clade4691_','Clade5595_','Clade5620_','Clade6556_','Clade6559_','Clade7560_','Clade10865_','Clade10866_','Clade11967_','Clade11996_','Clade11998_','Clade12018_','Geomyoidea','Clade14010_','Clade14059_','Clade17677_')
>     -> ;
> +---------+---------+---------------------------------+--------------------+
> | id      | ott     | name                            | popularity         |
> +---------+---------+---------------------------------+--------------------+
> |   26585 |  644564 | Rathayibacter                   |  24460.19942691062 |
> |  463372 |  837477 | Ratibida                        |  45835.06302185226 |
> |  816228 |  349953 | Rathkeidae                      | 50305.254312838195 |
> |  816236 |  349961 | Rathkea                         |  53988.85223533473 |
> |  874792 |  197414 | Rathbunella                     |   65182.5606049855 |
> |  887978 | 1054153 | Ratufa                          |  124895.8904792987 |
> | 1011510 | 1045676 | Ratnadvipia                     |  66972.40625094743 |
> | 1216561 | 6186896 | Rathbunaja                      |  74888.64413931739 |
> | 1219642 | 4666779 | Rathbunamon                     |  75198.71009370219 |
> | 1222648 | 4667969 | Rata                            |  72663.02872653221 |
> | 1262973 | 2945078 | Rataniidae                      |  70584.80658034972 |
> | 1339180 | 3439689 | Ratemiidae                      |   86399.6314984086 |
> | 1440867 | 4209872 | Ratburella                      |  92611.00805213678 |
> | 1562127 | 4548130 | Rattana                         |  87568.45952669658 |
> | 1635522 | 5797672 | Rathymus                        |  97899.46705343267 |
> | 2069970 | 4232427 | Ratarda                         |  87469.86081511484 |
> | 2130933 |  514506 | Rathinda                        |  84569.41887856188 |
> | 2146085 | 3158613 | Ratasa                          |  89173.38810923864 |
> |  889553 |  856142 | Dasymys                         | 110948.88138796063 |
> |  890107 |   81443 | Palaeognathae                   | 115104.90150482566 |
> |  888456 |  839752 | Muroidea                        | 140248.64921940604 |
> |  888822 |  576093 | Sigmodon                        | 109235.90917004846 |
> |  888522 |  741256 | Tachyoryctes                    | 109763.14505536514 |
> |  888201 |  692682 | Bathyergidae                    | 114734.08529144329 |
> |  889153 |  816251 | Spalax                          |  112173.2130039811 |
> |  888845 |  794268 | Neusticomys                     | 114619.61556323532 |
> |  888488 | 1018049 | Brachytarsomys                  |  117926.3498347176 |
> |  888483 |  276747 | Nesomys                         | 116762.22007303179 |
> |  889171 |  766446 | Beamys                          | 117316.88193023462 |
> |  889172 | 1068783 | Cricetomys                      | 116840.99988260046 |
> |  888936 |  310838 | Oligoryzomys                    | 106460.02071508339 |
> |  888838 | 3611169 | Ichthyomys                      | 115053.56674917882 |
> |  888490 |  441610 | Eliurus                         | 113193.96071381251 |
> |  888890 |   38055 | Sigmodontomys                   | 116121.70905624234 |
> |  889334 |  386294 | Parotomys                       |  115484.3318615578 |
> |  889365 | 3610624 | Thamnomys                       | 114467.41935059865 |
> |  889364 |  976847 | Oenomys                         | 115590.33124201655 |
> |  889374 |  170604 | Grammomys                       | 107327.85624709546 |
> |  889441 |  366060 | Berylmys                        | 113520.46368295744 |
> |  889475 |  742013 | Bunomys                         | 111802.99967307698 |
> |  889508 |  784791 | Nesokia                         | 115677.40989977987 |
> |  889445 |  686829 | Arvicanthis                     | 110719.01899982183 |
> |  888963 |  548603 | Oecomys                         | 105402.16568639631 |
> |  889402 |  989549 | Hydromys                        | 111734.79917305673 |
> |  889452 |  458646 | Tokudaia                        | 114687.42342888124 |
> |  889438 |  106788 | Bandicota                       | 114169.28726289727 |
> |  889534 |  474761 | Maxomys                         | 103706.25888421238 |
> |  889627 |  386289 | Pelomys                         | 111657.08862226772 |
> |  889679 |  474767 | Niviventer                      |  103955.3316602023 |
> |  889738 |  692528 | Macruromys                      |  114484.6030301542 |
> |  888898 |  526781 | Scapteromys                     | 114544.77842313869 |
> |  889696 |  159167 | Lophuromys                      | 104599.95319511558 |
> |  889809 |  156331 | Zyzomys                         | 111920.15454890451 |
> |  889740 |  692536 | Mallomys                        | 112185.94559638966 |
> |  888901 |  540520 | Bibimys                         | 113046.87386607417 |
> |  888900 |  526767 | Kunsia                          | 114098.67577732822 |
> |  888278 |  360965 | Isothrix                        |  112917.6060472955 |
> |  889528 |  402367 | Hapalomys                       | 113493.56272099206 |
> |  909794 |  913536 | Spilotes                        |   75563.6922575444 |
> |  888148 |  360876 | Thryonomyidae                   | 119268.64136356117 |
> |  888520 |  964578 | Rhizomys                        | 117769.38001369651 |
> |  888694 |  157070 | Neotoma                         | 107853.49764427092 |
> |  888206 |  118546 | Cryptomys                       |  112102.3019029351 |
> |  888205 |  118536 | Bathyergus                      | 117469.89101552241 |
> |  888814 |   15635 | Tylomys                         | 113615.16444997369 |
> |  888241 |  885698 | Dactylomys                      | 114016.52369498591 |
> |  888932 |   91084 | Reithrodon                      | 116226.58509130611 |
> |  888240 | 3611040 | Olallamys                       | 114840.83579321262 |
> |  888282 | 3610420 | Diplomys                        |  113010.9714447019 |
> |  889281 |  185330 | Leopoldamys                     | 112159.04418384148 |
> |  889733 |  156339 | Hyomys                          | 115055.29126823282 |
> |  888867 |  913871 | Nectomys                        | 112793.65480374041 |
> |  908093 |   27078 | Crotalus                        |   83385.4088685022 |
> |  885051 |  317162 | Bettongia                       | 106499.83139713253 |
> |  908091 |  755881 | Sistrurus                       |  84284.19916746207 |
> |  909548 |    6524 | Ptyas                           |  75264.70143506573 |
> |  909590 |  788008 | Gonyosoma                       |  75033.07771424315 |
> |  909517 | 1032601 | Bogertophis                     |  74847.38086530069 |
> | 1339186 | 1010451 | Polyplacidae                    | 61197.700413155275 |
> | 1981084 |  816779 | Syrphidae                       |  57198.10133814149 |
> |  840449 |  550659 | Chimaeridae                     |    59189.162993219 |
> |  840442 |  194656 | Rhinochimaeridae                |  68288.63612084158 |
> |  252640 |  762993 | Goodyera                        | 37918.745943251146 |
> |  371731 |  612457 | Crotalaria                      | 32001.826931164112 |
> |  220532 |  413239 | Briza                           | 45817.931295404946 |
> |  442234 |  475557 | Prenanthes                      |   43435.7695821966 |
> |  531977 |   83781 | Rhinanthus                      | 36246.440243922014 |
> |  888305 |  342249 | Dipodomys                       | 108997.76793727676 |
> |  889299 |    NULL | Clade10865_                     |  116081.6713097025 |
> |  889294 |    NULL | Clade10866_                     | 112950.43537187373 |
> |  888238 |    NULL | Clade10951_                     | 112481.17745921477 |
> |  889335 |    NULL | Clade11967_                     | 102365.67968725177 |
> |  889732 |    NULL | Clade11996_                     |  114562.8854353249 |
> |  889200 |    NULL | Clade11998_                     | 104573.23276326203 |
> |  888956 |    NULL | Clade12018_                     | 114362.54397075724 |
> |  888071 |    NULL | Clade1220_                      | 117735.33799541395 |
> |  889635 |    NULL | Clade14010_                     |  109937.6066471362 |
> |  888981 |    NULL | Clade14059_                     | 102342.13026811919 |
> |  889581 |    NULL | Clade17677_                     |  109696.2687646696 |
> |  888164 |    NULL | Clade3167_                      | 115992.04974764695 |
> |  889143 |    NULL | Clade3867_                      | 106565.12967880984 |
> |  888813 |    NULL | Clade4691_                      | 113248.92108850354 |
> |  889175 |    NULL | Clade5595_                      |  88665.75165878024 |
> |  888519 |    NULL | Clade5620_                      |  117328.2306371126 |
> |  889176 |    NULL | Clade6556_                      |  97700.44968850262 |
> |  889168 |    NULL | Clade6559_                      | 114110.90670423211 |
> |  888229 |    NULL | Clade6618_                      |  91885.97950732739 |
> |  889170 |    NULL | Clade7560_                      | 115432.71758006015 |
> |  888301 |    NULL | Geomyoidea                      |  94260.68035027932 |
> |  888070 |    NULL | HystricomorphsMinusEarlyBranch_ | 119780.67271916592 |
> +---------+---------+---------------------------------+--------------------+
> 110 rows in set (0.02 sec)
> 
> So the dumb optimisation would be to make two queries, but I don’t quite get why the subquery is slow when run as part of the larger query when it isn’t slow in itself.  The other thing that occurs to me is that the queries that were stacked up were mostly the same suggesting we could have some application level caching in there to help – if these queries are essentially static.  Obviously database level caching would also be good, but I suspect to optimise it we need to move the onezoom stuff to it’s own server.
>

**Comment by hyanwong** [comment]
The reason seems to be that we are joining on names where the name column is encoded as `utf8` in one table (e.g. ordered_leaves) and `utf8mb4` on another (vernacular_by_ott). Although we need to allow full mb4 characters (e.g. some Japanese chararacter & emojis) in the vernacular name, I can't see when we would ever want them in a *scientific name*, so we should simply use the default encoding for the `name` fields, I think.

I'm sure I came across this issue before, and even coded up a test case for it, at https://github.com/OneZoom/OZtree/blob/41ccd998542970b234fa932ef75301a72fb49d50/tests/site_setup/test_database_settings.py#L74, where I said

>  Check the 'name' columns in e.g. vernacular_by_name & ordered_leaves have identical charsets
>  Since these are used as unique matching keys, having different charsets can drastically slow down search,
>   which has caused problems in the past

But since we don't run these tests automatically, we didn't spot that the DB had changed somehow. That shows we should really implement some automatic testing framework, I think.

**Comment by hyanwong** [comment]
I have added instructions for testing after updating the tree: 6b4e75ccda238c00bc47578486f8c3d84a7fac7c, so we should be checking (by hand, though) every time we update.
