### ISSUE TITLE
UI changes across site

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#187]
These are UI changes that should be implemented across the entire site...

1.) Make there be an option for whether or not to zoom to search results.  This option will apply to both basic and advanced search.  It will be parsed through the URL and can be adjusted in settings.  The default will be to zoom on all pages except life_expert.
2.) Get rid of previous ancestor button and make the (-) button perform the same function as previous ancestor.  leave the (+) button as is.  In cases where + and - are not shown but previous ancestor is (e.g. mobile) revert to showing both (+) and (-) getting rid of previous ancestor.

**Comment by jrosindell** [comment]
default fly / jump status across site should be as follows....

life_MD = fly (via launch page)
life = fly
life_expert = jump
linnean = fly

**Comment by kz12** [comment]
Both +, - and previous ancestor buttons are not shown in mobile now. Do you still want to add + and - button for mobile?

**Comment by jrosindell** [comment]
I experimented here and felt that it's best to leave the - off from the mobile as well because although it's useful it does add clutter and feel confusing if it's present without a matching + button
