### ISSUE TITLE
UI changes for museum display

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#188]
These are UI changes for the museum display only.

1.) The buttons on the bottom left have two modes, expanded and collapsed.  
a) collapsed mode is rather like it is now but with a 'help' button that moves to expanded mode.
b) expanded mode is the default state and it resets to this when the display goes onto screensaver mode.  Expanded mode puts full text explanations next to all the buttons and adds a box of interpretation next to that explaining what the tree of life is and how to zoom.  Expanded mode also has a button to hide the help information again.

Full text is as follows.... 'current location', 'zoom in', 'zoom out', 'reset tree view', 'about this display', 'how to use'

both 'how to use' and 'help' buttons should always be present with full text at the bottom of the tray of controls.

2.) the reset tree view function should reset to a predefined home OTTid that is selected through the museum display launch / configuration page

3.) there should be no settings at all on museum display - they are all settable instead by the launch page and preserved in the URL

4.) add key bits of interpretation at the top of the 'info' page which remains to help users alongside other features.

**Comment by jrosindell** [comment]
Of the above 2 and 3 are done so we're left with 1 and 4.  I'll do 1 and after discussion Kai will do 4

**Comment by hyanwong** [comment]
The labels need switching left-to-right with the icons

**Comment by hyanwong** [comment]
Also, might we want to integrate these with the UIkit tooltip information (probably not, though)

**Comment by jrosindell** [comment]
internationalisation on the text
