### ISSUE TITLE
Screen saver and timeout after non user for museum display page

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#19]

**Comment by hyanwong** [comment]
There is something similar in the original OneZoom Museum display software, which could be looked at to get some idea of what we could do, but the actual functionality would need to be re-coded somehow. 

We should decide whether this is done by using UI code to instruct the OneZoom canvas using the  API, or whether it should be functionality built-in to the OneZoom internal javascript. I suspect the latter is more sensible, although the timeout could be decided by the UI, which would call an OZ API function to trigger the screensaver.

**Comment by jrosindell** [comment]
I agree that the latter is more sensible - i.e. a screensaver is built into the code JS of OneZoom which takes the form of some flights and stills from around the tree with a few bits of text popping up indicating what it's all about.  Also the screen saver should have a count down to when it gets kicked off e.g. 'this display will reset in 30,29,28 seconds' underneath a couple of very simple options like 'Don't reset, I was looking at that' and 'Start from the beginning'

**Comment by lentinj** [comment]
So the main thing here is the internet banking style "If you don't do anything in 30s" we're going to log you out (and actually doing so). The screensaver part would be whatevever day-dream mode we do as part of the tutorial before the start (#55).

I think it's more part of the UI code, which is more responsible for the overall page. The alert would need to be visible in the UI, and it just tells the tree to reset / reload the page on reset.

**Comment by jrosindell** [comment]
•	movement when not in use.
•	Hard coded JSON for the screensaver positions will do 
•	List of popular places is hard coded and this would be done in the same way.
•	Passes list of nodes and leaves a the positions that could be changed and customised later but not as part of the basic essential package.
•	Zooms between the positions when idle
•	'Get started' button or similar over the top that triggers the tutorial

**Comment by jrosindell** [comment]
This has basically been implemented now.

Outstanding tasks are....

- [ ] set the JSON for the screensaver location content

- [ ] hook the URL parsed screensaver timeout to the screensaver trigger so that there is no screensaver on any of the OneZoom pages except life_MD and in that case so that the launch page does correctly set the screensaver wait time.

- [ ] arrange the CSS of the screensaver elements.

**Comment by hyanwong** [comment]
> * arrange the CSS of the screensaver elements.

I don't think we are showing any screensaver elements, are we? In which case we can tick this option as done.

**Comment by hyanwong** [comment]
I think this can be closed @jrosindell ?
