### ISSUE TITLE
signpost clicking performance

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#193]
I've noticed that on the production as well as the other more recent development branches performance when clicking on a signpost to zoom in is very poor compared to performance of a flight animation.

**Comment by jrosindell** [comment]
I think this is because the signpost clicks probably use an old version of the flight animation that has not been optimised.  This might be a very easy fix.

**Comment by lentinj** [comment]
I've a feeling this is ~intentional. They're tap2zoom actions, so the change would be:-

```
diff --git a/OZprivate/rawJS/OZTreeModule/src/button_manager.js b/OZprivate/rawJS/OZTreeModule/src/button_manager.js
index a594b06..add0d12 100755
--- a/OZprivate/rawJS/OZTreeModule/src/button_manager.js
+++ b/OZprivate/rawJS/OZTreeModule/src/button_manager.js
@@ -21,7 +21,8 @@ export function click_on_button_cb(controller) {
   } else if (global_button_action.action =="fly_node") {
     controller.fly_straight_to(global_button_action.data, true);
   } else if (global_button_action.action =="tap2zoom") {
-    controller.fly_straight_to(global_button_action.data);
+    controller.fly_on_tree_to(null, global_button_action.data);
   } else if (global_button_action.action =="link") {
     if (typeof config.ui.openCopyright !== 'function') {
       alert("Developer error: you need to define a UI function named openCopyright");
```

...however, the advantage of ``fly_straight_to()``, from memory at least, is that it doesn't wait for detail to be loaded before doing it's thing. Which whilst as you say can be jerky, also means you don't click a button and nothing happens.

**Comment by lentinj** [comment]
...no, that's all nonsense. ``fly_straight_to`` also develops it's destination before flying. It's a simplified version of basically the same codepath anyway, so there's no advantage to changing.

**Comment by jrosindell** [comment]
I don't see the behaviour any more and think it might have been an overloaded device or something like that.  Closing.
