### ISSUE TITLE
On screen keyboard for museum display 

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#20]
not the system keyboard

**Comment by hyanwong** [comment]
e.g.  https://mottie.github.io/Keyboard/ or https://github.com/chriscook/on-screen-keyboard

My preference is for the first, which is simpler.

**Comment by hyanwong** [comment]
Only needed for the search boxes (plain and for common ancestor).

**Comment by jrosindell** [comment]
I think this is not needed as several institutions have deployed displays without this feature.  They are obviously using some in-built system level on screen keyboard that can be configured not to let users into the system.  I think we can therefore close this.
