### ISSUE TITLE
Move the screensaver timing code out of the Tour class

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#200]
After chatting with @jrosindell , we think that although the tutorial should be simply a `Tour` object, the *screensaver* should not be: in fact, a tour should not have any setting that allows it to start automatically. This is a specific feature of a screensaver, not a tour. The `auto_activate` section of the screensaver config JSON can then be removed, which would leave the whole config file as pure JSON, and allow it to be stuck in a database. It also means that the config file only ever needs to reference object classes defined in the "template" file, rather than in the rest of the UI.

So my suggestion is that we create another `Screensaver` class, which *contains* a single `Tour` class. The auto timing code that is currently incorporated into the `Tour` class should be extracted and placed into the `Tour` class (or alternatively, but probably less elegantly the `Screensaver` class could extend the `Tour` class with this functionality). The screensaver can be called with an `inactive_duration` time, and possibly some js code which might include references to UI objects, if necessary, to hide popups etc. (in fact, we can simply pass `UI_callbacks.closeAll()` as a callback to activate before starting the screensaver). 

The `onezoom` object can only have a single screensaver, but you could imagine (in the future) that it could create and destroy many tours.

I wonder if this is some jiggling around of code that @kz12 could do?

**Comment by hyanwong** [comment]
This is mostly done with af1cc93bfdb9172c0d4c625207b482f84ed8bafb but after putting some console logs in, it seems that the screensaver is going mad, and firing off timers thousands of times (and also `tree_state.last_active_at` never seems to be reset). 

I hope this is something that @kz12 might be able to fix, if he can see what it is that I've tried to do i the new Screensaver.js file.

**Comment by hyanwong** [comment]
@kz12  - fixing the screensaver so that the timers fire off at the right time seems a good priority at the moment. If you could keep that code in the new `Screensaver.js` file within thr `tours` directory, that would be most helpful.

**Comment by kz12** [comment]
@hyanwong 
The issue of triggering screen saver too frequently is now fixed. It is caused by two issues:

1. last_active_at is not reset when the view refreshes
2. screen saver should not be activated when it is started

I notice that you've add a loop mode in screen saver. It seems that there is an issue with it now. I'll take a look at it later.

**Comment by hyanwong** [comment]
Great, thanks so much.

Yes, do look at the loop mode later. It was a little hack, using negative numbers as indexes, but I thought it should work.

**Comment by kz12** [comment]
This should be working now. The removal of `ott_end_id` simplify this issue a lot. If you add `ott_end_id` later, then it needs to take care of how to do a reverse transition inside a tour stop.

**Comment by hyanwong** [comment]
This is working now, I think
