### ISSUE TITLE
Move the URL parsing for museum displays into the OneZoom controller

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#202]
We have redundantly coded 2 url parsers: one in layout.html, and one in OZTreeModule. We should remove the one ins layout.html, which only deals with 2 parameters:

1) the screensaver time. This should be parsed by the OZTreeModule parser and then read by the screensaver module coded up in #200 
2) the home_ott_id. This should be parsed by the OZTreeModule parser, and stored internally as a "home-location" by the OneZoom instance - e.g. in a `home_location` variable, which can be get and set using e.g. `onezoom.controller.get_home_location` and `onezoom.controller.set_home_location`. Then to go to the home location, you should simply call e.g. `onezoom.controller.go_home()`, which we can bind to the reset button.

**Comment by jrosindell** [comment]
The reason for two separate URL parsers was...

1.) the main content of the code is not the parser itself but the code of what to do with those parameters

2.) there is a reasonably clear distinction between the part of the URL related to tree position and the part related to UI and tree settings.  The first is purely about finding a location in the tree, whereas the second is everything else customisable about the display

Therefore maybe it's best left as it is.

**Comment by jrosindell** [comment]
Also the core and its URL parser should probably be distinct from the URL parser more specific to the HTML and specific application of the code.  E.g. if we built some totally different application around the OneZoom core such as a game then that game would still probably use the location part of the URL whereas the other bits would be not appropriate and would instead be replaced with the game specific parameters in the URL.

**Comment by hyanwong** [comment]
On 17 Sep 2019, at 07:58, James Rosindell <notifications@github.com> wrote:
> 
> The reason for two separate URL parsers was...
> 
> 2.) there is a reasonably clear distinction between the part of the URL related to tree position and the part related to UI and tree settings. The first is purely about finding a location in the tree, whereas the second is everything else customisable about the display

Hmm - the part of the URL relating to tree position follows the `#` part, so that’s completely separate.

The part following the `?` contains settings for the tree itself, such as the fractal shape, which UI windows are open, the language, etc. We agreed that the screensaver is something that only the OZ module should know about (it’s not part of the UI layer). Similarly, the home OTT id is something that the onezoom instance stores as an internal parameter, which affects where the viewer jumps to when you call `onezoom.controller.button_reset()`. These are both features of the onezoom instance, not a UI layer thing. So I think they should be parsed by in OZTreeModule.

**Comment by hyanwong** [comment]
> On 17 Sep 2019, at 08:01, James Rosindell <notifications@github.com> wrote:
> 
> Also the core and its URL parser should probably be distinct from the URL parser more specific to the HTML and specific application of the code. E.g. if we built some totally different application around the OneZoom core such as a game then that game would still probably use the location part of the URL whereas the other bits would be not appropriate and would instead be replaced with the game specific parameters in the URL.

The URL parser is not just concerned with location, though (see my other comment). Are you confusing the *location* parser and the more general URL parser? Currently within OZTreeModule we do parse_querystring() *and* parse_location(). I’m talking about modifying parse_querystring(), which currently parses out the following params (all of which seem just as much part of the UI as e.g. ottdef)

* pop
* vis 
* init
* lang

**Comment by kz12** [comment]
@hyanwong 
Hi Yan, I made a mistake in understanding James's question. James was just helping me to compile the answers. 

I thought he was asking why do I parse these parameters in two different files. But in fact you were asking that why do we have 2 separate URL parsers. 

Yes, you are right. There is no need to create a separate URL parser. We could export 'parse_querystring' function and re-use it.  

There are two more things need to be done in order to re-use it:
1. rewrite 'parse_querystring'. Currently it is hard coded about the parameters that it is able to parse
2. export 'parse_querystring' to OZEntry. There is no suitable object to export utility function though. I think we can create a utility object on OZEntry.

**Comment by hyanwong** [comment]
Thanks @kz12 - I think it's just a question of adding `ottdef` (should we rename this to `otthome`?) and `ssaver` to `parse_querystring()`.

I'm not sure we even need to export `parse_querystring` to OZentry. We can probably use the URL parser to set the values in `state` variable stored inside the onezoom instance, and access them within the tours module directly. No need to mention them in the html files.

**Comment by kz12** [comment]
The reason for adding `ssaver` in html is that I regard `screen_saver` as a normal type of `Tour` which does not have a hard-link with `ssaver` in URL. Hence, I need to parse it in html and inject this setting into `screen_saver`.

However, if you regard `screen_saver` as a special type of `Tour`, then it sounds perfectly ok to parse it from internal module.

Another parameter is `ottdef`, or you would like to rename it to `otthome`. It is parsed in the html file because I need to find it's ozId before onezoom is loaded, so that the tree could be centred around `ottdef`.

**Comment by kz12** [comment]
I think that `ottdef` should also be parsed inside onezoom instance. The `setup` function in OZEntry would need to be rewrite to prefetch the ott to id map of `ottdef` before the onezoom instance is actually built.

**Comment by hyanwong** [comment]
There is only one use-case for the screensaver - it's not functionality that "normal" tour users would every be able to access, so I think it's fine doing this all internally (what do you think @jrosindell?).

Could the `otthome` parameter not be treated in the same way as the ott value passed in the normal URL (location part) - we don't have  problem centering around the value passed in to the location, so I assume it should be possible for `otthome` too?

**Comment by hyanwong** [comment]
> I think that `ottdef` should also be parsed inside onezoom instance. The `setup` function in OZEntry would need to be rewrite to prefetch the ott to id map of `ottdef` before the onezoom instance is actually built.

Yes, I agree. I guess that's what we do with the location part of the parser? That uses OTTs and not internal OneZoom IDs, so it must use the ott-to-id map too?

**Comment by kz12** [comment]
> 
> Yes, I agree. I guess that's what we do with the location part of the parser? That uses OTTs and not internal OneZoom IDs, so it must use the ott-to-id map too?

Yes. When onezoom is setup, it would call `setup_loading_page`. This function would then call `search_init` to find the ott-to-id map of the id in URL. We could search `ottdef` when we fetch ott-to-id map in `setup-loading-page` and thus the problem should be solved.

**Comment by hyanwong** [comment]
Perfect. Thanks.

**Comment by kz12** [comment]
These parameters are moved into OneZoom code package now. The `ssaver` parameter is stored in `tree_setting` and `screen_saver` would access `ssaver` from `tree_setting` object.
