### ISSUE TITLE
Return promises from flight and leap functions

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#203]
At the moment, the (newly renamed, at least on the education-functions branch) functions that are used to move around the tree (defined in `controller_anim.js`) are:

* `fly_on_tree_to()`
* `fly_straight_to()`
* `leap_to()`

(and also less vitally, `init_move_to`)

The first of these returns a javascript promise. The rest return booleans, but probably should return promises.

**Comment by hyanwong** [comment]
At the moment, I've hacked around this in the tours function by wrapping `fly_straight_to()` and `leap_to()` within a promise in the code in `TourStop.js`, but since I don't really understand it, when running a tour I'm getting js errors of the form `Unhandled Promise Rejection: undefined`. I guess @kz12 will knock these on the head when he closes this issue.

**Comment by kz12** [comment]
@hyanwong 

I've made some changes to fly_on_tree_to before. It would throw an exception whenever fly animation is interrupted. This exception is not used and is not handled in tour stop. I will catch the exception and add an empty catch handler to get rid of the error.

**Comment by hyanwong** [comment]
Great, thanks @kz12 - if all the `fly_to` and `leap_to` functions were consistent in returning promises and the exceptions they return, that would be great. Thanks!

**Comment by hyanwong** [comment]
@kz12 - we need to think about what happens when the current location is too close to the target location to want to do a jump or fly. For example, do we raise a specific type of error, which we then (mostly) ignore when doing `promise.then` (I guess in nearly all cases we want to carry on doing the `then` clause even if there wasn't a physical jump in this case, whereas in the case of an animation interrupt, we are unlikely to want to do the `then` function?)

**Comment by kz12** [comment]
I don't think the implementation of `jump` or `fly` should be coupled with where the current location is. I think it depends a lot on the scenario. User should test whether the current location is too close and do something which suits the scenario best. For example,

1. User interrupts fly animation during tutorial, then user starts next tour stop, and it is getting too close, it should start next fly animation without jump
2. User click on reset button. Then it should jump even if it's close

Based on what I write here, the code should be look like:

```javascript
//Scenario 1, jump only when view is not close
if (view_close_to_target()) {
  call_func_after_leap()
} else {
  leap().then(() => {
      call_func_after_leap()
  })
}

//Scenario 2, Jump regardless of how close it is to the target location
leap().then(() => {
  call_func_after_leap()
})
```

If we couple the logic into fly and jump, the code would be like this:

```javascript
//Scenario 1, jump only when view is not close
leap()
.then(() => {
     call_func_after_leap()
})
.catch(err => {
     if (err typeof TooCloseError) {
         call_func_after_leap()
     }
})

//Scenario 2, Jump regardless of how close it is to the target location
//I think we might not be able to jump if it throws an error 
```

**Comment by hyanwong** [comment]
You are right. The first seems more sensible to me.

**Comment by hyanwong** [comment]
@kz12 you may be able to help with something else too. At the moment, when fully zoomed out and just reloaed, the  tutorial is not responding to the command `fly_on_tree_to(-837461)`. The console log reports `Flying on tree to: -837461 (770315)`, but the location on screen remains unchanged, at least in the 2 browsers I have tried on my laptop.

I thought I had fixed it with 67eba02103e71ee3657e786bb16c9b1889815b95, but it appears not. Do you know what is going on?

If I call `onezoom.controller.fly_on_tree_to(-837461)` directly in the console, the viewer jumps (not flies) to humans, and I get the following console error:

```
Promise {<pending>}
factory.js:100 Uncaught (in promise) Error: Couldn't find node undefined within 1
    at _dl_codein_fly (factory.js:100)
    at Factory.dynamic_loading_by_metacode (factory.js:50)
    at Controller.develop_branch_to (controller_anim.js:367)
    at Controller.<anonymous> (controller_anim.js:257)
```

**Comment by hyanwong** [comment]
@kz12 - I just realised that in tours we might want to chain the fly or leap event to something beforehand (e.g. a wait). Something like

```
let promise = Promise.resolve()
promise.then(() => {wait 2 seconds})
promise.then(() => {fly_on_tree_to(pos)})
promise.then(() => {do something else})
```

Is that possible? Would that mean changing the return type of `fly_on_tree_to()`?

**Comment by kz12** [comment]
> @kz12 - I just realised that in tours we might want to chain the fly or leap event to something beforehand (e.g. a wait). Something like
> 
> ```
> let promise = Promise.resolve()
> promise.then(() => {wait 2 seconds})
> promise.then(() => {fly_on_tree_to(pos)})
> promise.then(() => {do something else})
> ```
> 
> Is that possible? Would that mean changing the return type of `fly_on_tree_to()`?

That is possible. However, the code needs to be changed:

```javascript
let promise = Promise.resolve()
promise
  .then(() => {return wait 2 seconds})
  .then(() => {return fly_on_tree_to(pos)})
  .then(() => {do something else})
```

Remember that both `wait 2 seconds` and `fly_on_tree_to` should return a promise here because it is async function. If a `promise` receives a `promise` as `return value` in `then` clause, it would wait for it gets resolved before it continues.

**Comment by kz12** [comment]
> If I call `onezoom.controller.fly_on_tree_to(-837461)` directly in the console, the viewer jumps (not flies) to humans, and I get the following console error:

The first parameter in `fly_on_tree_to` is the source OZ Id, the second parameter is the destination OZ Id. This function would firstly jump to the location marked by the first parameter and then fly to the location marked by the second parameter. Since the second parameter is not provided, the factory is unable to develop sub-branches around the target node.

**Comment by kz12** [comment]
The bug is fixed now. Sometimes `perform_actual_fly` would never call `finalize_func` or `abrupt_func`, hence the `promise` in `fly_on_tree_to` would never be resolved or rejected.

The fix is invoking the `finalize_func` in the `if` clause in `perform_actual_fly`:

```javascript
if(((r_mult>0.9999)&&(r_mult<1.00001))&&(x_add*x_add<1)&&(y_add*y_add<1)) {
    // nothing to zoom to so better to do nothing and return false or it feels like a bug
    if (typeof finalize_func === "function") {
      finalize_func()
    }
    return false;
}
```

**Comment by hyanwong** [comment]
Thanks @kz12 - you are a miracle-worker!

**Comment by kz12** [comment]
`fly_straight_to` and `leap_to` is also updated to return a `promise` in the updated code. Also simplify the code where it is now wrapping `fly_straight_to` and `leap_to` inside a `promise` constructor, to return the result of `fly_straight_to` and `leap_to` directly.

**Comment by hyanwong** [comment]
Perfect, thanks so much.

**Comment by hyanwong** [comment]
@kz12 - In 1e276a43885ad5bc31678a26359bea9d413309b1  I've tried to chain the promises but this doesn't seem to be working: the tutorial tour boxes are popping up in quick succession, rather than waiting for the next event. What am I doing wrong?

**Comment by kz12** [comment]
@hyanwong - The `then` clause of promise should receive a function, not the result of a function.

Here is what you write:

```javascript
promise
  .then(this.controller.fly_on_tree_to(null, this.OZid, into_node, speed))
  .catch(() => {})
```

You're passing the function result to `then` clause. In this case, the `promise` would execute next `then` clause without waiting for the return `promise` of `fly_on_tree_to`.

The right way of writing it should be:

```javascript
promise
  .then(() => this.controller.fly_on_tree_to(null, this.OZid, into_node, speed))
  .catch(() => {})

//or

promise
  .then(() => {
        return this.controller.fly_on_tree_to(null, this.OZid, into_node, speed)
   })
  .catch(() => {})

//or you could simple do the following as I notice that the promises are actually not chained in tour_stop.js
promise = this.controller.fly_on_tree_to()
```

**Comment by hyanwong** [comment]
Great, thanks. Yes, nothing is chained yet, but I'm going to add something, so will try this. Thanks so much.

**Comment by hyanwong** [comment]
@kz12 : I've just tried this and it doesn't seem to fix it - I still get the boxes appearing one after the other in quick succession, without waiting for the transitions. What I'm trying to do is coded up in b598eacd3da698fab286d1d6a0e6120b4d782b00

**Comment by kz12** [comment]
@hyanwong - I've updated the code and it's now fixed. `then` clause of `promise` would return a new `promise` object. You need to chain following `then` clause on the new `promise` object, instead of the old `promise` object

```javascript
promise = Promise.resolve()
promise
  .then(() => delay(200))
  .then(() => doSomething())
  .then(() => fly())

//The above equals
promise = Promise.resolve()
promise = promise.then(() => delay(200))
promise = promise.then(() => doSomething())
promise = promise.then(() => fly())

//If you write the following
promise = Promise.resolve()
promise.then(() => delay(200))
promise.then(() => doSomething())
promise.then(() => fly())

//It equals to:
promise = Promise.resolve()
promise.then(() => fly())
```

**Comment by kz12** [comment]
Youl could open your console and input the following code:

```javascript
const delay = (delayTime) => {
  return new Promise((resolve) => {
    setTimeout(() => {console.log('delay', delayTime);
      resolve()
    }, delayTime)
  })
}

//log appears after 1, 2, 3 seconds respectively
promise = Promise.resolve()
promise
  .then(() => delay(1000))
  .then(() => delay(1000))
  .then(() => delay(1000))

//log appears after 1 seconds simultaneously
promise = Promise.resolve(); 
promise.then(() => delay(1000)); 
promise.then(() => delay(1000)); 
promise.then(() => delay(1000));

```

**Comment by hyanwong** [comment]
Ah, that clarify how it works, thanks!
