### ISSUE TITLE
block user interaction when on flight with no box on tour

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#205]
To prevent a paused tour with no dialogue box...

test if

1.) interaction is null or defaulted (not any of the other settings)
2.) flight is happening (either kind)
3.) force hide is true

note that there are edge cases in case force hide is false but we're not worrying about that for now because we're going to set force hide true in the tour whenever we think this can happen

**Comment by kz12** [comment]
It is updated now. However, there are some tour stops having fly_in_visibility as 'force_show' and 'null'. The information box is not shown when the stop is set to these values. Maybe @hyanwong could change the value for these stops?

**Comment by hyanwong** [comment]
It was a bug. We were calling tourstop.exit() which hid the previous stop. We want the previous stop to carry on being shown even after exit, unless force_hide is true. I've fixed in in b4703f182b08742cde988fae60b47d4d31865413 (first change listed)
