### ISSUE TITLE
Pysql programming error

### ISSUE THREAD

**Issue by kz12** [OneZoom/OZtree#209]
When I run my mysql server the first time after I start my mac, I can't open OneZoom landing page. It says the following error:

<img width="889" alt="Screen Shot 2019-09-23 at 10 22 00 AM" src="https://user-images.githubusercontent.com/3263319/65398916-7e26c080-ddec-11e9-9d4b-d84de23cc535.png">

Then I stop my mysql server and start it again, everything works well. My mysql version is: 5.6.13, MySQL Community Server (GPL). My osx version is: osx10.7   (x86_64).

**Comment by hyanwong** [comment]
Have you upgraded to the latest web2py version?

**Comment by kz12** [comment]
My web2py version is: Version 2.18.5-stable+timestamp.2019.04.08.04.22.03

I think it's close to the latest.

**Comment by hyanwong** [comment]
Yes, that sounds fine. How about your pymysql version? I had an issue once where web2py was using the old version of pymysql that I had installed, rather than the newer one bundled with web2py.

**Comment by kz12** [comment]
I'm confused. 

I opened python in terminal and type this: `import pymysql`, but it says: 'ImportError: No module named pymysql'. 

But it must be there, isn't it? Otherwise OneZoom couldn't run on my mac at all. Is it that web2py provides pymysql module in its framework, so that when I run `python web2py.py`, it would load the module from its framework?

**Comment by hyanwong** [comment]
I think web2py provides its own (local) version. Maybe the problem I had was that I *also* had another version installed, and web2py used that where available instead. So you can probably ignore my comment, and it all still remains a mystery.

**Comment by hyanwong** [comment]
I'm closing this, after the move to Python3
