### ISSUE TITLE
Tour doesn't always hide tour contents when ended.

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#210]
<img width="1004" alt="OZbug1" src="https://user-images.githubusercontent.com/3009279/66273602-40567d00-e86d-11e9-9643-3e598e0e5dee.png">

**Comment by jrosindell** [comment]
to repeat the issue, start a tutorial, then press skip, then press exit (Safari / Chrome)

**Comment by hyanwong** [comment]
Think this is fixed, closing
