### ISSUE TITLE
Pin down timeline for tour transitions

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#211]
As discussed with @kz12 and @jrosindell , it would be useful to pin down *how* we expect tourstops and transitions to be chained together. Below is my first attempt at a schematic:

[ToursTimeline.pdf](https://github.com/OneZoom/OZtree/files/3722196/ToursTimeline.pdf)

**Comment by lentinj** [comment]
Closing in preference of #539, which will need to update this diagram as part of the work

**Comment by hyanwong** [comment]
Here's the powerpoint version (converted from apple keynote):
[ToursTimeline.pptx](https://github.com/OneZoom/OZtree/files/8744162/ToursTimeline.pptx)
