### ISSUE TITLE
Global search box

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#212]
```
* Has to be standalone since it ought work an all pages, e.g. FAQ
  - Use OZentry:api_utils_setup()
* TODO
  - Move styling from tree.css into a search.css
  - Alter populateByNodeResults() result format to include the @...=... portion of link?
    . Currently bunging extra javascript attributes on array object, ugly. Does it need to stay array?
  - Give searchPopulate() a proper home (where?)
    . It's not dynamic, only uses {{if is_testing:}}
    . jQuery uses don't suit going into search_manager
  - Keep '.searchinput input' in include for search heading
  - Generate links for all users of searchPopulate() - click handler prevents links working
  - Move OZstrings definition to <head>, just for clarity (it's an expected global elsewhere, shouldn't be lost in <script>)
* Where do we set that pages go to /life.html? Variable in template header? Hard-coding?
```

**Comment by lentinj** [comment]
@jrosindell @hyanwong In the search box we need to link to e.g. ``/life.html/@SIRENIA=226183``. I'm assuming (for now) that I can get away with hard-coding ``life.html``, since we've no concept of theming the rest of the site we can go to the default theme anyway. Correct?

**Comment by lentinj** [comment]
@hyanwong the only uses of templating in the existing ``searchPopulate()`` code was ``is_testing``. I'm translating that by adding a ``window.is_testing`` global to the top of the templates. Sound good?

The other option would be to use ``console.debug``, a log level that isn't enabled in Javascript consoles by default. Possibly cleaner, but you'd have to get used to enabling it.

**Comment by hyanwong** [comment]
> @jrosindell @hyanwong In the search box we need to link to e.g. `/life.html/@SIRENIA=226183`. I'm assuming (for now) that I can get away with hard-coding `life.html`, since we've no concept of theming the rest of the site we can go to the default theme anyway. Correct?

Yes, I think the search from the top bar of the main page headers can be hardcoded to life.html (or even simply `/life/@FOO=123`.

**Comment by hyanwong** [comment]
> @hyanwong the only uses of templating in the existing `searchPopulate()` code was `is_testing`. I'm translating that by adding a `window.is_testing` global to the top of the templates. Sound good?
> 
> The other option would be to use `console.debug`, a log level that isn't enabled in Javascript consoles by default. Possibly cleaner, but you'd have to get used to enabling it.

I'm happy with either. The `is_testing` thing is a bit of a hack, so possibly console.debug is cleaner. However, I quite like the fact that wrapping stuff in the web2py `is_testing`condition means that the debug cruft is never exposed to the client *at all*, unless it is actively turned on (usually on the beta site). Creating a javascript `window.is_testing` variable for cases where we aren't creating the js in web2py views seems sensible in this case.

**Comment by jrosindell** [comment]
> > @jrosindell @hyanwong In the search box we need to link to e.g. `/life.html/@SIRENIA=226183`. I'm assuming (for now) that I can get away with hard-coding `life.html`, since we've no concept of theming the rest of the site we can go to the default theme anyway. Correct?
> 
> Yes, I think the search from the top bar of the main page headers can be hardcoded to life.html (or even simply `/life/@FOO=123`.

So this is about whether the search always takes us to life or whether it takes us to some other page like life_expert or OTOP?  Assuming I've understood correctly I'd say yes take it to life all the time - the other pages will be accessed from menu items / other places on the site.

**Comment by jrosindell** [comment]
A few thoughts on use of a common header across all tree explorer pages....

It will work fine on all but there are a few exceptions that will need to be catered for...

1.) life_MDmouse and life_MDtouch need a header with increased size as they are designed for a large touch screen

2.) life_treasure has search disabled and inserts a 'checklist' there instead - users are asked to find things without using search.  Best approach here is probably to add the checklist as a separate element.  This makes me think that the logo and search might need to be different things rather than combined in a single header.

3.) linnean - there is a second logo at the top though this can probably be added separately from the default header.

4.) OTOP and OTOP_MD should use the same OTOP styling as always.

**Comment by lentinj** [comment]
I've added the icon, but I'm not sure that changing the box shape makes sense unless the rest of the UI boxes match.

The search box is still in the old layout.html, it's not working since it's using old includes. I'm guessing I should just remove it.

**Comment by jrosindell** [comment]
Regarding the styling of the search - maybe we shouldn't regard this as a common header to all pages including the trees, but rather that each page has its own layout but uses the same underlying mechanics for the search - hence on the MD_* pages the size of everything can remain increased by CSS

**Comment by jrosindell** [comment]
From discussion with Yan, here are outstanding things on the search box...

- [ ] Missing search icon
- [ ] When applying search from outside of a tree view (i.e. as part of the header on the rest of the site) we should have the little icon used elsewhere on the front page to indicate the results will open a new tab, the code should be edited to make it open a new tab also (though of course not if already inside a tree view)

**Comment by lentinj** [comment]
> each page has its own layout but uses the same underlying mechanics for the search

This (should be) what's happening now, there's a bunch of new search_ui CSS and JS outputs generated by grunt, then the layout.html files hook into this and turn what are links for the home page into tree navigation actions for tree pages.

> the little icon used elsewhere on the front page to indicate the results will open a new tab

So all the leaf-out links on the homepage (all the tree links IIRC) should open in a new tab on the home page?

**Comment by lentinj** [comment]
Leaf out does open in a new window, along with all search items.

**Comment by jrosindell** [comment]
Agreed - sounds good.
