### ISSUE TITLE
Apply theming to homepage layout

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#215]
- [ ] Ensure home-page static text can be translated

**Comment by lentinj** [comment]
Actions from call 2019-11-08:

- [ ] No border under title banner
- [ ] Border around circles for tree and counts

**Comment by lentinj** [comment]
Remaining design bits to implement

* Species count circles
* Everyone/Education/Science pictures

Questions for Matt:

* Menu styling
* Can we improve the sponsored items? They feel a bit flat, but not sure what to do about them.

**Comment by hyanwong** [comment]
> * Can we improve the sponsored items? They feel a bit flat, but not sure what to do about them.

You can at least modify the query to replace the `if (request.vars.omit_nopics):` criterion with always true, so that you *always* use the ones with pictures.

**Comment by jrosindell** [comment]
Here's a summary of what's still to do here

- [ ] Add interpretation in sponsor section to match the mockup
- [ ] Add green circles with species numbers? (don't add ‘the tree’ in a third circle)

**Comment by lentinj** [comment]
> Add interpretation in sponsor section to match the mockup

It's hard to tell what the queries should be given the anonymised data I've got. Is this about right?

* "total sponsored leaves" ==> ``SELECT COUNT(*) FROM reservations WHERE verified_time AND deactivated = NULL...``
* "total sponsors" ==> ``SELECT COUNT(DISTINCT user_registration_id) FROM reservations WHERE verified_time AND deactivated = NULL...``

**Comment by jrosindell** [comment]
- [ ] I'm just noting here that on small screens we will cut the 'about us' menu instead of scrolling left and right across menus.  The functions of this menu will be replicated by content in the new footer, in the page itself, and in other menus 
- [ ] Add a button with 2 rounded corners on the end of the endorsements section and sponsorship section.

**Comment by lentinj** [comment]
(assuming queries above are either right, or close enough)

**Comment by lentinj** [comment]
Final point here gets it's own issue: https://github.com/OneZoom/OZtree/issues/226
