### ISSUE TITLE
Homepage dynamic elements

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#216]
Apart from "Popular places", dealt with in #214 

- [ ] "For everyone/education/science"
- [ ] "What they say" endorsements
- [ ] Sponsor
- [ ] Milestone / news

**Comment by lentinj** [comment]
@jrosindell What is the criteria for things to end up in the "For everyone/education/science" boxes?

* All menu items
* First 4 menu items
* Just static HTML, selections will be hand-crafted.

**Comment by lentinj** [comment]
In general, how many items do we have to hand for each carousel? Do we restrict to most recent news for milestones? x most recent sponsors? All endorsements?

**Comment by hyanwong** [comment]
For the milestones carousel, we thought only the most recent item (and if it isn't that recent, we might put in something there that isn't very associated with any particular time).

For the sponsors, we have hundreds. James and I will devise an algorithm which combines the most recent with the nicest pictures. The easiest might be to set up a simple API for this, so that we can tweak it without affecting your code.

For the endorsements, we imagined showing only one at a time, but automatically cycling through all(?) or them e.g. 6 seconds. James and I were debating whether or not allow the user to scroll back and forth through them, as well as automatically sliding them forwards. I'm not sure we came to a conculsion about what we through was best. Re numbers, there are 53 in the `quotes` table in the DB dump that I sent you. I created a 'quality' field which I imagined might be populated by hand and used somehow to decide, but I haven't though hard about how that would work. I could work this up into an API too: what do you think @lentinj , @jrosindell ?

**Comment by lentinj** [comment]
> For the milestones carousel, we thought only the most recent item (and if it isn't that recent, we might put in something there that isn't very associated with any particular time).

So milestones isn't actually a carousel, and the left/right arrows in the mockups wouldn't be there?

> For the sponsors, we have hundreds. James and I will devise an algorithm which combines the most recent with the nicest pictures. The easiest might be to set up a simple API for this, so that we can tweak it without affecting your code.

I'm looking at recycling the output of ``views.default.sponsored()`` for now, which looks like it's already doing something similar.

Again, this isn't actually a carousel, and no left/right arrows (except possibly for a mobile view that isn't wide enough).

> For the endorsements, we imagined showing only one at a time, but automatically cycling through all(?) or them e.g. 6 seconds. James and I were debating whether or not allow the user to scroll back and forth through them, as well as automatically sliding them forwards. I'm not sure we came to a conculsion about what we through was best.

It's probably wise to have a x most recent limit, even if that's higher than the number of quotes currently available.

> Re numbers, there are 53 in the `quotes` table in the DB dump that I sent you. I created a 'quality' field which I imagined might be populated by hand and used somehow to decide, but I haven't though hard about how that would work. I could work this up into an API too: what do you think @lentinj , @jrosindell ?

It would be easy enough to apply after the fact, I'm not sure it's worth the effort of fetching the rest of the quotes separately in an API call and filling them in, vs. having them all as part of the index page HTML.

**Comment by lentinj** [comment]
Another problem with Milestone / news: The layout demands an image on the left, title, and text. We currently have a date (which could be used as a title) and lump of HTML, within which any images associated with the article are contained. There's a text_summary, but it seems mostly empty.

Ideally we'd have image, title (or date), text.

Either the schema (and existing data) needs to be altered to match, the layout, or we bodge the existing data to match (strip images from HTML, first ``<img>`` in HTML becomes side image). Any preferences?

**Comment by jrosindell** [comment]
> @jrosindell What is the criteria for things to end up in the "For everyone/education/science" boxes?
> 
> * All menu items
> * First 4 menu items
> * Just static HTML, selections will be hand-crafted.

I think it should not be all menu items.
static HTML was the original idea, however I like the idea of making it more automatic.
What about First 4 menu items with a ... or something to expand the list to the full menu if wanted?

**Comment by jrosindell** [comment]
> @jrosindell The Sponsor / follow / links / milestones section. Is this part of the homepage, or part of the footer (and on all pages)?

I've got mixed feelings about this, partly because it's the part of the front page that I'm currently least happy with.  I think it has been always intended as part of a larger footer that appears as the layout for all (non tree) pages

**Comment by hyanwong** [comment]
> > For the milestones carousel, we thought only the most recent item (and if it isn't that recent, we might put in something there that isn't very associated with any particular time).
> 
> So milestones isn't actually a carousel, and the left/right arrows in the mockups wouldn't be there?

Sorry - I was being confusing. The idea would be to have a carousel, but only show one item at a time (unlike e.g. the sponsor images, where, say, 5 are shown at a time. But the idea would be to be able to flick though them, I guess. As you say, some might have images, some not, so we'd have to think about how this would work.

**Comment by hyanwong** [comment]
> > For the sponsors, we have hundreds. James and I will devise an algorithm which combines the most recent with the nicest pictures. The easiest might be to set up a simple API for this, so that we can tweak it without affecting your code.
> 
> I'm looking at recycling the output of `views.default.sponsored()` for now, which looks like it's already doing something similar.
> 
> Again, this isn't actually a carousel, and no left/right arrows (except possibly for a mobile view that isn't wide enough).

I think the idea would be to be able to scroll through all of them (or perhaps the top 20), so it would be a carousel.

**Comment by lentinj** [comment]
> @jrosindell What about First 4 menu items with a ... or something to expand the list to the full menu if wanted?

I think that makes the layout unnecessarily complex, we'd have to deal with the side images not reaching, and if we've fully replicated the menu then you'll get people using that instead of the actual menu (and getting frustrated at all the to-ing and fro-ing.

> > @jrosindell The Sponsor / follow / links / milestones section. Is this part of the homepage, or part of the footer (and on all pages)?
> 
> I've got mixed feelings about this, partly because it's the part of the front page that I'm currently least happy with. I think it has been always intended as part of a larger footer that appears as the layout for all (non tree) pages

My main beef with it is potentially introducing database queries to every page. I'm not sure the milestones bit adds anything to warrant being on every page (especially on the home page, when it's just below the actual milestones).

**Comment by hyanwong** [comment]
> My main beef with it is potentially introducing database queries to every page. I'm not sure the milestones bit adds anything to warrant being on every page (especially on the home page, when it's just below the actual milestones).

Although if there are a couple of sponsored photos on the LHS of the footer, as at present, this risks introducing a DB query for each page, unless we hardcode a selection of (say) 3 nice ones.

**Comment by lentinj** [comment]
@hyanwong yes, I'd not commented on those. In a way they're worse. With the milestones it can be  a daily cache and nobody would notice. I'm assuming they're ones I *could* sponsor (although it's not obvious), in which case I might be pretty miffed if I did sponsor the squirrel only to find it still there on every page.

I think we should just remove them (although we should probably be discussing this with Matt / Jay).

**Comment by hyanwong** [comment]
> I'm assuming they're ones I _could_ sponsor

Ah, I'd assumed they are the ones that have *just* been sponsored. But I guess that illustrates the confusion.

**Comment by hyanwong** [comment]
Just thinking about this, if these are images of potentially sponsorable species (I think you are right that this is what was intended) it could still be a pretty fast query, I think. And might there be something we could do with SQL caching too?

**Comment by hyanwong** [comment]
Here, for instance, is an SQL command that simply picks 6 high quality, non-sponsored images (we could randomly chose 3 out of those 6 to show, to give some variety). It takes about a millisecond to evaluate on my laptop:

```
select images_by_ott.src, images_by_ott.src_id from images_by_ott join reservations on images_by_ott.ott = reservations.OTT_ID where reservations.PP_transaction_code is NULL and images_by_ott.rating >= 30000 and images_by_ott.ott not in (select ott from banned) limit 6
```

**Comment by lentinj** [comment]
@hyanwong @jrosindell On the mockup we have the text:

> TODO: people like you have helped us by making donations. Their names appear as sponsors on TODO: leaves of our tree of life." in the sponsor section. 

"TODO: leaves" seems pretty easy, just a count of reservations, and assume expired reservations have been deleted. There doesn't seem to be anything that tracks unique users for the former number though?

Do we cheat and skip that bit in the text?

**Comment by lentinj** [comment]
Matt says use the science uncovered image for events.

**Comment by lentinj** [comment]
Notes from meeting on Milestones:

* Keep using date as item title
* Add HTML summary (fall back to HTML description if unpopulated)
* Image column for Milestones, but have fall back image per-category, e.g. "events".
* Most recent items, or if this is too old, random "big" milestones. Change the title of the milestones section to reflect which mode we're in.

Other notes:
* Endorsements should auto-rotate
* At end of sponsored carousel, item linking to ``sponsored.html``.

**Comment by jrosindell** [comment]
One more thing to add - the X button should be a pause on the animated tree.  When paused, the pause button should be replaced with play and vice versa.

**Comment by jrosindell** [comment]
For the sponsorship section

- [ ] for now use sponsored?omit_nopics=1 API calls so only sponsorships with images will be retrieved.
- [ ] if time, build a new API that basically just does sponsored?omit_nopics=1 but enables us to change this in the controller later - hence the system is closer to enabling a bespoke API to choose images for the sponsorship section
- [ ] For the text formatting - we'll ask Matt, but I think make all the text be one string with smaller font, (same size as the quote names) - please don’t spend loads of time on this - only do if easy.

**Comment by lentinj** [comment]
> if time, build a new API that basically just does sponsored?omit_nopics=1 but enables us to change this in the controller later - hence the system is closer to enabling a bespoke API to choose images for the sponsorship section

The index controller does it's own heavily-inspired-by query for the sponsored section, so I think you can regard this as already done?

**Comment by lentinj** [comment]
> For the text formatting - we'll ask Matt, but I think make all the text be one string with smaller font

I've done the easier bits of his design, the lines dividing items is a pain, since you don't know what's leftmost and rightmost in UI-kit's slider.

**Comment by jrosindell** [comment]
> > For the text formatting - we'll ask Matt, but I think make all the text be one string with smaller font
> 
> I've done the easier bits of his design, the lines dividing items is a pain, since you don't know what's leftmost and rightmost in UI-kit's slider.

As discussed don't worry about the dividing lines.

**Comment by jrosindell** [comment]
> The index controller does it's own heavily-inspired-by query for the sponsored section, so I think you can regard this as already done?

You can keep it as is, there is plenty more to do elsewhere.  I think that at some later point we might want to change the controller and the sponsored section controller may end up being different to that used for the sponsored.html page controller in more ways than just sifting for images, but for now let's not worry about it.

**Comment by lentinj** [comment]
No issues left here, can pick up any issues in separate tickets.
