### ISSUE TITLE
Global footer

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#220]
Style footer as per mockups

- [x] Footer sponsor
- [x] Footer milestones

**Comment by lentinj** [comment]
@jrosindell The footer quick links is hard-coded, but just grabbed from the menu for now, if you'd like to replace them with what they should be.

**Comment by jrosindell** [comment]
- [ ] For the sponsored leaves in footer - please add three small pictures - we will change the static link and pictures as necessary later, but for now use any.
- [ ] Remove the footer milestones section and instead have two columns of quick links with a single quick links heading - these should again be static like all in the footer

**Comment by jrosindell** [comment]
I think we're going to have 'about us' links in the upper footer instead of a second quick links column.

**Comment by lentinj** [comment]
@jrosindell I've hard-coded the about links in the footer, rather than reading the web2py menu. I'm guessing this is more useful, so they can vary?

**Comment by hyanwong** [comment]
Yep, hard coding is fine. Thanks!
