### ISSUE TITLE
CSS layout issues for front page

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#223]
For SMALL screens....

- [x]  In the header - make font size and gaps smaller so no horizontal scroll is needed to see all four main menu items
- [x] Add padding on left and right e.g. biodiversity and conservation section - the text goes right to the edge of the screen
- [x] Too much vertical padding in 3 main sections for 'everyone', 'eduction' and 'science' - there are huge white gaps between them
- [x] Carousel arrows vanish lower down
- [x] the upper part of the footer goes onto multiple rows unnecessarily.

For LARGE screens

- [x] The main top part of the page under the header, including the title, goes over two lines unnecessarily.  The maximum width of this (and other) elements doesn't seem right for this screen width.

**Comment by lentinj** [comment]
>  the upper part of the footer goes onto multiple rows unnecessarily.

I'm not sure what this is referring to, got a screenshot?

**Comment by jrosindell** [comment]
I'm just making a note to say all this has been discussed with Jay over Skype
