### ISSUE TITLE
Apply homepage header to other pages

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#224]
Please see Matt's design for this

**Comment by hyanwong** [comment]
We can locate the old versions that haven't yet been converted to the new layout using e.g.

```
grep -L 'uikit_layout.html' views/default/*.html
```

**Comment by hyanwong** [comment]
These all need a masthead defining, if we are to use them

**Comment by hyanwong** [comment]
Should be done with #302 . The original layout file is still used for e.g. management pages. I think that's OK. It's also used for the popularity API description, and possibly in a few other places where we might like to change it.

**Comment by jrosindell** [comment]
I think this is done now
