### ISSUE TITLE
Custom tourstop icons

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#226]
UI kit icons are not suitable for the animated tree on the new front page - get next, last, play and pause SVG icons from Matt.

**Comment by lentinj** [comment]
@jrosindell Caught up with Matt, we got this sorted today, think it looks a lot better.

**Comment by lentinj** [comment]
(Matt apologies, the e-mails about this got lost in the Christmas rush)

**Comment by hyanwong** [comment]
Great, thanks.
