### ISSUE TITLE
Menu bars a tiny bit too close to "Welcome..." text on small screens?

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#227]
- [x] When the width forces the menu items to below the logo/search box, it's quite close to the Green "Welcome ..." text. Could we add a pixel or two in there?
- [x] Also perhaps the text that says "Our tree of life explorer is designed to be easily accessible for everyone; we also provide educational tools for teachers, software for scientists and interactive exhibits for museums." is a little close to the box below, considering the line spacing within the para - perhaps either decrease the line spacing on smaller screens or increase the bottom margin/padding a little?

![Screenshot 2019-12-11 at 22 28 08](https://user-images.githubusercontent.com/4699014/70665922-85c86980-1c65-11ea-841a-4c986f3ab0a1.png)

**Comment by jrosindell** [comment]
I find this part of the page a bit strange for other reasons too.  The four menus go onto two lines when the could still be fitted into 1 line but off centre.  Then, when on two lines they should probably spread out a bit more to use the horizontal space.

**Comment by lentinj** [comment]
> The four menus go onto two lines when the could still be fitted into 1 line but off centre.

That (shouldn't) be possible, at very least I've never seen it. Got a screenshot?

**Comment by jrosindell** [comment]
<img width="993" alt="OZ_FP_layout" src="https://user-images.githubusercontent.com/3009279/71253243-4530b600-231f-11ea-898c-4354bb93a07e.png">
This shows what I'm talking about

**Comment by lentinj** [comment]
Oh! I see what 2 lines refers to now. Sorry. This relies on media queries so can't be a precise science, and the cut-off is errs on the side of caution. If the search box was the same width as the new logo (width: ~13rem instead of width: 16rem), then the centered-to-page menu will fit in the gap better (max-width: 900px instead of max-width: 1000px). But obviously means you get less space to type in.
