### ISSUE TITLE
Layout issues on front page

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#232]
- [x] overall footer links should be 3 columns on a narrow screen, they are 2
- [x] on mobile - biodiversity and conservation section has 1 leaf when room for 2 or 3
- [x] on mobile (iPhone SE)- ‘what they say’ arrows slightly off side same for ‘news’ section 
- [x] scroll left and right on mobile moves view far off side of page
- [x] footer content on mobile - not quite right as it collapses to 2 columns when there are three things - the final thing is left on its own (follow us section)
- [x] on mobile especially there is often too much white space when news items are too short in the carousel compared to some others
- [x] as screen size is narrowed the tree height doesn't decrease and it ends up being too tall / out of shape.  On mobile it already starts both narrow and not too tall so that part is OK

**Comment by jrosindell** [comment]
start exploring box (previously called ‘show me how’) not tied to the bottom right of the box it’s sitting within
<img width="655" alt="OZ bug dec 2019" src="https://user-images.githubusercontent.com/3009279/71120050-743a1100-21d3-11ea-8897-32bfe0359f71.png">

**Comment by jrosindell** [comment]
For the three boxes 'for everyone' .... they can easily get into a state where the images displayed are very thin and look ugly.  Probably the best solution is to place them below the text as the three sections get too thin or to move them one on top of the other sooner.

<img width="924" alt="OZ bug dec 2019 2" src="https://user-images.githubusercontent.com/3009279/71120257-edd1ff00-21d3-11ea-8f3d-0f3cba9d28b6.png">

**Comment by lentinj** [comment]
> For the three boxes 'for everyone' ....

I did experiment with this a bit, but putting them below the links then ate up a good chunk of screen space on an iPhoneSE size screen needlessly. To not eat up the entire screen with a single "for x" menu, they'd have to be as short as they are narrow in your screenshot.

Agreed that there should be a cut-off before you end up with such silly views as above.

**Comment by lentinj** [comment]
> start exploring box (previously called ‘show me how’) not tied to the bottom right of the box it’s sitting within - this happens especially when the width of the page is played with

The root of this is the tree view fixing it's aspect ratio on load. So as you resize you end up with the tree view forcing the table here to be much higher than the content in it is expecting.

**Comment by lentinj** [comment]
> overall footer links should be 3 columns on a narrow screen, they are 2

I'm not sure they fit:

![screen](https://user-images.githubusercontent.com/586911/71187838-c59bdc00-2277-11ea-999e-02401a28c6bd.png)

**Comment by lentinj** [comment]
"footer content on mobile - not quite right as it collapses to 2 columns when there are three things - the final thing is left on its own (follow us section)" is the same as "overall footer links should be 3 columns on a narrow screen, they are 2", correct?

**Comment by lentinj** [comment]
> on mobile especially there is often too much white space when news items are too short in the carousel compared to some others

We can't do too much about that, as then the left/right arrows start jumping up and down as the space enlargens and decreases. The best we can do is proper summaries for news items which are roughly the same length.

**Comment by jrosindell** [comment]
> "footer content on mobile - not quite right as it collapses to 2 columns when there are three things - the final thing is left on its own (follow us section)" is the same as "overall footer links should be 3 columns on a narrow screen, they are 2", correct?

Sort of, I guess one this is small screens where the three can fit, the other is *very* small screens where they cannot fit.  Maybe the solution is to balance it with two columns of quick links, then about the contact so that the about / contact go below on a narrow screen

**Comment by lentinj** [comment]
> start exploring box (previously called ‘show me how’) not tied to the bottom right of the box it’s sitting within - this happens especially when the width of the page is played with

> as screen size is narrowed the tree height doesn't decrease and it ends up being too tall / out of shape. On mobile it already starts both narrow and not too tall so that part is OK

The above doesn't solve the root cause (the canvas preserving the aspect ratio), but it does make it a lot more bearable by the start exploring staying where it should.

**Comment by jrosindell** [comment]
> overall footer links should be 3 columns on a narrow screen, they are 2

> I'm not sure they fit:

Whilst it's not ideal on very narrow screen widths with 3 columns I think it's the better solution than the alternative which is an ugly layout for medium size screens. So I'm opting for a 3 column layout in the latest push.

**Comment by jrosindell** [comment]
> > For the three boxes 'for everyone' ....
> 
> I did experiment with this a bit, but putting them below the links then ate up a good chunk of screen space on an iPhoneSE size screen needlessly. To not eat up the entire screen with a single "for x" menu, they'd have to be as short as they are narrow in your screenshot.
> 
> Agreed that there should be a cut-off before you end up with such silly views as above.

I played around with this and unfortunately if we tweak the threshold a bit then it looks too silly the other way with three stacked sections each with extremely wide and large images.  So, I think it's best as it is.

**Comment by jrosindell** [comment]
> > on mobile especially there is often too much white space when news items are too short in the carousel compared to some others
> 
> We can't do too much about that, as then the left/right arrows start jumping up and down as the space enlargens and decreases. The best we can do is proper summaries for news items which are roughly the same length.

Agreed - this should be addressed by keeping content to a reasonably uniform size.

**Comment by jrosindell** [comment]
The last point is not fully solved so now it has its own issue which is not essential

#262
