### ISSUE TITLE
Tour controller (was: Tour URL format)

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#244]
After discussion with @jrosindell , we think that the simplest format for a URL for a tour is something like

`www.onezoom.org/life/my_tour`

which can be distinguished from a "normal" geo-located URL because of the lack of `@` sign, i.e. it's not `www.onezoom.org/life/@foo=bar`. This should play nicely with e.g. partner pages, which can be of the form `www.onezoom.org/linnean/my_tour`.

**Comment by lentinj** [comment]
The bulk of this work here will be a Tour (javascript) controller, that can be plumbed into URL state and trigger an update.

The tour controller should also be responsible for the tutorial / screensaver wiring. I'm not sure if there should be some consideration for pre-loading the tutorial. But it's unlikely worth the effort.

**Comment by lentinj** [comment]
The above, after doing a lot of ~unrelated bugfixes, introduces ``controller_tour``. This means I can do e.g. ``onezoom.controller.tour_start('/tour/tutorial_MDmouse')`` from the ``/life`` page.

Next step is to add an option for managing the tour via. URL, as described above.

**Comment by lentinj** [comment]
The above adds a "tour" querystring parameter, which looks like ``tour=/tour/tutorial@2``, where "2" is an optional tourstop number. The URL is parsed well enough that we won't mistake it for the @ in the OTT.

**Comment by lentinj** [comment]
Merged into main with https://github.com/OneZoom/OZtree/pull/639
