### ISSUE TITLE
css issue with location dropdown

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#25]
E.g. go to http://127.0.0.1:8000/life.html/@Coccinella_septempunctata=343294?vis=spiral#x1145,y209,w1.3228 and hit the location bar. The "current location" header is misaligned, as are some of the intermediate groups. It works OK in the museum display. This is to do with 24b529359c2ceb1f18b1368f83c7d1b8ba2b2531.

**Comment by jrosindell** [comment]
This is a replicate of #103 and hence I'm closing here
