### ISSUE TITLE
Advanced search bugs introduced by front page redesign

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#255]
- [x] advanced search mode - when searching and clicking on the drop down menu it doesn't perform the correct function and instead take the user to that place on the tree - it seems to reload the page when clicked on a single species
- [x] advances search search icons to be updated (uses old icons)

**Comment by lentinj** [comment]
There's hooks into the now-common search_ui to disable the link action and do the right thing. Just needs the advanced search overrides putting in the right place.

**Comment by lentinj** [comment]
Spotted a few more problems, also fixed above
