### ISSUE TITLE
IUCN page quick fix

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#269]
we need a quick fix for the conservation pages just in the short term

see #181

we think just a bit of text explaining why it doesn't work - with a link to IUCN instead

**Comment by jrosindell** [comment]
use web2py a helper so that it can be sandboxed later.

This should be edited in tree.py

**Comment by hyanwong** [comment]
You'll need to add a new page to the tree controller like `wikipedia_OZpage()` that only uses the embed.html layout. Unlike` wikipedia_OZpage.html`, for the moment the new `IUCN_OZpage.html` doesn't need to have any major content, merely a message with a link provided by the `A()` helper. This page can replace the `"http://www.iucnredlist.org/details/{}/0"` URL used on line 277 of `tree.py`.
