### ISSUE TITLE
menu bar CSS

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#282]
The menu bar at the top of the page leaves a gap between the main four items, and each sub menu that opens up.  I think this may be because of the large gap left between the top part of the header and the title, but we want that gap to remain.

<img width="484" alt="Untitled" src="https://user-images.githubusercontent.com/3009279/78501294-06e6c780-7753-11ea-9cac-cc1bc18320ac.png">

**Comment by hyanwong** [comment]
Should be fixed with #287
