### ISSUE TITLE
Screenshot tool saves images only with links to web URL

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#328]
The images are not embedded in the SVG itself - this can be seen by opening in e.g. Inkscape or by opening in a browser with internet disconnected and images will not be found

**Comment by hyanwong** [comment]
Confirmed. How did this work again? Does it work on beta?

**Comment by hyanwong** [comment]
Errors in the console?

**Comment by jrosindell** [comment]
Sorted with pushes from me and Yan just now
