### ISSUE TITLE
Minor CSS bug on mobile

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#337]
When the user clicks on the search dialogue from the front page, it opens up and expands off the side of the main page (on mobile use with small phones only).  

See attached screenshot.

![IMG_6026](https://user-images.githubusercontent.com/3009279/80308510-628ef880-87c7-11ea-95ab-8b83ebce66cd.PNG)

**Comment by jrosindell** [comment]
labelling as a priority mostly because it's probably very easy to fix

**Comment by lentinj** [comment]
601ddba should sort this I think.
