### ISSUE TITLE
Performance on Android mobile

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#339]
The front page is very slow slow to load - whilst it's loading it shows a white screen and gives no indication that anything is loading in the background - it looks to the user like something is broken when this happens.  We wonder if this is related to javascript errors.

**Comment by lentinj** [comment]
I think this is a duplicate of #341.  Regardless the home page displays pretty quickly now on the phones to hand, but the tree viewer takes a while to warm up as expected.
