### ISSUE TITLE
Advanced search common ancestor button pointing to wrong place

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#342]
If you put two tree locations into the advanced search and click on the common ancestor it works fine, but if you then change one of the advanced search items for a new one the common ancestor button still takes the user to the old common ancestor instead of the new one which might be different.

For example type swallows into the first box
Then type Swifts in the second box and select (Hepialidae)
Then go into the second box again and select a different group - Swifts (Apodidae)
The click on the common ancestor button - button goes to the wrong place (though the markings do change to the correct new location)

**Comment by lentinj** [comment]
This seems to have been fixed as part of #344 - I've not investigated precisely how the problem was arising, but I guess we don't care that much :)

**Comment by hyanwong** [comment]
Great! Perhaps @jrosindell can test to see if he finds it fixed, then he can close it?

**Comment by jrosindell** [comment]
I've tested this and it's fixed so will close - thanks @lentinj
