### ISSUE TITLE
advanced search sometimes fails to highlight an item

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#344]
If you click on advanced search and select any two places on the tree it all works fine.

If you then click on either search box for one of the items and delete its contents then the highlight disappears (which is also fine)

But... if you re-enter the species that was in there before you deleted the contents the highlight fails to show on the tree

e.g. to repeat click on advanced search
type in human in the top box and select homo sapiens (human highlights and flies there OK)
type gorilla in the bottom box and select western gorilla (western gorilla highlights and flies to common ancestor OK)
then click again on the bottom box and delete the contents (highlight for gorilla disappears OK)
then click for a final time on the bottom box and put western gorilla back in (FAILS to highlight)

**Comment by jrosindell** [comment]
If I select any two places on advanced search, they both highlight OK.

Then I change the second to be the same as the first - so I get only one colour of highlight now to that single place - that's probably an OK behaviour though it might be better if it showed two different colours going to the same place

Next I change the second one back so it's again different from the first - from this point on I get only one colour of highlighting.

**Comment by lentinj** [comment]
This is fixed in the above commits. Basically the treeviewer code was muddling 853411 and the "853411", which the controller wasn't coping with.

I've added explicit errors for this, to make any future mistakes more obvious.

**Comment by hyanwong** [comment]
Fast work, thanks @lentinj !
