### ISSUE TITLE
Auto tweeting not working on production

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#346]
error message said could not auto tweet and cited a missing module in the error message - unfortunately it is not possible to say which now as the message disappeared

**Comment by jrosindell** [comment]
![bug on OZ](https://user-images.githubusercontent.com/3009279/87569861-a9ea9e00-c6bf-11ea-8bd0-5a61858133fb.png)

Here is what appears when tweeting is attempted (twitter handle for individual involved has been removed)

**Comment by hyanwong** [comment]
Oh, right. Do we need to install twython?

**Comment by hyanwong** [comment]
I just installed twython. Does it work now @jrosindell ?

**Comment by jrosindell** [comment]
yes - it works - thanks!
