### ISSUE TITLE
milestones page needs updating 

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#35]
last 'event' was in April 2017 so this needs updating

**Comment by hyanwong** [comment]
Has it been updated on beta?

**Comment by hyanwong** [comment]
We can *probably* transfer the beta milestones page straight into the production site if we want to.

**Comment by jrosindell** [comment]
Correct but actually what I meant was that even the beta version is out of date.  We might as well get beta how we want it then swap as normal I think.  It's more complex to switch than you expect because of the new method of injecting the content into the page that is not on prod

**Comment by jrosindell** [comment]
Done in latest push
