### ISSUE TITLE
Extra URL configuration for embeds to use

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#369]
Make a new public API that accepts ID from IUCN or GBIF or some other system and tells in the response whether there is a OneZoom page on that species, returning OTTid.

Add an instruction page about this API and explaining how to construct a URL for linking to OneZoom using this API and using the OTTid that gets returned.

In a more advanced version we should have a version of OneZoom that's more suitable for embedding - like a map.  It should have some 'activation' method to enable scroll / touch to interact with the map or not.  it should also turn off the tabs as that's iframe within iframe which is not neat.

**Comment by jrosindell** [comment]
1.) enable the path to the selected species to be marked by URL parser
2.) small changes to UI style specifically for embedding 
i) get rid of iframes?
ii) 'press to interact' button that keeps view locked until pressed so that the user can scroll past the onezoom view
iii) full screen button to open in new tab
iv) reduced features (more like the MD)
v) ‘what is this’ button to explain it more
vi) OneZoom logo takes to OneZoom website in new tab rather than in iframe.

**Comment by jrosindell** [comment]
@lentinj if you have time to attempt 1) here would be very helpful - that is.

Enable the path to the selected species to be marked by URL parser.  So we can effectively store the markings of an advanced common ancestor search in the URL.  This way it would be easier to make switching to the polytomy view retain the markings (which it doesn't currently) and we could enable embedding in iframe of a page that has markings already in it from the start - more useful to those wishing to embed.

**Comment by jrosindell** [comment]
This will also need to provide a new API so that e.g. GBIF can see in advance if there is a OneZoom leaf for that GBIF id before they try to embed the tree view.

**Comment by jrosindell** [comment]
OK here are the things I think Jamie could do towards this.

- [ ] upgrade URL parser so that colour scheme can be parsed in
- [ ] add highlighting of a single place to the URL parser
- [ ] have a modifier key and a button to press that enables interaction to be locked / unlocked - it will be locked by default.
- [ ] have a separate page without search or advanced search and with the interaction lock instead

**Comment by jrosindell** [comment]
I think the above list of tasks are all redundant now.... the new plan would be to embed code directly and use an API for data delivery with an API key.  This means that the URL parser and page features will not be the mode of action and instead there should probably be JS and a canvas embedded within the page concerned with some JS controls exposed to select the highlighting at least of a single species and the selection of other options that would have been in the control panel of the tree.  The need for a modifier key / button to lock and unlock free zooming and maybe a button to zoom up to next ancestor would be useful here.

**Comment by jrosindell** [comment]
#518 is an issue that has the attention of a collaborator from a major site that now plans to use the tool so please interact on that issue to help figure out a way to get this working.

**Comment by jrosindell** [comment]
I think it's worth linking to the ticked on the GBIF repo where we're now discussing the approach

https://github.com/gbif/portal16/issues/1711

**Comment by lentinj** [comment]
The above adds "cols" and "initmark" as valid querystring options that do what we want ("cols" was half-added already, interestingly).

**Comment by lentinj** [comment]
Remaining:

- [ ] Keep zoom buttons (responsively based on view height?)
- [ ] Keep info buttons, again based on height, 
- [ ] Disable pinch/zoom modifiers
- [ ] Make OneZoom transparent (incl. setting globalCompositeOperation for ``leaf.bg`` items instead of assuming white)
- [ ] Prompts about ctrl-zoom

**Comment by lentinj** [comment]
Instead of having many tiny on/off qs parameters, the above reduces it to a single "interactivity" setting:

* ``full``: As per full page (search, zoom buttons, pan/zoom events work as per normal)
* ``cooperative``: Default iframe view (no search, only zoom buttons, pan/zoom events work with modifiers)
* ``none``: Disable all input events, search, zoom buttons.

**Comment by lentinj** [comment]
- [ ] The OZ logo is 1 colour, so doesn't work with a black background. Didn't we have one with a white outline for OTOP?

**Comment by lentinj** [comment]
Okay, the interactivity thing was a bad plan, the above dismantles it and puts the iframe behaviour in ``/life`` and makes a ``/life_noninteractive`` for non-interactive embeds. The editor can now pick the page variant used, which in theory would allow it to embed museum displays, e.g.
