### ISSUE TITLE
Colour scheme updates

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#373]
See also #40 and #22 

New colour scheme - includes

- Lighter green for IUCN unknown or NE or DD
- Darker green for IUCN NT and LC
- Grey for Extinct (EW / EX)
- Red (possibly different intensities) for VU / EN / CR

a different colour for branches connecting two randomly resolved nodes and for the randomly resolved nodes themselves.  we may try and make the polytomy uncertainty colour be the same as the leaf uncertainty colour e.g. a blue-grey-green colour of some kind  - for consistency.

In future we could have traffic lights for certainty and include whether the tree is based on genetic data or not.

Beyond this we may also wish to retain original colours, add popularity colours and add a colour blind friendly mode.

For management of the different colour schemes we need to

enable colour selection in the settings and the URL parser
enable colour selection from MD launcher
sort issues with colours in sponsor leaf page code (maybe by parsing the colours in via URL to allow for whatever colour scheme currently active to work).
add interpretation about colours and make changes throughout the site where there colours feature.  E.g. on the front page and as decoration elsewhere.

**Comment by hyanwong** [comment]
For a polytomy (i.e. "fake" node), I don't think we should have the text "The most recent common ancestor to XX species" on the node. We should either have no text (and no ring) or some text that says "this is an artificial node", or similar. In the middle of the picture below is an example of a fake node with 6 species that should probably not be shown
<img width="1116" alt="Screenshot 2021-05-06 at 13 24 25" src="https://user-images.githubusercontent.com/4699014/117297667-650e3e80-ae6e-11eb-87a1-e5d38840ae52.png">

**Comment by hyanwong** [comment]
Also re polytomies, here's a random thought I had for displaying them even in the spiral view. I'm not sure it quite works, but you get the idea:

![image](https://user-images.githubusercontent.com/4699014/117300669-b0761c00-ae71-11eb-98f0-345d082d4c91.png)

**Comment by jrosindell** [comment]
That's very nice.  Thinking about how this works behind the scenes, it may require a bit of tricky geometry to look good.  I think we should save this idea as part of the project to find new view types.

**Comment by jrosindell** [comment]
@lentinj if you have time this is something you could helpfully make a start on.  Specifically enabling new colour schemes to be changed in settings and parsed in the URL, and allowing colour schemes to change the colour of nodes and branches depending on whether they are randomly resolved or not. This is encoded in the tree string information that loads either the polytomy view (which uses only non randomly resolved nodes in the local data structure) or  the normal view - which shows all nodes.  Don't worry about the colours themselves, just getting the mechanism working would be already really helpful

**Comment by jrosindell** [comment]
This is now done with the latest push and merge from colour theme branch.  note that interpretation is still needed - see issue #372
