### ISSUE TITLE
Upload docker version to docker hub and document its use on the README (for the MEE paper)

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#377]
e.g. via Docker

**Comment by hyanwong** [comment]
Now available for building at [https://github.com/OneZoom/OZtree-docker](https://github.com/OneZoom/OZtree-docker). I will push a version to DockerHub once we have tested it. For the moment I'm changing the issue title to reflect this

**Comment by hyanwong** [comment]
Re licensing, the docker image will have the entire OZtree directory present in it (in `/opt/web2py/applications/OZtree`) which will contain the OneZoom license in `license.txt`, so anyone actually looking at the code in the image will hopefully be able to see the licensing terms easily. For that reason, I think all we need to do is to make that clear on the dockerhub image page, and provide a link to the OneZoom licence in the description field of the dockerhub image.

**Comment by jrosindell** [comment]
Agreed.  As a tiny aside I noticed that the license text specifies the version and is slightly out of sync with the actual versioning.

**Comment by hyanwong** [comment]
Another problem is that the docker image currently does not have prices set. That means when  an internal node is clicker, the sponsorship tab lists everything as "Leaves that are only sponsorable by negotiation (email us)". Perhaps we need some generic text there that is not price-specific?

**Comment by hyanwong** [comment]
> Another problem is that the docker image currently does not have prices set. That means when an internal node is clicker, the sponsorship tab only lists "Leaves that are only sponsorable by negotiation (email us)" (because NULL prices currently mean the leaf is not sponsorable). Perhaps we need some generic text there that is not price-specific?

Actually, there's not reason why we shouldn't copy the order_leaves & nodes straight from prod, which will bring the (current) prices with it, so perhaps this is just a question of phrasing in any non-onezoom-hosted site: e.g. "these are estimated donation amounts - please see the main OneZoom page for the latest values".

**Comment by jrosindell** [comment]
I personally think that we don't need the reservations table in the docker image.  I also think we should put a quite prominent label on the readme / documentation reminding users of the docker image that the license does not permit them to host any kind of tree with sponsorable elements, even if it's free, or not for revenue generation, or for non-profit use.

**Comment by jrosindell** [comment]
After discussion just now, Yan and I agreed that including the prices in docker with some non price specific new text would be best - the text should be used only when sponsorship is turned off
