### ISSUE TITLE
Images on leaves not updated when switching to public domain mode 

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#389]
To replicate go to

https://www.onezoom.org/life/@Thylamys_elegans=282403

click on settings
select public domain image sources

The image remains displayed even though it's not marked as public domain in the database

Reload the page and the image disappears now (which is correct) because there is no public domain image on file for this species.

**Comment by lentinj** [comment]
I *think* this is another case of the refresh loop not running so the view doesn't change. Does the above help?

**Comment by lentinj** [comment]
Actually, this isn't the root issue. When this happens on onezoom.org you can still hover over nodes, so refreshing the screen isn't helping. But it does help locally. Even if I throttle the browser's network connection to flush out race conditions.

Any chance this is already fixed and not deployed to onezoom.org?

**Comment by hyanwong** [comment]
Sadly, this does not seem to be already fixed. Perhaps it's a problem when there is no PD image available?

**Comment by lentinj** [comment]
I think I saw this occur for nodes where there was a PD image as well, just didn't change until a refresh.

**Comment by jrosindell** [comment]
I think this bug is very repeatable for the case where there is no public domain image at all but there is an image otherwise e.g. https://www.onezoom.org/life/@Thylamys_elegans=282403
