### ISSUE TITLE
Extra text warning about possible inaccuracy of leaf sponsor prices on non-OZ sites

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#392]
The only valid prices in the order_leaves table are those on the onezoom_prod database. Other copies of the DB (e.g. in the [docker image](https://github.com/OneZoom/OZtree/issues/377) may have old prices. We should check whether or not this OneZoom instance is running with allow_sponsorship = 0 in appconfig.ini, and if so, have an extra para of warning that the prices may not exactly reflect those on the main OneZoom site.

**Comment by jrosindell** [comment]
I think ideally the docker image will just have null in the prices part.  We should also reiterate in the plain text license that use to build your own tree with sponsored leaves is not permitted for any purpose.

**Comment by hyanwong** [comment]
> I think ideally the docker image will just have null in the prices part. We should also reiterate in the plain text license that use to build your own tree with sponsored leaves is not permitted for any purpose.

I'm thinking of if we use the docker image for a museum display. Then we might want to direct users to the main OneZoom website for sponsorship, and if so, knowing the (rough) prices is useful, and it would be used when a user clicks on an internal node in the museum display. If we don't have prices, what should we do here?

More generally, I think that if sponsorship=0 in appconfig.ini, all the sponsorship text should direct people to the main OneZoom website, and having prices for this is not necessarily a bad idea.

**Comment by jrosindell** [comment]
The current museum display sponsorship feature does not tell users the price of the leaf, it gives the QR code and creature code and that's it.  I'm not sure we need to change that given that doing so opens something of a can of worms about sponsorship price consistency. I think the docker should therefore have no prices set and instead explain that sponsorship must be off and give prices on redirect to the official site only.

**Comment by hyanwong** [comment]
I agree that it should not give a price. However, the prices of leaves *are* accessible in the museum display when clicking on an internal node. It would be good to find a solution to this, both for museum displays and for the docker image.

One easy possibility is to label the groupings that are shown in the sponsor_node page

- "Contact us"
- "Very popular (likely most expensive)"
- "Popular (usually expensive)"
- "Reasonably popular (medium price)"
- "Lower popularity (pretty cheap)"
- "Obscure (really cheap)"

Obviously not that exact phrasing though.

**Comment by hyanwong** [comment]
Here's an agreed phrasing:
* Obscure species (likely requiring only a small donation)
* Less well known species
* Regular species
* Well known species
* Charismatic species
* Iconic species (likely requiring the highest level of donation)
* Leaves that are likely to require negotiation to sponsor (email us)
