### ISSUE TITLE
Ways to solicit a username

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#394]
For the public donor page, we decided that we want to use a url of the form

```
/donor/YanWong
```

Where "YanWong" is the (new) `reservations.username` field. By default we would, I think, want to construct this out of the `reservations.verified_donor_name` field, rather than allow the user to define it themselves, so that we are reasonably assured that it's sensible. In other words, we would assign the username under the hood, without any user input. There are a number of issues associated with this (@jrosindell, @lentinj: feel free to edit the notes below):

1. We are currently linking multiple sponsorships to the same person via the `reservations.PP_e_mail` field. What's the logic for integrating this with the `reservations.username` field? My feeling is that we would want to treat the `username` field as canonical, and be able to edit the reservations table by hand so that entries with different `PP_e_mail` entry could still be assigned to the same username. (JL: We're currently using the ``e_mail`` field, not ``PP_e_mail``. However, the renewal page proper could use username, provided we can resolve the given e-mail address to a username).
2. For existing sponsors, we can probably create sensible usernames easily enough, although it needs a little thought. Presumably we would group by `PP_e_mail` then look for any `verified_donor_name` fields and pick one of those at random (although they will probably all the the same) to assign to `reservations.username`, after deleting any non-alphanumeric characters and uniquifying (perhaps by adding 1, 2, 3 etc if necessary). If no `verified_donor_name` exists, we would look for rows with a `verified_name` and a `verified_kind='by'` row and use that instead. I think we should ensure that all valid sponsorships have a valid username - this might be a bit of a hassle to sort out at the start, but would save us from insanity later.
3. For new sponsorships from existing sponsors, we would check if any rows exist with the same `reservations.PP_e_mail` as the email sent to us by PayPal, and if so, use that as the username. This means that the username field is only filled out on hearing back from PayPal, or perhaps, even better, on admin verification of the sponsorship (I guess that's OK though). If the email doesn't match, we create a new one using the same logic in (2.) above.
4. For new sponsorships from new sponsors, we also follow the logic in 2., but if is a `sponsor_for` and there's no donor name, then perhaps we need some way that an admin can create a username during the verification phase.
5. Even if the sponsor does not want their donor page to be public, they have a username, but it's invisible to them and the public more widely.
6. We say on the private "renew" page that if they don't like the username they've been allocated, they can email us, and we'll change it (should be easy to do by hand, using a simple search-and-replace)
7. We need a way to allow sponsors who visit their public donor page to see how they can change their username (by emailing us). One possibility is to say on the public donor page that "if you are the owner of these sponsorships, click here to be sent an email so you can see your renewals or change your username". We would probably need some simple click-through method to avoid spamming donors with emails if someone keep clicking on that link, though.

**Comment by hyanwong** [comment]
If I'm right above, then we'll need to modify the `manage/SPONSOR_UPDATE.load` and/or the `manage/SPONSOR_VALIDATE.html` views to be able to assign a username on validation (presumably auto-filling out the username to save us hassle).

**Comment by jrosindell** [comment]
All agreed, but re. point 7 let's add all the interpretation around e-mailing us to change things into a separate page for managing sponsorships.  This managing sponsorships page should probably be the same page as is used to e-mail yourself a token to manage your sponsorships

**Comment by hyanwong** [comment]
I think we should probably strip accents off names etc to produce the username, and only allow lower+uppercase ascii and digits. E.g. something like this in Python, which would be part of the sponsor_validate logic (i.e. only ever run by an admin, when verifying, and used to populate a "username" field.

```
import string
allowed = string.ascii_lowercase + string.ascii_uppercase + string.digits

# logic here to check if this is a new_email, or instead if email already exists in 
# reservations.e_mail or reservations.PP_e_mail (making sure to exclude any unverified rows)
if new_email:
  name = reservations.donor_name  # here we could also check on sponsor_by names
  username = "".join(c for c in unicodedata.normalize('NFKD', name).encode("ascii", "ignore").decode() if c in allowed)
  if username in reservations.username:
    # uniquify
    while(True):
       newname = name + f"_{i}"
       if newname not in reservations.username:
        username =newname
        break
```

If we have this as a function, I can write a script that uses it to construct names for existing sponsors too.

**Comment by lentinj** [comment]
Your example code / text doesn't allow for underscore (although I think you're expecting to be allowed given ``f"_{i}"``)? Regardless I'd say it's worth allowing, if at every least so you can then simplify down to:

```
>>> unicodedata.normalize('NFKD', re.sub('\W', '_', "Café Culture")).encode('ascii', 'ignore')
b'Cafe_Culture'
```

It'd be worth randomising ``i`` in the final section if you weren't already intending to, e.g. ``random.randint(100, 999)``, rather than incrementing until you find a free one, to reduce the chances of 2 users racing to the same username.

**Comment by hyanwong** [comment]
> Your example code / text doesn't allow for underscore (although I think you're expecting to be allowed given `f"_{i}"`)? 

Yeah, I thought I would ban then apart from at the end, but you're probably right

> ```
> >>> unicodedata.normalize('NFKD', re.sub('\W', '_', "Café Culture")).encode('ascii', 'ignore')
> ```

Does \W only include lc+uc ascii + numbers and underscore then? I wondered if it might be language specific?

> It'd be worth randomising `i` in the final section if you weren't already intending to, e.g. `random.randint(100, 999)`, rather than incrementing until you find a free one, to reduce the chances of 2 users racing to the same username.

I don't think there will be a race, because it's only us setting the username (users can't do so), and only as a way of autocompleting a field on the verification page. So we can double check on verify whether the username already exists.

**Comment by lentinj** [comment]
> Does \W only include lc+uc ascii + numbers and underscore then? I wondered if it might be language specific?

Historically ``\w`` was ``[A-Za-Z0-9_]``, but ~anything nowadays (including Python) will consider any unicode word character to be part of ``\w`` when dealing with unicode strings. In the example above it's only filtering the space.

**Comment by hyanwong** [comment]
So I think we don't want to allow unicode chars in the username (which is why I converted them to ascii) and we probably want to simply remove them all rather than replace with underscores. I think a donor name like "Yan Wong" should give a username of "YanWong". Some other wacky examples from the DB:

"Toby, Caroline & the Gibsons" -> "TobyCarolinetheGibsons" (I guess & could be _ here though)
"Thomas van Diehl" -> "ThomasvanDiehl"
"Sierra Nevada Brewing Co." -> "SierraNevadaBrewingCo"
"SBI3U class of 2016" -> "SBI3Uclassof2016"
"Dr. Griffard's Bio-111" -> "DrGriffardsBio111"
"Rasmus Ø Pedersen" -> "RasmusPedersen" (this is annoying: Ø is not NFKD'ed to O)

**Comment by hyanwong** [comment]
I have code to do this now, but it still only allocates 640 out of 791 sponsorship rows.

The remaining rows are all "sponsored for" and don't have a donor name. We could construct a donor name from the first and last PayPal name, or even the PayPal email, but these are values which aren't public, so if we make the username something that the public can see (e.g. in the URL) we are revealing private information, which I suspect we won't want to do.

**Comment by hyanwong** [comment]
We decided to use the name of one of the sponsored species (maybe plus the year of sponsorship) for cases where we can't deduce a username
