### ISSUE TITLE
Fix incorrect references to private repos.

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#4]
in the ReadMe of OZtree, all references should be "https://github.com/jrosindell/OneZoomPublic" in general there might be incorrect references to the old private repos that need to be checked and replaced.

**Comment by hyanwong** [comment]
grep -r 'OneZoomPublic' applications/OZtree/

**Comment by hyanwong** [comment]
or if you a feeling very brave

`find . -type f -exec perl -i -pe 's/OneZoomPublic/OZtree' {}\;`

DO NOT DO THIS :)

**Comment by jrosindell** [comment]
I slightly worry about even the first option as OneZoomPublic might refer to the app name or the URL of the git repo. I thing we can safely grep for the URL above starting https://github..... and then leave anything else to be fixed by hand using grep only to find locations

**Comment by hyanwong** [comment]
eh? Nothing is in OneZoomPublic any more. Besides which we are only identifying potential files, so false positives are fine. FWIW, the only files that mention `OneZoomPublic` are 

```
applications/OZtree//README.markdown
applications/OZtree//views/dev/DOCS.html
```

**Comment by hyanwong** [comment]
Done with d4a1622a34477f118f6eae5c0e35163e89434e84
