### ISSUE TITLE
How to acquire database dump?

### ISSUE THREAD

**Issue by ocourch** [OneZoom/OZtree#407]
Hi, I'm following the README full installation instructions, and reached the part about emailing an address to get a dump of the database.

I emailed but haven't heard back yet, is there a new way to get the database dump?

Thanks!

**Comment by hyanwong** [comment]
Hi @ocourch - apologies that you didn't get any response to your email. It's possible that it accidentally went into our spam folder.

As it happens, we are in the middle of revising our installation instructions, and we have an docker image pipeline which should make the entire process *much* easier (see https://github.com/OneZoom/OZtree-docker and https://github.com/OneZoom/OZtree/issues/377). I'm just about to build a version with the new OpenTree release 13.4, and after that I'll release the docker image and let you know (should be this weekend).

**Comment by ocourch** [comment]
Oh that sounds great! Thanks!

**Comment by ocourch** [comment]
Hey any update on the expected release date? I'm trying to block out some time to test it out.

**Comment by hyanwong** [comment]
Hi sorry about the slowness. Got caught up in holidays! I'm blocking off some time to do this this weekend.

Yan

**Comment by ocourch** [comment]
Ah not to worry, thanks for letting me know!

**Comment by hyanwong** [comment]
Hi @ocourch: I have uploaded a temporary docker image of OneZoom (version 3.5, development version) to https://we.tl/t-BzYOTmPJug, and it will probably be available for download from there for a week or two. Note the licence etc requirements listed at https://github.com/OneZoom/oztree-docker

You should be able to load the downloaded file into docker with

```
docker load < oztree-noimg.tpxz
```

and run it with e.g.

```
docker run -p 8080:80 -p 3307:3306 --name running_onezoom onezoom/oztree-noimg
```

And then you can access the database on port 3307, and the actual running web instance on http://127.0.0.1/8080

I've just noticed, however, that the higher levels of the eukaryotic tree are out of date (see https://github.com/OneZoom/OZtree/issues/411) so I'll try to revising the higher levels of the tree before the next formal release, which will mean a change in the database values. Also @jrosindell is working on a new set of colours for the branches and leaves, so this is currently a bit of a work in progress. I'll let you know when we formally release the final docker image.

**Comment by hyanwong** [comment]
@ocourch I've created a new docker image with the updated eukaryotic tree and the thumbnail images. Instructions as above. Temporary download at https://we.tl/t-MFWTKebQkg

**Comment by hyanwong** [comment]
The docker image is now up at https://hub.docker.com/r/onezoom/oztree-complete
