### ISSUE TITLE
Error: Can't find color interior.copyright.text.fill. Please make sure that you've defined interior.copyright.text.fill

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#42]
title speaks for itself, just recording during testing. I'll go and add some colours to the themes to resolve this.  It occurs in AT colour mode so might be related to that.

**Comment by hyanwong** [comment]
I am hitting this again e.g. when using "popularity view" in the partial-install version (treeviewer/minlife.html). Can we please solve it?

**Comment by hyanwong** [comment]
Corrected with 5622ced4a1be652624b1801c376c67bbcc8b9a38
