### ISSUE TITLE
Polytomy view bug

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#437]
If I zoom into Holozoa and move off the screen to the right the node disappears before it's off screen.  The same is not true for all other nodes. I think this is symptomatic of the horizon calculation code not taking into account the size of the node itself .

**Comment by lentinj** [comment]
We only render an interior node if all it's children are visible (i.e. their bounding boxes are on-screen):

https://github.com/OneZoom/OZtree/blob/3929f585b19ac259ca1637bc153872d083b4b94a/OZprivate/rawJS/OZTreeModule/src/projection/shape_manager.js#L74-L82

The above adds the parent's interior node radius to the bounding box, so a node's bounding box includes the whole of the parent interior node, not just the end of the line.

I've also made the bounding box debug enablable at run-time, so you can put in the javascript console, for example:-

    onezoom.config.debug_bounding_box = 0x03
    onezoom.config.debug_bounding_box = node => node.latin_name === 'Holozoa' ? 0x03 : 0
    onezoom.config.debug_bounding_box = node => node.upnode && node.upnode.latin_name === 'Holozoa' ? 0x03 : 0
