### ISSUE TITLE
Zooming in to "Ploceus_philippinus" without an OTT takes you to slightly the wrong place

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#445]
Compare

https://www.onezoom.org/life/@Ploceus_philippinus

with the version with the OTT:

https://www.onezoom.org/life/@Ploceus_philippinus=865477

In the first case, the current version of OneZoom takes you to near the 4-tip node 898759 instead. That's a bit odd, and could do with investigating.

**Comment by hyanwong** [comment]
It turns out to be a pain, because we provide links like this without an OTT ID to sponsors. So it would be nice to fix this. It *used* to work, weirdly

**Comment by lentinj** [comment]
https://onezoom.org/life/@Lentinus_tigrinus also suffers with this, but interestingly https://www.onezoom.org/life/@Lentinus_tigrinus=685638 does not. I'm guessing this is a good lead on what's going wrong.

**Comment by lentinj** [comment]
The above should sort matters. This was the nub of the issue:

```
$ curl 'https://www.onezoom.org/API/search_init.json?ott=5299806&name=Lentinus_fasciatus' ; echo
{"ids":[-594430]}
$ curl 'https://www.onezoom.org/API/search_init.json?name=Lentinus_fasciatus' ; echo
{"ids":[594430]}
```

I don't think ``search_init`` is used anywhere else, so I don't think there could have been anything depending on this behaviour.

**Comment by hyanwong** [comment]
Oh, *well done*. I think we were using negative numbers for leaf ids and positive for nodes, right?

**Comment by lentinj** [comment]
> Oh, well done. I think we were using negative numbers for leaf ids and positive for nodes, right?

It's the convention in tree-viewer land at least. I'm guessing there's not so much need server-side.
