### ISSUE TITLE
Screenshot tool does not work (used to read only works on Safari but now fully broken)

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#463]
The screenshot tool button to take a screenshot only does anything on Safari.

It's quite an important feature and cross browser support is worth having

**Comment by jrosindell** [comment]
Update - I just tested it and it doesn't even work in Safari now.

I think this is something that's worth fixing because people do use screenshots.

I also think that it could be valuable to have a screencast tool that records a flight from one place to another with the buttons hidden and public domain images turned off.  I'm not sure if there are packages out there to achieve this and how much work it would be to make one.

Still, it's true that I get requests for these kind of materials on a fairly regular basis so it would be nice to have solutions for it.

**Comment by hyanwong** [comment]
We need to add this to the unit testing somehow, right?

**Comment by davidebbo** [comment]
I just tried the screenshot tool on Chrome (MacOS), and it also seems broken. So maybe it's a general issue, and not Safari specific?

Specifically, what I tried is:
- Go to https://www.onezoom.org/life_expert.html
- Click on the camera icon

And nothing happens.

It may be related to [this](https://ourcodeworld.com/articles/read/682/what-does-the-not-allowed-to-navigate-top-frame-to-data-url-javascript-exception-means-in-google-chrome), and to [this OneZoom logic](https://github.com/OneZoom/OZtree/blob/d57da635fa5cd5084c769b2822ebc40831f41cbf/views/treeviewer/life_expert.html#L72-L74) used to download the file (which apparently is no longer allowed).

**Comment by jrosindell** [comment]
I've been playing with the site again and noticed that the screenshot tool doesn't even work on Safari now.  This might be an important one to fix  because it's related to third party update of using OneZoom for things....

**Comment by jrosindell** [comment]
@lentinj I'm mentioning this to you as it could form part of a non tours day potentially....

**Comment by jrosindell** [comment]
This is still a nice to have, it's more important to finish the tours and make them excellent though....
