### ISSUE TITLE
Sponsorship fails to open PayPal 

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#468]
This has happened (and been reported) many times.  Here is perhaps the most useful feedback we've got on why...

"I was able to perform the donation when I filled out the form when it was not in pop-up mode, but simply in my webbrowser (Firefox 95.0.2)."

I think there is an issue with opening a new tab from within an iframe.

I think we need to have a broader discussion about how to solve failed sponsorship attempts prior the making the PP donation itself.  There will be a separate issue about the pipeline post PP donation.

**Comment by jrosindell** [comment]
From more e-mails received about this I think it's related to popup blocking.  I wonder if the fix will be as simple as making PayPal open but not in a new tab.

**Comment by lentinj** [comment]
For the new window to not be blocked, it needs to happen as part of the form submit action. But to validate the form we need to ask the server, and by the time it responds we're no longer happening within the user interaction, so any pop-up is considered automatic and blocked. However, we have to have PayPal in it's own window to function.

There may be a subtle sleight-of-hand I've missed but if there is it's potentially a loophole that will get closed in the future. The simple answer will be both PayPal and validation errors to appear in a new window after clicking Submit. Makes the flow a bit uglier, but at least works.

**Comment by lentinj** [comment]
Right. The above feels like a bit of a cheat, but as above I don't think there's any easy answers here to preserve the previous desired behaviour.

**Comment by hyanwong** [comment]
Right - that's why we did it like that previously: so the form was in the same window. But you're right: better to simply open the validation error in a new window as well. We were probably trying to be too clever.

**Comment by hyanwong** [comment]
Closing as we think this is fixed, and we have tested it a few times
