### ISSUE TITLE
Automatic emails come from mailonezoom@gmail.com, not mail@onezoom.org

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#478]
It would be nice to change the sender settings so that even though we send through gmail, it appears to be from the main address. Can we just change the email in appconfig.ini, or will this confuse the mail sender? Here's what we have ATM:

```
[smtp]
autosend_email = 1
server = smtp.gmail.com:587
sender = mailonezoom@gmail.com
login  = mailonezoom@gmail.com:MYPASSWD
```

can we just change the sender line do you think, @lentinj ?

**Comment by lentinj** [comment]
I'm not sure of the ins and outs of gmail, but unless gmail already knows that's a valid sender for your account (e.g. you've already configured it so you can send e-mails from the web UI as "from onezoom.org"), then I suspect it will refuse to send e-mail.

In general you may also have to configure DKIM (verifies the sender by making comparing the signature they added to one available via DNS) / SPF (a list of valid senders for a given domain), but I don't think these are turned on here.

**Comment by hyanwong** [comment]
I send mine through gmail from yan@pixie.org.uk, but I have configured it. This is probably one for @jrosindell to sort first then.

**Comment by hyanwong** [comment]
I've changed the email in appconfig, and verified that it works by sponsoring something myself.
