### ISSUE TITLE
Renewal does not save correct information in reservations table.

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#520]
After renewal PayPal worked OK and relevant row(s) got moved from reservations to expired BUT the new row in the reservations table only had the PayPal and expiry information - none of the personal and sponsorship information that would be needed for this sponsorship system to still work was copied across.

**Comment by lentinj** [comment]
Okay, I think this broke in eceb5314d6e88e0d375e7270c1f8c3b4e54c9e70, before we check r.prev_reservation_id which is will be set for both expire-repurchase and extensions. prev_row, on the other hand, isn't.

Anyway. The above should sort things, and add some tests that notice this.
