### ISSUE TITLE
Recovering half finished sponsorships that went wrong

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#524]
I think that the detailed entered into a sponsorship form and validated but not paid for should be saved in the database for a lot longer before releasing the leaf again.  We're not overrun with people reserving things and I think that's a much better experience for the person reserving to know they have longer in case something happens. Connected with this I also wanted to check that even when it is released again for sponsorship it will only wipe that row of the reservations table when another person fills out and submits a validated form.

**Comment by lentinj** [comment]
> I think that the detailed entered into a sponsorship form and validated but not paid for should be saved in the database for a lot longer before releasing the leaf again.

We already do, if I'm understanding the question:

https://github.com/OneZoom/OZtree/blob/3929f585b19ac259ca1637bc153872d083b4b94a/modules/sponsorship.py#L29-L36

The former applies if I've clicked on the sponsor tab, but proceeded no further. The latter applies if I've (in theory) got as far as PayPal but the payment didn't come through. So we have 2 days to work this out.
