### ISSUE TITLE
Systematic embedding of many species

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#526]
We need to allow people to programmatically embed species, which may or may not exist.

Add some indirection so the embed code can:

* Embed via. another ID which is looked up in the onezoom DB, e.g. GBIF
* Hide the treeviewer if there's no associated OTT in OneZoom, rather than displaying an error

**Comment by lentinj** [comment]
From the desk of @jrosindell:

> OK here's the decision from a discussion with Yan - we'll provide 3 options.....
> 1.) plain text link that says the latin and vernacular name explore on OneZoom etc,
later this option may have a graphical teaser designed by Matt but not for now
> 2.) a static iframe of the requested settings and dimensions that is not interactive and consumes no resources after its initial load - it acts as as link to open a full tree with those settings in a new tab
> 3.) like 2.) but with an option to interact with it - still no settings or search or advanced search, or leaf link outs - just explore freely and zoom out to ancestors / zoom back in to the pre defined focus.

**Comment by lentinj** [comment]
A basic example of using getOTT with an embed might be:

```
<iframe id="oz_iframe" style="border: 1px solid black; padding: 2px; width: 600px; height: 400px" src="javascript:"></iframe>

<script>
const oz_origin = 'https://onezoom.org';
const oz_embed_url = ott => `${oz_origin}/life/@${ott}?otthome=${ott}&initmark=1028837&img=best_any&init=leap&vis=natural&cols=IUCN&embedkey=054eb6e3-acf9-4c1d-bcd3-87834299d6e5`;

let gbif_code = window.location.search.match(/gbif=([0-9]+)/);
if (gbif_code) gbif_code = parseInt(gbif_code[1]);

window.fetch(`${oz_origin}/API/getOTT.json?gbif=${gbif_code}`).then(x=>x.json()).then(function (data) {
    const ott = (data.data.gbif || {})[gbif_code];

    if (ott) {
        document.getElementById('oz_iframe').src = oz_embed_url(ott);
    }
});
</script>
```

Then going to ``/embed_test.html?gbif=3221736``. It's obviously not as simple as it could be to implement, a simpler option would be a search endpoint that either redirects to the equivalent ``/life/`` URL or returns an empty page, but then there's always an OZ-sized chunk of the page used up you can't do much about.

**Comment by hyanwong** [comment]
Yes, do feel free to rethink it entirely!
