### ISSUE TITLE
Embed page corrections

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#531]
- [x] When I select locations from the drop down menus for marking and home places the text box does not display what I selected, this makes me feel that the selection isn't really recorded
- [x] When I make changes, the page loads with the all life view showing for a moment before it positions on the correct location with a jump

**Comment by lentinj** [comment]
> When I select locations from the drop down menus for marking and home places the text box does not display what I selected, this makes me feel that the selection isn't really recorded

It should do, for exactly this reason. What browser are you using? It's working locally.

It's stretching the seams of what the search dropdown was intended for though, and it shows. I'll add a highlight for the currently selected item too, possibly a "previously selected items" section (abusing the "popular places").

**Comment by jrosindell** [comment]
I've done a bit more digging into this issue. It only happens for nodes that have a Latin name but no vernacular name e.g. Eleutherozoa or Nepenthes

**Comment by lentinj** [comment]
Ah, that makes it obvious then. Guess what I copy into the search field :)

**Comment by jrosindell** [comment]
> > When I select locations from the drop down menus for marking and home places the text box does not display what I selected, this makes me feel that the selection isn't really recorded
> 
> It should do, for exactly this reason. What browser are you using? It's working locally.
> 
> It's stretching the seams of what the search dropdown was intended for though, and it shows. I'll add a highlight for the currently selected item too, possibly a "previously selected items" section (abusing the "popular places").

You could have a prominent bit of text underneath the box to confirm what's selected.

**Comment by lentinj** [comment]
> When I select locations from the drop down menus for marking and home places the text box does not display what I selected, this makes me feel that the selection isn't really recorded

Sorted with [308552a](https://github.com/OneZoom/OZtree/commit/308552a7c6fd223f6f3b4a9f1ffca1411f37f40e), as a bonus [cb48c18](https://github.com/OneZoom/OZtree/commit/cb48c18c4ab026cd33862be951f0e07ae949683e) lets you click on the latin name

> When I make changes, the page loads with the all life view showing for a moment before it positions on the correct location with a jump

Sorted with [d34fdb0](https://github.com/OneZoom/OZtree/commit/d34fdb0f913bc9f143103bd45d715f06432a3123). Basically we need to be careful when the first ``trigger_refresh_loop`` is called, if it's before we've moved to the starting point then we show the tree root briefly.

Another bonus, [50e55ee](https://github.com/OneZoom/OZtree/commit/50e55ee14a0b07dfd64b2fb10713b99e44edbc92) simplifies tree switching a bit.
