### ISSUE TITLE
Audio narration for tours

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#534]
Narration is an [embedded audio player for a TourStop](https://github.com/OneZoom/OZtree/issues/535), with somewhat different rules:

* An invisible audio widget in a tourstop dialog, starts playing as soon as the tourstop appears
* Continues to play as the next transition starts, unlike "sound" above.
* Don't display next tourstop until audio finishes (obviously the theory will be that they'll be timed so this doesn't happen).
* Pause / play buttons for tour also work for narration audio

The main wrinkle here is we run the risk of falling foul of autoplay rules. Basically if we start playing audio before there's been a
click on the page, the browser may ignore us. This is something we just have to live with though, and/or explain to museum
display-types how to disable.

**Comment by lentinj** [comment]
NB: [Autoplay shouldn't be a problem, so long as there is an intial click](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide).

This may get problematic with [tours triggered by URL](https://github.com/OneZoom/OZtree/issues/244), but that's more work-aroundable.

**Comment by lentinj** [comment]
We can use [MutationObservers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to trigger autoplay events via. CSS state classes.

**Comment by lentinj** [comment]
Do we want to support audio subtitles during narration? Or rely on the tourstops itself?

https://developer.mozilla.org/en-US/docs/Web/API/TextTrack

**Comment by lentinj** [comment]
Assuming the remaining tasks in #535 work out, I'm not entirely sure what will be left to do here. I think it'd cover everything you'd want to do for a narration.

We decided elsewhere that trying to sync a continuous stream of A/V to a tour is not worth the bother vs. playing separate chunks of A/V for a tourstop.

Invisible audio tourstops would be possible, but seems like a bad idea for accessibility reasons; we need some alternative text (which would be far easier to arrange than actual subtitles), and we need a home for tour controls.

**Comment by jrosindell** [comment]
All agreed and sounds good. It's most elegant to just treat it as another embedded thing that's chunked by tour stop. Alt text will be needed but I guess that same applies to other kinds of assets in tours e.g. images should have an alt text for accessibility really. Probably we can close the issue then.
