### ISSUE TITLE
Tours list showing nearby / previously started tours

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#538]
Show a menu of suggested tours, in order of:-

* Tours with a tourstop on-screen
* Tours that you haven't finished
* Hard-coded tours, e.g. "How to use"
* Tours relevant to the current clade (? see below)
* Everything else (we're going to have ~10 tours initially)

...the top-most tour is "promoted" below the tours menu item so you don't have to open the pop-up to get at it.

We may want to promote the "how to use tour" to the top initially, then let it drop down the rankings as people seem to know what to do.

@jrosindell I think there was brief mention of assigning a tour to a clade, e.g. a "flightless birds" tour might be presented when near the "Birds" node. Correct? For this I think we'd need add a list of related OTTs for that tour which aren't themselves tourstops, but cause the tour to be shown when that OTT is on-screen.

on-screen is a bit of a wobbly concept too, and might need tweaking to get right.

~~We do it as part of node_detail calls, saying whether we have tours mentioning this, then the client manages the display of these when the nodes are visible~~

**Comment by jrosindell** [comment]
I think that having a list of OTT IDs that aren't tour stops is the correct solution. Rather like key words to cover things not obvious in the abstract / title of an article.  on screen is wobbly and could get messy to code up but is probably needed.  Instinct says that it should be tied to the placement of flags as that makes it simple - if a tour stop has a flag on screen (or a key-word OTT would be drawn as a flag if it were a tour stop) then this counts - otherwise not.  Hence the same system can be co-opted for on screen tours as chooses to draw flags or not.

**Comment by lentinj** [comment]
Okay, so the "Birds" node should have a tours icon and offer "flightless birds" in it's list of tours, just as it would if "birds" was a tourstop in the tour?

>  on screen is wobbly

Yes, I think our concept of on-screen will end up more broad than a user might expect, but that's probably not a bad thing.

**Comment by lentinj** [comment]
@hyanwong [we decided that tours have an image_url, not src/src_id](https://github.com/OneZoom/OZtree/issues/536#issuecomment-1131895777), but I'm guessing that providing a manually-sourced image for every single tour will get boring very quickly.

We could have src/src_id fields for a tour, but I'm wondering if inventing a url scheme like ``src:99:32373704`` and using that in ``image_url`` makes more sense. However:

* Have we already invented something similar, and am I re-inventing the wheel in a slightly different colour?
* Is something like ``src:99:32373704`` sensible to store, long term?

**Comment by hyanwong** [comment]
We should be able to access images via their source + source_id using the `local_pic_path` function within web2py (defined in db.py), I think.

**Comment by hyanwong** [comment]
I assume you might want a javascript equivalent, and I think I coded one up somewhere?

**Comment by lentinj** [comment]
``local_pic_path`` isn't quite what I want, it's the fitting the 2 src parts into a single URL-scheme-ish string I'm after. This is what I'm currently doing:

```{python}
def url(s):
    thumb_base_url = current.globalenv['thumb_base_url']

    if s.startswith('src:'):
        parts = s.split(':')
        return thumb_url(thumb_base_url, parts[1], parts[2])
    return s
```

> I assume you might want a javascript equivalent, and I think I coded one up somewhere?

Just python, but I think you're thinking of [thumb_url](https://github.com/OneZoom/OZtree/blob/main/modules/img.py#L29), as wrapped above.

**Comment by hyanwong** [comment]
Ah, I see, you mean you simply want to store a string which can be broken down in that way. We haven't invented anything, no. `src:99:32373704` seems fine, or maybe `img:99:32373704`, since we are specifically talking about images here, right?

**Comment by lentinj** [comment]
> since we are specifically talking about images here, right?

Yup.

I think I prefer ``src:`` over ``img:``, since the image-ness of this is pretty obvious in context, but the fact that the 2 numbers are src/src_id isn't.

This is a pretty tiny thing to quibble over though. Maybe ``imgsrc:99:32373704`` and everyone's happy?

**Comment by hyanwong** [comment]
Sure - sounds good to me.

**Comment by lentinj** [comment]
This is done at this point, apart from previously explored tours which can happen with #690
