### ISSUE TITLE
Museum display launch page

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#54]
There should be a basic page that enables museums to configure and then launch their displays.

This page should include basic terms of use for the museums, and the bullet point list of instructions #53.

Furthermore this page should include the user settings that are to be URL parsed in #47 In the ideal world it too would contain a simple search to find places to add as your list of popular places.

**Comment by jrosindell** [comment]
We won't help them find the OTTids - that's too fancy and a waste of time.
There should be a contact us button on that launch page with carefully thought out text e.g. give feedback, let us know you're using it etc.

**Comment by jrosindell** [comment]
Probably there should be a new launch page that is linked from the main page about museum displays.  In the initial implementation we won't need full URL parse of all the options for a display, but probably will want screensaver speed / wait times to be there somewhere.

**Comment by hyanwong** [comment]
I'm putting together an "education" part of the site - this launch page is an obvious addition. Will add in a few days.

**Comment by jrosindell** [comment]
We should record the key parameters that are URL parsed and selected from the launch page.

1. View type 
2. Screensaver wait time

The page should be quite basic - but it should be functional.  We can embellish it later with text to explain about the display software.  We don't need to job to include content creation.

**Comment by hyanwong** [comment]
@windwalker - I have made a very rough template for the education page on the branch labelled "education-functions". Perhaps you could build off this branch? 

The "education" page is in a different controller, at https://github.com/OneZoom/OZtree/blob/education-functions/controllers/education.py which simply provides links to e.g. https://github.com/OneZoom/OZtree/blob/education-functions/views/education/museum_display_setup.html - perhaps you could tweak this view to be the MD launch page?

**Comment by kz12** [comment]
I've made a basic page in which user could config the six options that James commented. 

However, I don't know what URL base should I use. If there exist an OneZoom URL used specifically for Museum Display already? Or is it using onezoom.org/life? 

James said that the page should include terms of use and include partial installation bullet point, is it still needed?

<img width="767" alt="Screen Shot 2019-08-06 at 2 55 18 PM" src="https://user-images.githubusercontent.com/3263319/62517593-4b376600-b85a-11e9-93f3-895f642cb508.png">

**Comment by hyanwong** [comment]
The setup pages can all go in the `/education` controller, which is only on the git branch labelled "education-functions" - so if you create your branch off that, it would be helpful.

However, the setup pages can *link* to `onezoom.org/life_MD` (i.e. not in the education controller)

**Comment by jrosindell** [comment]
This is basically done now.  Only the screensaver timer selected data is not read from the parsed URL.  This should be done, also if that URL arg is absent then there should be no screensaver (across all OneZoom life pages)
