### ISSUE TITLE
Ability to add tours to popular places

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#545]
- [x] There's already a ``tour_identfier`` in the tree_startpoint table, modify the home page so it can work with tours being populated here instead of OTTs.

- [x] Tours can have a thumbnail href field, a OneZoom image URL could be copy-pasted here and would be relatively stable ~~but it would be nicer if we just had a "Give me a public domain image for this OTT" API call. Using public domain would be better, as you don't have to worry about how to display some attribution image (which you can't pass in along with the image). We don't show attribution in popular places anyway.~~

~~Ideally we need a means to let users add their own images, but adding an image upload service to onezoom is a bit out-of-scope. Maybe we can teach people to upload to wikimedia and/or hotlink from dropbox (Adding ``raw=1`` lets you hotlink, an editor could do this automagically).~~

We should have a ``thumbnail_href``, but the nature of image links is discussed here and is a more general problem. https://github.com/OneZoom/OZtree/issues/601

**Comment by jrosindell** [comment]
> Ideally we need a means to let users add their own images, but adding an image upload service to onezoom is a bit out-of-scope. Maybe we can teach people to upload to wikimedia and/or hotlink from dropbox (Adding `raw=1` lets you hotlink, an editor could do this automagically).

Could we consider a very simple upload service open only to managers?  Or, alternatively let the assets be kept in the tours repository but in a format that's easy to use later in case we do add an uploading system

**Comment by jrosindell** [comment]
Note the related discussion in #601
