### ISSUE TITLE
Intelligent tutorial

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#55]
when a new user comes along....

1.) tells them about the tree of life with a bit of text at the start - maybe this text is being revealed at a comfortable pace for reading or maybe it's always present

2.) indicate to them immediately what they can do and don't overload them with options

3.) if they start to explore the tree but don't figure out how to zoom pop up, use two fingers and pinch together to zoom out, move your fingers apart from each other to zoom in.

4.) If they've zoomed in a long way and got to a leaf or node of the tree indicate to them to buttons that will zoom them back out e.g. ancestor button, or compass position tool.

5.) If they've been exploring for a while without using search pop up 'can we help you find what you're looking for? You can type into the search box' or something similar.

6.) Red leaves are species threatened with extinction - we should say this when red leaves appear and are sufficiently large or at least tell the user about it in the introduction.

In general factor in as much as possible of helpful pointers to get people to see a sensible number of ways forward for exploring the tree at any time.  The principle I'd apply would be that at all times the user must see a relatively small number of possible next actions, and that none of those next actions should yield an uninteresting result.

**Comment by jrosindell** [comment]
The help page is rather poor at the moment, and needs some work. Ideally we would also have popups in the UI which showed users how to use it, as a form of tutorial.

**Comment by lentinj** [comment]
Is there target screen size(s) for museum displays?

Defaulting to explore, rather than forcing users through a many-step tutorial definitely seems like the way to go. Especially given the screensaver will be demonstrating the rough structure of the tree already. The text in (1) could also be visible for the screensaver.

For (3) I'd be tempted to keep zoom in/out buttons on screen and concentrate on those. Users comfortable with pinch-to-zoom will just do it, and we don't confuse if the hardware (or hands) aren't capable of detecting the gesture. Then the prompts for can be gently highlighting the zoom in, zoom out, search buttons in turn if nothing is happening, which covers (5). If highlighting each of these a few times doesn't result in any activity, then back to the screensaver.

**Comment by hyanwong** [comment]
I'll let @jrosindell answer the size question (the one in Oxford with DeepZoom on is large).

Agree with defaulting to "explore"

**Comment by jrosindell** [comment]
In terms of resolution almost all reasonably priced hardware in this space is full HD resolution.  I think the minimum screen size we could expect is 23 inch, at events we use a 27 inch monitor, I expect some venues may have up to 50 inches.

I do agree with your point about encouraging exploration, but also we want to know when they are getting frustrated and give them pointers e.g. 'can we help you find what you are looking for' to highlight search if they use the screen for a while without using that option.

**Comment by hyanwong** [comment]
A very easy help layer "overlay" could be made as a first attempt, something like the one at e.g. 

https://dnaskittle.com/browse/homo/sapiens/hg19/chrY/?graphs=bn&start=1468365&scale=1&width=105&annotation=gencode

(see "Close this help overlay")

**Comment by jrosindell** [comment]
For the September launch of the new display I think it would be nice to at least do this...

> If you can add some movement when it's idle that would be great. Also maybe jazz up the Sponsor screen with an image or something.

**Comment by jrosindell** [comment]
#19 is relevant for the above comment.

The tutorial should use the commands to zoom around the tree.  There should be an easy way to get out of it if it's annoying and an easy way to get back in (e.g. a prominent 'tutorial' button) probably spelt out rather than as a symbol only

**Comment by jrosindell** [comment]
An idea for the future would be some kind of information display that pops up e.g. if there is a threatened species on screen (red leaf)

**Comment by jrosindell** [comment]
for the first issue of this maybe a simple slideshow with a button to view it again would be best. Also the how to use info should be integrated in the screensaver

**Comment by lentinj** [comment]
> the how to use info should be integrated in the screensaver

Integrated as in there's a "how to use" button on-screen and relatively obvious, or the screensaver is an elongated version of the slideshow (e.g. by zooming in and out of several nodes before we display the tutorial content for that location).

**Comment by jrosindell** [comment]
As an initial solution we've implemented a basic tour that acts as a tutorial.

**Comment by jrosindell** [comment]
Outstanding things with this are 

- [ ] getting some feedback on the content of the tutorial 
- [ ] jazzing up with images for clarity / interest (maybe)
- [ ] jumping to new locations in a tour does not pre-cache data - this is a bit strange but as Kai has pointed out this relates to the jump function and really we'd need to make a design decision for the whole site as to whether we load before jumping.  On reflection I think that this is a good idea to change.
- [ ] There is an unwelcome jerk in the dynamics when at the end of a zoom to a location we then jump to the same location. This should be fixed either by getting perfect line up of the dynamics or by remembering the last OTTid moved to and cancelling the jump if that OTT is the same as the location.

**Comment by hyanwong** [comment]
I think this can now be closed, @jrosindell. What do you think?
