### ISSUE TITLE
sponsor_thanks page is badly worded for renewals

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#555]
When I renew, after going through the PayPal steps, I get redirected to a page that looks like this:
<img width="1193" alt="Screenshot 2022-05-20 at 19 46 06" src="https://user-images.githubusercontent.com/4699014/169593140-38e55fc4-4aba-42b5-a4b4-035aff7a0b59.png">

If it's a renewal, it should appear on the tree immediately, so there's no need to say "after a couple of days" in the text, I think.

**Comment by jrosindell** [comment]
Proposed new text to use if it's a renewal.

Title: "Thank you for continuing to support OneZoom by renewing your sponsorship"

Text: "Your donations help us in our aim to provide easy access to scientific knowledge about biodiversity and evolution, and raise awareness about the variety of life on earth together with the need to conserve it."

I think it's OK to leave it at this for now.  Again, I think this may be a simple thing for @lentinj to look at

**Comment by lentinj** [comment]
Okay, that adds just enough so we know that it's a renew and we should use different text.

Possibly we should be being more enthusiastic here, if the sponsor_thanks page knew about the basket_code / OTT list of what got sponsored, it could say if it's on the tree, waiting, etc. and give some links.

**Comment by lentinj** [comment]
Closing in preference to #592
