### ISSUE TITLE
renewals page e-mail address entry bug

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#599]
If I go to 

https://www.onezoom.org/sponsor_user_manage.html

and enter my e-mail it does not work - i.e. it does not send an e-mail.

If I enter what I know to be my username - then it does work and send me an e-mail with the necessary details in it.

**Comment by hyanwong** [comment]
This is a great one for @lentinj to fix in his upcoming sprint.

**Comment by lentinj** [comment]
Is "my" specifically @jrosindell 's e-mail address, or a generally?

**Comment by jrosindell** [comment]
to be specific jrosindell@gmail.com does not work but JamesRosindell does at https://www.onezoom.org/sponsor_user_manage.html 

I go here....

https://www.onezoom.org/manage/SHOW_RENEWAL_INFO

it now says "many users associated with the e-mail address jrosindell@gmail.com" which is obviously a massive clue!

The problem is that it's probably common that the usernames are a bit mixed up like this so I wonder if the correct behaviour should be to send an e-mail separately for every username and to append to the e-mail 

"The e-mail you entered has been associated with multiple usernames on OneZoom. We tried to set usernames automatically based on the e-mails people used but for some people it's not so clear how to do this in all cases because each sponsorship has both the e-mail address (optionally) entered into the sponsorship form, and the e-mail address used by PayPal to make the donation. So, if you've made a lot of donations with different e-mails and the same PayPal account, or with the same e-mail but different PayPal accounts then that may be why.  If you're happy with things as they are that's fine, but if you want to change your username or amalgamate your sponsorships into one place please respond to this e-mail and we'll get that sorted for you."

**Comment by jrosindell** [comment]
I noticed that Echinopsis candicans and Cucumis humifructus had just a blank string (not null) for the username and so did Hippocampus bargibanti - not sure why that data error occurred but after fixing it the problem no longer happens.

**Comment by jrosindell** [comment]
I think this is actually fixed now so there was not a problem.  I'm closing the issue
