### ISSUE TITLE
Pause / resume tour edge cases

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#605]
If you pause a tour by moving the tree, then skip forward/back, it's not clearing the paused state, leading to a half-paused inconsistent state.

**Comment by jrosindell** [comment]
I think this would be handled as a UI issue later.  If we want to stop this then we'll just make sure the UI does not permit those actions. OTOH I do wonder if this is also fine e.g. winding a video whilst still on play vs. winding a video whilst on pause are two different kinds of action for difference user intentions and one could imagine wanting the same for a tour.  We've lined up the UI and graphic design project to take place during this year so best not to tie ourselves down to specific choices just yet.

**Comment by lentinj** [comment]
https://github.com/OneZoom/OZtree/commit/1eba8173923e8f86dd4cee81cd2d926ab2e6492e is a fun semi-related bug. Interactions with the tree will generally stop flights, and tours listen to interactions and pause itself too. However, window resizes weren't on the list, so a window resize in a tourstop transition would get stuck, as the tour isn't aware the flight has stopped.

Adding ``window_size_change`` to the list of interactions for the most part solves this, however it's impossible to block a window resize we can with clicks. If your tour's interaction is set to "block_on_flight", and you take advantage of this by hiding tourstops in transitions, the resizing the window will stop the flight and tour, with nothing visible on-screen. I'm not sure what the solution is here. Possibly "don't do that", and always have something on-screen.

One option could be that we don't listen for window resizes, and instead of the commit's backstop of making sure the tour is paused, immediately leap to the next stop when the flight failed and the tour isn't paused. We could also restart the flight in this situation, but I'm a bit wary that immediately restarting a flight that got cancelled somehow will reveal edge cases of why it was cancelled.

**Comment by lentinj** [comment]
The original issue here should be solved with the above, whenever we poke a tourstop we also assume that the tour itself is in PLAYING state, even if it wasn't before. We don't explicitly resume the tour, since that will invoke machinations to replay tourstops which we've already done by advancing / rewinding.

We don't really have any notion of going to a tourstop without "playing" (e.g. starting video or timer to advance to next tourstop), and I'm not convinced it's what you mean by pressing forward/back on a paused tourstop.

**Comment by lentinj** [comment]
I think the obvious bugs that pause/resume had have been solved now, but I'll leave this open for a bit to highlight more philosophical UI concerns:

* As above, is resuming when "Skip" is pressed on a paused stop reasonable?
* How much should be we pause / resume on pause/resume?
* Flights definitely should pause / resume
* Stop timers should ideally pause / resume (currently we restart from the beginning)
* Videos / Audio should keep playing, since they have their own controls to interact with? Or should they pause too if I start poking the tree?
* The pop-up in the tutorials tour shouldn't, since if I'm poking about in the tree having the pop-up appear is really annoying. https://github.com/OneZoom/OZtree/commit/da05b6ca94e605cda26d488bae6face84fe031c8

Revising how any of these works will require re-thinking the pause mechanism works.

**Comment by jrosindell** [comment]
> I think you're right, there's an argument for still being able to press prev/next whilst paused, which possibly skips transitions between states.
> 
> However, in this case the tour shouldn't think it's unpaused whilst the tourstop thinks it's paused, which is what's happening at present. That definitely needs fixing.

Agreed

**Comment by jrosindell** [comment]
> * As above, is resuming when "Skip" is pressed on a paused stop reasonable?

I think it's fine from a UX perspective it could be argued either way but as this is simpler to just move stop and unpause I'm fine with that behaviour remaining

> * How much should be we pause / resume on pause/resume?
> * Flights definitely should pause / resume

agreed

> * Stop timers should ideally pause / resume (currently we restart from the beginning)

agreed

> * Videos / Audio should keep playing, since they have their own controls to interact with? Or should they pause too if I start poking the tree?

I think they should keep playing but after they finish the tour is paused. Probably we need a way to dismiss the video though if the user wants.

> * The pop-up in the tutorials tour shouldn't, since if I'm poking about in the tree having the pop-up appear is really annoying. [da05b6c](https://github.com/OneZoom/OZtree/commit/da05b6ca94e605cda26d488bae6face84fe031c8)

agreed

A related question.... will we have a distinction between cancelling a tour and pausing a tour?

> Adding window_size_change to the list of interactions for the most part solves this, however it's impossible to block a window resize we can with clicks. If your tour's interaction is set to "block_on_flight", and you take advantage of this by hiding tourstops in transitions, the resizing the window will stop the flight and tour, with nothing visible on-screen. I'm not sure what the solution is here. Possibly "don't do that", and always have something on-screen.

I think in the end we probably want flights that survive window resizing for but now I like this solution. I also think that the UX should always have some indication that a tour is loaded and can be resumed or exited - hence it should be impossible to resize and pause on a tour with no controls open.  Hence it will be easy to resume for the user if that's what they want
