### ISSUE TITLE
Ancestor's Trail tree

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#61]
I just noticed that the link used from the trail website 

https://ancestorstrail.org.uk

is

http://www.onezoom.org/trail2016.html

and this page no longer works properly. I thought I should record the issue straight away.

**Comment by hyanwong** [comment]
I have fixed this on master, but this will only work on beta

**Comment by hyanwong** [comment]
Can be closed when we push beta to prod

**Comment by hyanwong** [comment]
Might as well close now.
