### ISSUE TITLE
Encyclopedia of Life identifiers csv file is missing its header

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/OZtree#615]
The [doc](https://github.com/OneZoom/OZtree/tree/main/OZprivate/ServerScripts/TaxonMappingAndPopularity) says to download the EoL identifiers file from https://opendata.eol.org/dataset/identifiers-csv-gz.

Doing this results in a csv file without a header. i.e. it starts with

```
20571209,"http://mushroomobserver.org/name/show_name/1",113,5559,"Fungi"
20571277,"",114,4409,"Aceraceae"
20571278,"",114,37290,"Acer"
...
```

This then causes [add_eol_IDs_from_EOL_table_dump()](https://github.com/OneZoom/OZtree/blob/4cc6f9d01a4b55be767633cac57ca6931f2b50d0/OZprivate/ServerScripts/TaxonMappingAndPopularity/CSV_base_table_creator.py#L194) to fail, because it's relying on headers to reference columns. e.g.

    provider = int(EOLrow['resource_id'])

Maybe this used to be correct on the EoL download, but somehow changed recently? I can try asking over there, but thought I would check here first.

**Comment by hyanwong** [comment]
Ah, I suspect this has changed in EoL. I will ask them. Thanks for picking this up.

**Comment by hyanwong** [comment]
I have just asked and EoL are correcting it. Meanwhile, they say:

```
You can get the "direct" files from EOL via [this](https://eol.org/data/full_provider_ids.csv.gz) and [that](https://eol.org/data/provider_ids.csv.gz) link (but the OpenData links should really be the canonical ones for non-friends.) 
```

**Comment by davidebbo** [comment]
Thanks @hyanwong those look much better. I ended up reporting it [here](https://discuss.eol.org/t/identifiers-csv-eol-v2-is-missing-a-header/2098) yesterday, but clearly its more effective via your insider channels. :) That file also had additional issues with improper quotes which further broke the csv parser.

Those two new files look good. The second one (full_provider_ids.csv.gz) has about twice the number of lines as the first (provider_ids.csv.gz), ~26M vs ~13M. But maybe the subset that is relevant to OneZoom is in both, and either can be used?

Anyway, I still have only a faint idea what I'm doing, but this is a small step forward!
