### ISSUE TITLE
Enable Discussions on the repo

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/OZtree#619]
What do you think about enabling the GitHub [discussing feature](https://docs.github.com/en/discussions) on the repo? It might work better than 'abusing' Issues for discussions that are really not issues.

Looks like it's just a checkbox under Settings / General to enable this.

I've never actually used this feature, and didn't know it existed, but it seems worth trying :)

**Comment by hyanwong** [comment]
Ah, good plan. I do use that feature in the other GitHub development project I'm involved in. It works OK, although it's rather easy to overlook newly added items & chat. I think it would be fine here though. I will activate it.

**Comment by hyanwong** [comment]
Should be done now

**Comment by davidebbo** [comment]
Thanks @hyanwong !

**Comment by hyanwong** [comment]
No problem. Good suggestion. Glad it works!

**Comment by davidebbo** [comment]
I started a discussion yesterday. Not at all urgent nor important as it was more to test the discussion feature, but more curious whether it generated a notification for you.

**Comment by hyanwong** [comment]
Yes, I did get the notification - good to check. I've been busy with various family illnesses et this weekend so didn't reply, sorry!

**Comment by davidebbo** [comment]
Sorry to hear this Yan. Hope everyone is on a path to recovery. And not that I'm never expecting a fast response on anything here. I only asked on this one since we just turned on discussions and I wasn't sure how notifications worked :)

**Comment by hyanwong** [comment]
Thanks. No problem asking on the GH repo - I can always ignore! Definitely worth checking that the notifications are coming through.
