### ISSUE TITLE
Dynamic screensaver on front page broken

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#649]
I think 01d3fbf4e8519ed13ed2f10fb0ddc3500b90b605 broke the front page: at least, on Safari after this commit, the "movie" and on the top right of the front page is missing navigation buttons and a central box.

The javascript error in Safari is as follows:

<img width="927" alt="Screenshot 2023-04-01 at 20 04 30" src="https://user-images.githubusercontent.com/4699014/229309590-fc8382eb-5b81-4344-a447-363248534a6f.png">

**Comment by hyanwong** [comment]
The issue here was that it was looking for a non-existent version of pymysql:

```
ModuleNotFoundError: No module named 'applications.OZtree.modules.pymysql
```

Here

https://github.com/OneZoom/OZtree/blob/2d6a8487ff6133b473575e258ec3435169eec8fc/controllers/tour.py#L66

**Comment by hyanwong** [comment]
We could import the web2p built-in pymysql, but that's very old, and doesn't allow 4-byte UTF: see 

https://github.com/OneZoom/OZtree/issues/676

I don't really understand how the current setup is using 4 byte UTF when loading appconfig.ini (I think it does this in a venv which contains a recent pymsql version, but then it fails to load the pymysql module within a controller? Perhaps the subprocesses that actually run the web service are not running in the env, but the master process that kicks them off is?

**Comment by hyanwong** [comment]
Edit - the env didn't have pymysql installed. I have just installed it

**Comment by lentinj** [comment]
> I think it does this in a venv which contains a recent pymsql version, but then it fails to load the pymysql module within a controller?

An option is the pymysql version embedded in web2py has been patched (or upgraded) for this not to be a problem. If it has, then ``?set_encoding=utf8mb4`` would work but ``import pymysql`` would still be broken.

**Comment by hyanwong** [comment]
Ah, that could be it, I suppose.

**Comment by hyanwong** [comment]
Hmm, so now the front page animation more-or-less works (and I have upgraded beta.onezoom.org to main), but the *links* from the animation, e.g. to "Explore the great apes", seem not to have an href, and therefore simply reload the front page. Any idea why this should be @lentinj ?

**Comment by lentinj** [comment]
FWIW you don't need to wait for the tour to do it's thing before seeing this, you can view-source:https://beta.onezoom.org/tour/homepage_animation

**Comment by hyanwong** [comment]
On a new build I'm still seeing the issue above:

> the links from the animation, e.g. to "Explore the great apes", seem not to have an href, and therefore simply reload the front page. 

I assume the fix hasn't yet been ported into main, @lentinj ?

**Comment by lentinj** [comment]
Yeah, doesn't look like this has happened yet I'm afraid. I'll get this done when I start OneZoom-ing January.

**Comment by jrosindell** [comment]
Just a quick comment on this to say that some redesign of the front page has been suggested by UX designer - including dropping of the movie control buttons mentioned in the original post. I'm not sure how important it is to fix that part of the functionality

**Comment by lentinj** [comment]
@jrosindell this is the links to individual species in the home-page tour, not the movie controls. Unless we're outright binning the homepage tour this is still worth doing.
