### ISSUE TITLE
Autoplay settings for DB generated tours

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#651]
https://github.com/OneZoom/OZtree/commit/86760f361220b80feae6057bc19c8d55dd181351 assumes that autoplay in active_wait is what we want for any DB tourstop, but we should add means to configure this.

However, I'm not sure if we should be more restrictive where we allow autoplay?

**Comment by hyanwong** [comment]
Hmm, good point. I think this requires a short discussion with @jrosindell, possibly after looking at a demo?

**Comment by lentinj** [comment]
I thought we did the demo for this bit a while back? Easy enough to do another though.

Should also think about #654 at the same time, likewise we need to know in which tourstop states the highlights should be on for, or decide we're hard-coding it for DB tours.
