### ISSUE TITLE
setupUI not in sync with treeviewer setup

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#655]
The UI doesn't seem to wait for the treeviewer to be ready before interrogating it to get the various things it needs to setup the UI (e.g. language, highlight status).

This results in the occasional "Cannot set properties of undefined (setting 'title')" in ``toggleAdvancedSearch`` currently, as the language isn't set yet. This will get worse as more of ``setup_page_by_state`` happens asynchronously.

Add more locking, so it waits until the relevant parts of the treeviewer are ready.

(the more fundamental problem here is that the tail is wagging the dog; The UI should be in charge of the URL, and passing options through to the treeviewer, which is a component on the page)

**Comment by hyanwong** [comment]
Yes, this is a bugbear, and would be good to fix properly. Have you a suggestion of a way forward? I find all the async stuff intensely confusing!

**Comment by lentinj** [comment]
Not yet, I need to rummage through and work out how it all joins together currently. But probably will result in it with some "page_state_changed" event that setupUI can be hung off.

**Comment by lentinj** [comment]
Okay, my initial diagnosis was a bit off. What's happening on language change is that jQuery was being used to replace the DOM content for the UI, then firing an event on done (i.e. calling setupUI).

UIKit keeps an eye on any DOM changes and wires up any components it recognises (read: the advanced search tooltip). However, the jQuery event fires immediately after the DOM has been changed, UIKit hasn't had a chance to leap into action.

The fix above is a bit unsatisfying, but sufficient. Waiting a bit gives chance for the relevant events to fire and be processed, after which UIKit is ready to do it's thing.

This also used to happen on-load, but that seems to have evaporated. Not sure why.
