### ISSUE TITLE
Switch code to use sponsorship_ends

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#660]
In the main API query (`nodes_info_from_string` we (optionally) return sponsorship info, and we calculate the expiry date using `sponsorship_duration_days` plus the `verified_time`, but we could save some calculating using `sponsorship_ends` instead.

https://github.com/OneZoom/OZtree/blob/4a2c8d393bbfcb5663819fd0010079e65666e72c/modules/OZfunc.py#L509

**Comment by lentinj** [comment]
Not only could we save some time by using ``sponsorship_ends``, we seemingly could save even more time by just throwing it away.

The point of ``active`` seems to be to knobble sponsorships once sponsorship_ends has passed, it's used to do things like ``IF(active,verified_name,'leaf_sponsored')``. This shouldn't be necessary, since they'll get moved to ``expired_reservations``.

But if this is what's going on, then surely onezoom.org would be full of anonymous sponsorships? There's something I'm missing somewhere.

**Comment by lentinj** [comment]
NB: We can't test what happens on expiry in the same way as other leaves, because the condition uses the MySQL date not web2py date. But doctoring the above test to create reservations in the past does produce what you'd expect for expired reservations:

```
 'reservations_dict': {4787677: {'OTT_ID': 4787677,
                                 'verified_kind': 'by',
                                 'verified_more_info': '',
                                 'verified_name': 'leaf_sponsored',
                                 'verified_url': None},
                       4787747: {'OTT_ID': 4787747,
                                 'verified_kind': 'for',
                                 'verified_more_info': '',
                                 'verified_name': 'leaf_sponsored',
                                 'verified_url': None}},
```

**Comment by hyanwong** [comment]
Good point - this was code that was written before we had functions to move stuff into expired_reservations, so I think you are right: we can simply omit this condition.

However, there is another field, `deactivated`, which we also sometime use in order to mark a reservation as invalid (e.g. if the sponsored species accidentally drops off the tree). If `deactivated is not NULL or deactivated <> ""` then we should ignore this reservations row. I don't know if we will use it in the future though: we could just move bad sponsorships like this to `expired_reservations`, right @jrosindell ? In which case we can remove `deactivated` from the db definitions.

**Comment by jrosindell** [comment]
@lentinj is right - this has been a problem that deactivated sponsorships have displayed incorrectly on the tree as 'awaiting admin approval' and we never fixed this.  An example is the AyeAye that was sponsored for 1 year but not renewed so we deactivated and left it floating around in the reservations table until recently.

I agree with @hyanwong that we'll just move deactivated sponsorships out of the table now so the deactivated field is probably redundant in a way - though note that in the cases where things are really deactivated it's used to store a free text comment as to why.
