### ISSUE TITLE
Change expiry_soon_days and expiry_critical_days

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#662]
We decided that expiry_soon_days should default to 30 and expiry_critical_days should default to 10. They need setting here:

https://github.com/OneZoom/OZtree/blob/41fac8e29a2a3e31c313714947194bf79eb528e4/modules/sponsorship.py#L54

When doing this, is there any constraint on what we should set `expiry_hysteresis` to, @lentinj ?

It's not critical to do this now, because we will override it on the server using appconfig.ini, but it would avoid confusion to change the defaults in the code to what we expect.

**Comment by lentinj** [comment]
Beyond the obvious "make sure the regions don't overlap as a result", I don't think so. What they actually do is:

https://github.com/OneZoom/OZtree/blob/41fac8e29a2a3e31c313714947194bf79eb528e4/modules/sponsorship.py#L740-L743

The first date decides that they appear in an e-mail, the second triggers the e-mail to actually be sent (and thus batching the 10 days' worth of alerts).

**Comment by hyanwong** [comment]
Also it would be good to add a comment with a little more explanation of the `expiry_hysteresis` value, e.g. using a practical example, as it's not obvious ATM. E.g.

"If expiry_soon_days is 31 and expiry_hysteresis=5, then when the script is run anything exciting between 31 and 26 days will be considered as expiring soon". Is that correct @lentinj ?

**Comment by lentinj** [comment]
"If expiry_soon_days is 30 and expiry_hysteresis=5, then an e-mail will be sent when any sponsorship has 25 days left. This e-mail will include any other sponsorships with 25..30 days left - these won't get a separate e-mail once they hit 25 days left.".
