### ISSUE TITLE
Email renewal code incorrectly calculating expiry date

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#664]
We have been testing the renewals pathway. I have a sponsorship for _Giardia intestinalis_ due for renewal tomorrow (`sponsorship_ends=2023-04-24 21:42:18`, `sponsorship_duration_days=2505`, `verified_time=2016-06-14 21:42:18`). When  I ask for a dry-run email, (on 23rd April), I get the following logged:

```
Expiring very soon, or already expired:

* Giardia parasite (Giardia intestinalis) - now expired, but might not be too late to renew

```

Although it hasn't actually expired yet. When I go to the renewals web page, it correctly says it hasn't expired yet. So I think the email generating code is slightly wrong:

<img width="1173" alt="Screenshot 2023-04-23 at 22 57 54" src="https://user-images.githubusercontent.com/4699014/233868389-474ccb77-851d-4b68-bfdf-3b9f8ffd7bdf.png">

**Comment by lentinj** [comment]
It's a question of rounding I think (I had a suspicion this was coming):

```
>>> def strptime(x): return datetime.datetime.strptime(x, '%b %d %Y %I:%M%p')
...
>>> (strptime('Jun 10 2023  1:33PM') - strptime('Jun 9 2023  1:23PM')).days
1
>>> (strptime('Jun 10 2023  1:33PM') - strptime('Jun 9 2023  1:43PM')).days
0
```

I think we add a special case for this, displaying "less than a day to renew".

I'm slightly worried that we're being too literal in our interpretation of "days" here though, and should be doing a midnight<->midnight comparison. OTOH, we don't decide when people read their e-mail, so there's always potential for it to be off by a bit.

**Comment by lentinj** [comment]
Also, this looked way less bad in the tests since they assumed that expiry was ``4*365``, not ``4*365 + 1``.

**Comment by lentinj** [comment]
Have a look at #666, merge it if you think the change in wording is good.

**Comment by hyanwong** [comment]
> Have a look at #666, merge it if you think the change in wording is good.

@jrosindell - what do you think? LGTM, although I can't see an obvious change in the wording that the end user sees?

**Comment by lentinj** [comment]
It's that I've gone for a Central Line 1 day left, which is one-and-a-bit days long, vs. explicitly saying "Less than a day to renew" or summat.

**Comment by jrosindell** [comment]
Yes this looks good to me as well
