### ISSUE TITLE
'was_renewed' field set incorrectly in expired reservations.

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#674]
Everything that's moved across to expired reservations seems to have 'was_renewed' = 1 regardless of whether it was really renewed or not. e.g. OTTID 50727. I think we need to check this as it's probably a bug.

**Comment by hyanwong** [comment]
Needs a test writing, I guess.Have you looked for "was_renewed" in the test suite?

**Comment by lentinj** [comment]
Yeah, this is fairly obviously problematic:

https://github.com/OneZoom/OZtree/blob/59720b8c31b5183b28c485d9aafdc406a0528666/modules/sponsorship.py#L167-L171

IIRC we use this function both in expiry and in renewal. We only need to do this bit in the latter.

**Comment by hyanwong** [comment]
Thanks @lentinj - Those lines are indeed part of the problem. I've been chatting about this with James. We think there are 2 things wrong:

1. "was_renewed" in the expired_reservations table is always set to True when expiring, even when the sponsorship wasn't renewed, simply expired
2. The row in the main reservations table should not be deleted on expiry: instead, the user-specific fields should be wiped, but some elements should stay the same (e.g. the visit count). I think we simply didn't make it clear this was required when asking you to come it up.

**Comment by lentinj** [comment]
Yeah (1) is pretty obvious how to sort, and wouldn't take very long.

And yes, I'd not realised about (2). Do we know what fields should be preserved, besides ``num_views``?

**Comment by hyanwong** [comment]
> Yeah (1) is pretty obvious how to sort, and wouldn't take very long.

Great

> And yes, I'd not realised about (2). Do we know what fields should be preserved, besides `num_views`?

id, OTT_ID, name, num_views, last_view, and deactivated should do it.

**Comment by hyanwong** [comment]
Anyway, panic over! We thought these had all gone missing completely! But it's all recoverable, phew!

**Comment by lentinj** [comment]
Is ``was_renewed`` True for a expire-and-repurchase as well as a renewal? I'm assuming yes.

**Comment by lentinj** [comment]
Gah, somehow I managed to not notice the convenient ``clear_reservation``() just above that does exactly what we want.

https://github.com/OneZoom/OZtree/blob/59720b8c31b5183b28c485d9aafdc406a0528666/modules/sponsorship.py#L138-L144

(even more annoyingly, I was the one that moved it there in the first place. Ah well.)

But, it doesn't preserve ``name`` or ``deactivated``. is that a bug? Former is probably not that much of a deal either way, the latter might be.

**Comment by lentinj** [comment]
Either way, the code changes are above. Note the latter also changes ``get_reservation`` to return up-to-date counts with it's reservation row. This shouldn't make a difference in real life since we don't do anything with the counts, but potentially reduces unit-test confusion in future.b

**Comment by lentinj** [comment]
@hyanwong The above commit removes as much of the deactivated field as possible without restructuring the database. It's not part of the pull request above but can add it if you still think it's a good plan?
