### ISSUE TITLE
Delete most files from static/FinalOutputs/data

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/OZtree#683]
This [static/FinalOutputs/data](https://github.com/OneZoom/OZtree/tree/main/static/FinalOutputs/data) folder has various ancient versions of the generated static files. Do they serve any purpose? I would think that anyone who wants to run the site should generate fresh files (using the tree-build steps).

And the folder should have a .gitignore.

**Comment by hyanwong** [comment]
James wanted to have some permanent record of previous versions of the tree, so we decided to save them here.

**Comment by davidebbo** [comment]
Fair enough.

**Comment by davidebbo** [comment]
We can keep these files, but we can also add a .gitignore, so that new files used for testing don't get treated by git as an untracked change.
