### ISSUE TITLE
Tour images from Wikimedia use full resolution versions unnecessarily 

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#736]
In the frogs and toads tour we have

     "media": [
                    "https://commons.wikimedia.org/wiki/File:Anoures.jpg"
                ]

Which works fine but I've noticed that it fetches the 4.2Mb version of the image which is not necessary.

https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Anoures.jpg/529px-Anoures.jpg

![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Anoures.jpg/529px-Anoures.jpg)

gives us a sensibly resized version but doesn't work if I insert this URL into a tour.

**Comment by lentinj** [comment]
For this to happen we need to implement a metadata cache, so on first request we fetch available sizes & the full title. We then store this in our DB so we're not continually fetching.

The approach here might be worth considering within #601 before leaping in.

**Comment by jrosindell** [comment]
OK agreed, the caching is heavy handed.  I'd suggest that the solution is for tour designers to store a sensible resolution version in static.  So, what's really needed here is a solution to store assets in statics for tours as needed (I don't see that working with any example right now) also, to enable licensing and credits to be stored somewhere for such static assets. For this part I'm not sure what's best but perhaps we ultimately need a DB table with a list of assets that aren't exactly images (of species) by OTT but still get used. The table should have location of material in static, link to source and license.   I guess that's too much for this project so a cut back version might expand the tour JSON to enable licenses and sources to be declared for materials and hence we can have something performant working with proper acknowledgements as needed.

**Comment by lentinj** [comment]
Not bothering with this, using #741 instead.
