### ISSUE TITLE
space doesn't work in search

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#738]
If I press the space bar whilst typing into search (latest version of main branch at the time of writing) the space has no effect.

**Comment by lentinj** [comment]
See also #731, it gets mentioned there, but that's an unrelated problem.

**Comment by lentinj** [comment]
This is an incompatibility with the latest UI-Kit, which tries to make dropdowns open/close on space:

https://github.com/uikit/uikit/blob/8313ce565be686952ab6edf8a7caee5fdfcca08c/src/js/core/toggle.js#L138-L151

It already turns this off when the dropdown is an input, but in our case the input is buried under other bits and bobs.

**Comment by lentinj** [comment]
Fixed with #744
