### ISSUE TITLE
Tours wikimedia content not working on Safari

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#773]
e.g. see the screenshot form frogs and toads

![OZ tour video bug](https://github.com/OneZoom/OZtree/assets/3009279/1af9774e-9d43-4a8b-93d2-cbe7d599dfde)

The same issue occurs with sounds

**Comment by lentinj** [comment]
This is basically a video version of https://github.com/OneZoom/OZtree/issues/743, VP9 (the codec used by the froglet) is only supported in Safari 14.1 onwards.

Unlike video, we can't say "Just use MP3" as there's not a universally supported format. VP9 will probably be it eventually.

It might be the case that Safari is offered an alternate format if you go to https://en.wikipedia.org/wiki/File:Intense_bone_fluorescence_reveals_hidden_patterns_in_pumpkin_toadlets_-_video_1_-_41598_2019_41959_MOESM2_ESM.webm, but I can't see one myself.

**Comment by hyanwong** [comment]
See https://github.com/OneZoom/tours/issues/1 - it *should* work on recent safari versions if we spec ivy the right transcoding.

**Comment by jrosindell** [comment]
After some testing by Yan and I both of whom have experienced intermittent working here - we now think it's caused by race conditions.  If the video is slow to load the JS starts to complain about things

**Comment by hyanwong** [comment]
> @hyanwong to intelligently choose videos with the right encodings, we'd have to either persuade Wikimedia to publish a iframe API for their player, or build our own player out of their sources. We'd need a metadata cache similar to #736.
> 
> Whether this is worth it depends on how many videos come from Wikimedia really.

Can we just pick one of the transcoded versions and use that?

It's a bit irrelevant anyway, as this video *does* seem to work on the latest Safari. The odd thing is that (for me) it wasn't working until recently, which is why we suspect there might be some sort of race condition. As that's hard to debug, however, I'm happy to boot this down the line, unless @lentinj or @davidebbo have any clues on what might be causing the videos to sometimes fail even on the most recent Safari.

**Comment by lentinj** [comment]
> Can we just pick one of the transcoded versions and use that?

This won't be much of an improvement over letting Wikimedia choose one. We ideally tell the browser all available transcodings and let it choose what it supports, or even better use the Wikimedia video player to do this for us (provided we can still autoplay videos using it).

> The odd thing is that (for me) it wasn't working until recently, which is why we suspect there might be some sort of race condition.

Were there any errors in the console beyond https://github.com/OneZoom/OZtree/issues/783? I'm pretty sure neither of those are related.

**Comment by hyanwong** [comment]
> > Can we just pick one of the transcoded versions and use that?
> 
> This won't be much of an improvement over letting Wikimedia choose one. We ideally tell the browser all available transcodings and let it choose what it supports, or even better use the Wikimedia video player to do this for us (provided we can still autoplay videos using it).

Fine, I think what we have now seems good as long as we can figure out why it sometimes fails.

> > The odd thing is that (for me) it wasn't working until recently, which is why we suspect there might be some sort of race condition.
> 
> Were there any errors in the console beyond #783? I'm pretty sure neither of those are related.

I don't think so. I'll try to replicate when loading beta.

**Comment by hyanwong** [comment]
I'm still seeing this on the "hidden" prod server, but it might just be a certificates thing. This is the error in the JS console:

![image](https://github.com/OneZoom/OZtree/assets/4699014/912131f6-a281-4d53-8460-7e14630e82b3)

**Comment by lentinj** [comment]
Nothing to do with certs---safari isn't letting us autoplay, same as here: https://github.com/OneZoom/OZtree/issues/783#issuecomment-2056502195

We should catch and humanize the exception though.
