### ISSUE TITLE
Clearing previously set tourstop values (qs_opts)

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#776]
if I've loaded a tour into the DB and then overwrite it later the global qs_opts are not overwritten in each tour stop.

So if I load a tour with 

` "tourstop_shared": {
        "fly_in_speed": 0.8,
        "stop_wait": 15000,
        "qs_opts":"cols=popularity"
    },`

then later edit the tour to say

` "tourstop_shared": {
        "fly_in_speed": 0.8,
        "stop_wait": 15000
    },`

it will not overwrite each tour stop to retain the default qs_opts

This doesn't matter so much if we're loading tours by wiping everything and reloading each time

**Comment by jrosindell** [comment]
The problem here is that the curl command for loading tours does not work properly - the database is not updated if I update the JSON and load it in again.

I think this perhaps relates to @davidebbo's request via slack for a helper to delete a tour (I currently do this by zapping from the DB directly)

**Comment by lentinj** [comment]
@jrosindell What do you mean by not work properly?

Deleting and recreating a tour would certainly be one way of getting around the above, but would create a lot of unnecessary database churn for an update.
