### ISSUE TITLE
Using markdown in tour text content

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#781]
It would be really useful to be able to use markdown in the text in tours. In particular, we could do with bold and italic, bullets and number lists, and possible the ability to grey things out somehow (although that might involve <span> tags I guess, which could be bad). How easy would this be to implement @lentinj ?

**Comment by lentinj** [comment]
On the surface, pretty easy. We inject a markdown parser at some point when converting the data structure to HTML:

https://github.com/OneZoom/OZtree/blob/0e513c9d0b30223605b8dc2620d7faeef1bd5c90/views/tour/data.html#L56-L58

Web2py already includes a markdown parser, so can just use that.

What will be hard work though is shoehorning (multiline) markdown into valid JSON by hand. I think it would be worth investigating supporting [TOML](https://toml.io/en/) or YAML as an alternative tour serialisation format. Supporting either should be fairly easy (now we have a venv to vendor a YAML library), but we may have to tweak the structure a bit to make sense.

**Comment by hyanwong** [comment]
Could we just allow trivial markdown (e.g. italics etc) for the moment, and retain json? That would presumably be OK, and we could always use raw HTML tags (I guess?) e.g. `<ul>` etc rather than have to worry about multiple lines?

**Comment by lentinj** [comment]
> Could we just allow trivial markdown (e.g. italics etc) for the moment, and retain json?

They're separate issues---Nothing is stopping stopping an arbitrarily complex markdown string being encoded into a JSON document. And yes this is something we could enable without switching from JSON.

My point is that writing these JSON documents by hand will be hard, and switching serialisations would make tour curation a lot easier.

**Comment by hyanwong** [comment]
Yep - I take your point. But for the moment, we could switch to allowing single-line markdown, which gives us a little more flexibility, even in the JSON format. We can think later about using YAML or whatever (which sounds like a lot more work, although probably worthwhile)?

**Comment by hyanwong** [comment]
I'm not sure of the pros and cons of TOML vs YAML (or any other alternative), but I can see this as useful for the next iteration of tours development. I wondered if markdown in JSON would be possible in this iteration, that's all.

**Comment by davidebbo** [comment]
I think it would make sense to treat the strings as full markdown in the JSON. While it's painful to author by hand for non-trivial markdown, one can just go to a site like https://nddapp.com/json-encoder.html, write their markdown and get back a properly encoded JSON string. Later, we can consider switching away from JSON, to make direct authoring easier.
