### ISSUE TITLE
Tours: pause video when tree is clicked

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#782]
I don't know if this is easy/possible, but @jrosindell and I though that it would seem more logical to pause any video (and ?audio) when the user clicks elsewhere on the tree as the video is playing (this is when the next button turns into "resume" - presumably you would click "resume" to continue the video)

**Comment by lentinj** [comment]
It's fairly easily doable, but I'm not convinced it's the "right thing" in all cases. Especially on a smaller screen, where you might have to nudge the view about a bit to get what the video is talking about.

OTOH, as you say it makes our pause/resume behaviour more consistent, maybe this is reason enough to do it.

**Comment by jrosindell** [comment]
I think we should have this pause functionality regardless - it does feel more consistent and easier to grasp.

**Comment by hyanwong** [comment]
I agree - can we put this on the list of things to implement today, @lentinj ?

**Comment by lentinj** [comment]
Right, this was a fair bit more complex than initially envisaged, but I think https://github.com/OneZoom/OZtree/pull/817 catches all the cases.

If it still proves problematic, It may be easiest to hide player controls and do our own. The tourstop would become more complex but it would get rid of syncing at least in one direction.
