### ISSUE TITLE
Can't find variable `OZui` error in JS

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#783]
I'm getting to follow error on viewing the frogs and toads tour:

![screenshot_2024-04-09_at_12 15 37_720](https://github.com/OneZoom/OZtree/assets/4699014/e6fd155f-7dab-4af5-b969-00c564a99fc0)

**Comment by lentinj** [comment]
> I'm now getting [NotAllowedError] But the tour video is actually working...

Error is an overly strong description here---that's us tripping Safari's autoplay policies. I'd assume that once you start it playing manually, you can go next then previous, and the video starts playing immediately without an error.

We should catch this error and turn it into a warning though, at very least so the exception doesn't stop other parts of the tour from working.

**Comment by lentinj** [comment]
> Hmm, the above looks like a race condition (something to do with <script defer>)

Yeah, this seems very likely. We're also ``<script>``ing OZui twice for some reason.

**Comment by hyanwong** [comment]
See #801 for the reason for not finding OZui (it's the `defer` keyword). We should also remove the double inclusion of OZui, and (I guess?) figure out how to remove the `<head>` tags (#802)?

**Comment by hyanwong** [comment]
OZui issue fixed by https://github.com/OneZoom/OZtree/pull/803
