### ISSUE TITLE
Solve PayPal updating issues

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#80]
AT the moment the paypal updating doesn't seem to work. Once we push to beta we can test the mechanism and try to solve why this is (PP testing doesn't work on localhost, as it requires a public-facing web server). We should also add a functional test to check this works on the server (only to be run when (a) not on localhost and (b) when paypal.url in appconfig.ini contains "sandbox".)

Yan

**Comment by hyanwong** [comment]
This might be something to solve alongside https://github.com/OneZoom/OZtree/issues/133

**Comment by jrosindell** [comment]
Unfortunately, the 'live' test I've done with PayPal isn't working on a.onezoom.org so transaction goes through but details don't post.  This has not been a problem for a long time on the live site.

**Comment by hyanwong** [comment]
What do you mean "the details don't post"?

**Comment by hyanwong** [comment]
I see this in the logs:

```
173.0.81.1 - - [25/Apr/2020:11:52:59 +0000] "POST /pp_process_post.html/None HTTP/1.1" 500 853 "-" "PayPal IPN ( https://www.paypal.com/ipn )"
173.0.81.1 - - [25/Apr/2020:11:53:11 +0000] "POST /pp_process_post.html/None HTTP/1.1" 500 853 "-" "PayPal IPN ( https://www.paypal.com/ipn )"
173.0.81.1 - - [25/Apr/2020:11:53:33 +0000] "POST /pp_process_post.html/None HTTP/1.1" 500 853 "-" "PayPal IPN ( https://www.paypal.com/ipn )"
173.0.81.1 - - [25/Apr/2020:11:54:15 +0000] "POST /pp_process_post.html/None HTTP/1.1" 500 853 "-" "PayPal IPN ( https://www.paypal.com/ipn )"
173.0.81.1 - - [25/Apr/2020:11:55:36 +0000] "POST /pp_process_post.html/None HTTP/1.1" 500 853 "-" "PayPal IPN ( https://www.paypal.com/ipn )"

```

so paypal are, I think, getting back to us. But we are messing up somehow

**Comment by hyanwong** [comment]
There's a management page which might help testing: a.onezoom.org/dev/TEST_POST

**Comment by jrosindell** [comment]
Yan has fixed this with a recent push to Master
