### ISSUE TITLE
<header> CSS style change

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#84]
Something has changed to the CSS all over the site - everything inside <header> now appears in a box with text as a strange kind of shadow.  This needs to be reverted to how it was before.

E.g. see http://127.0.0.1:8000/endorsements.html

![untitled](https://user-images.githubusercontent.com/3009279/39296143-0b0a3d88-4938-11e8-880e-ad4cd5475f17.png)

**Comment by jrosindell** [comment]
I think you meant grunt compile!  Yes it's fixed thanks

**Comment by hyanwong** [comment]
No, `grunt compass` just runs the css stuff which is run as one step of `grunt compile`. So running `grunt compass` is quicker if you've only been faffing with css. But whatever. Thanks for checking.
