### ISSUE TITLE
sponsor_renew_request not redirecting after sending mail

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#841]
The controller isn't redirecting back to a GET version of the page:

https://github.com/OneZoom/OZtree/blob/2f51d56262182e70c09fe30ce62c44d9b423e74c/controllers/default.py#L625-L640

It should have a ``redirect()`` on success, kinda like: http://web2py.com/books/default/chapter/34/07/forms-and-validators#Forms-and-redirection, so a reload of the page doesn't send another e-mail.

@hyanwong this isn't necessarily the root of your late night email avalanche, I've no idea why a browser would try and reload 8 times, but if it does it again then there should be no problems in doing so.

**Comment by hyanwong** [comment]
Ah, that's great. Thanks @lentinj. Shall I add the `redirect()` or do you want to.

Do we need a "unit" test for this behaviour? I'm guessing that's a bit tricky with the current setup.

**Comment by jrosindell** [comment]
I've done a bit of testing here.  The first time I requested I got two e-mails because after clicking the 'submit' button nothing was obviously happening and so I clicked it again.  A little while later I tested it with what was consciously a single click and I got a single e-mail.

**Comment by lentinj** [comment]
> Shall I add the redirect() or do you want to.

I'll have a look if I've time Monday.

> Do we need a "unit" test for this behaviour? I'm guessing that's a bit tricky with the current setup.

It's straying into unit-test-configuration territory, but it's still worthwhile.

The main faff with the unit test setup is mocking the mailer. We could probably achieve that with something similar to https://github.com/OneZoom/OZtree/blob/2f51d56262182e70c09fe30ce62c44d9b423e74c/tests/unit/test_controllers_default_sponsor.py.

But worst case, we don't actually care here. As long as we use an example.com address we'll have no side effects, even if the site configuration specifies a working mailer. All we care about is we managed to call ``sponsor_renew_request_logic`` and got some kind of flash message back.

**Comment by hyanwong** [comment]
That would be great. Thanks @lentinj
