### ISSUE TITLE
Remove `.html` from internal URL() links.

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#846]
@davidebbo pointed out a problem with accessing URLs using https://www.onezoom.org/life.html, instead of just https://www.onezoom.org/life (no extension): https://github.com/OneZoom/OZtree/issues/843.

The search bug is now fixed but he also (very reasonably) said:

> We should fix all internal links to not have the extension, if only for consistency. e.g. it doesn't have it from the home page (if you click on popular places...), but does have it from https://www.onezoom.org/introduction.html

We need to take a little care, because web2py can add e.g. a `.load` ending to `{{=URL('default','life')}}` *if the view is itself access from a `.load` page* (see http://web2py.com/books/default/chapter/29/04#Dispatching). Therefore I suggest, if we really mean the URL to be to a .html file, but don't want the extension to appear in the link, that we use

`{{=URL('default','life',extension=False)}}`

Since there is no `life.load` file in `views/treeviewer` (which is where default/life is redirected to in the controller), then we can quite reasonably do this for all instances of `life.html`, I think. These are the relevant files:

```bash
OZtree % grep -l 'life\.html' views/*/* controllers/*
views/default/FAQ.html
views/default/data_sources.load
views/default/endorsements.html
views/default/introduction.html
views/default/spl_maintenance.html
views/default/sponsor.html
views/default/sponsor_leaf.load
views/default/terms.load
views/default/treecards.html
views/education/educational_materials.html
views/manage/SHOW_EMAILS.html
grep: views/tour/tourstop: Is a directory
views/treeviewer/layout.html
controllers/default.py
```

**Comment by lentinj** [comment]
The menu is also a good target, e.g:

https://github.com/OneZoom/OZtree/blob/fa65779fcd6a37cd6658e3fd21b07568ea023a17/models/menu.py#L33-L40

You could probably sort most of them with a regex find-replace.

**Comment by hyanwong** [comment]
> [OZtree/models/menu.py](https://github.com/OneZoom/OZtree/blob/fa65779fcd6a37cd6658e3fd21b07568ea023a17/models/menu.py#L70-75)

I notice this also has the following. Presumably we should just remove anything below line 69?

```
DEVELOPMENT_MENU = False

#########################################################################
## provide shortcuts for development. remove in production
#########################################################################
```
