### ISSUE TITLE
Tour ideas

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#862]
Here's an issue in which we can dump ideas for tours, as we come across them.

* Convergence in "saws" of sawfish etc: https://mapress.com/mz/article/view/mesozoic.1.2.3 - would make a nice tour
* This sort of thing is an example of topical social media-type stuff to highlight (or make a tour for) on OneZoom: https://x.com/ImperfectFunGuy/status/1801965609200095250

**Comment by jrosindell** [comment]
I moved this content to here https://github.com/OneZoom/tours/issues/8 in the tours content repo where I think it's better placed
