### ISSUE TITLE
Search bar doesn't bring up keyboard on first tap on iOS

### ISSUE THREAD

**Issue by jaredkhan** [OneZoom/OZtree#877]
The search bar in the explorer and on the home page on onezoom.org both require multiple taps to bring up keyboard on iOS when tested on an iPhone and an iPad. 

## Expected
Tapping the search bar would focus the text field and bring up the keyboard

## Actual
On the first tap, tapping the search bar shows the 'Popular Places' dropdown (which is empty on the home page of onezoom.org) but does not focus the textfield or bring up the keyboard. On the next tap, they focus the text field, bring up the keyboard and hide the popular places.

https://github.com/user-attachments/assets/ae0fe6c5-a4b9-4c4e-8752-759302811146

**Comment by jaredkhan** [comment]
I suppose this may have been deliberate so that Popular Places can be displayed. Perhaps Popular Places can be shown whilst the text field is in focus but nothing has yet been typed. That's the current situation when you type in a search term, get results, but then delete the term anyway.

**Comment by davidebbo** [comment]
FWIW, I don't see this on my Android phone (Pixel 6). Tapping the textbox both shows the popular places and brings up the keyboard, at the same time.

**Comment by jaredkhan** [comment]
This one resolves itself with a uikit update to 3.21.6 and above.

The same problem is reproducible outside of the onezoom context as demonstrated here:
https://codepen.io/jaredkhan-the-sans/pen/gOVjJyx
https://codepen.io/jaredkhan-the-sans/pen/jOgpjOe
