### ISSUE TITLE
Compass menu does not display reliably on iOS Safari

### ISSUE THREAD

**Issue by wolfmanstout** [OneZoom/OZtree#883]
To reproduce:
1. Go to https://www.onezoom.org/life
2. Search for "Common fruit fly" and navigate there.
3. Use the compass menu to navigate to "Fruit fly"
4. Tap the compass button again.

Observed behavior: Compass button turns yellow but nothing pops up.
Expected: Compass menu pops up.

**Comment by hyanwong** [comment]
Can you reproduce this @lentinj ?

**Comment by lentinj** [comment]
Yeah, mobile Firefox does the same, only way I can get it to open again is reload the page.

On desktop it appears on mouseover (which isn't consistent with everything else anyway). Touch-based interaction requires a click.

My bet is the code to hide on zoom isn't telling UI-Kit that the pop-up is now closed, so doesn't open again.

**Comment by jaredkhan** [comment]
You're spot on I reckon, @lentinj!
Fixing that seems to solve this problem for me locally on an iPhone.
Could you see what you think in https://github.com/OneZoom/OZtree/pull/889
