### ISSUE TITLE
Text Jitters

### ISSUE THREAD

**Issue by jaredkhan** [OneZoom/OZtree#899]
Scale and centering of text is very jittery as you zoom around the viewer.
Problem is visible on all platforms but the effect is most noticeable on mobile (where refreshes occur frequently whilst zooming) and in slow-moving tours.

https://github.com/user-attachments/assets/c56aa145-561d-4a3b-9ed2-b876b624d4ca

**Comment by lentinj** [comment]
I'd look into the ``auto_text`` set of functions here, which manage textbox sizing:

https://github.com/OneZoom/OZtree/blob/main/OZprivate/rawJS/OZTreeModule/src/util/draw.js

I've never dug into the guts of them though, so can't give any more hints than that. It may be there's no easy wins, and we have to rethink how node/leaves are scaled.
