### ISSUE TITLE
Incorporation of still or animation behind the tree

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#90]
1.) This should be done in layout.html so that it's accessible as an option from all tree views.

**Comment by lentinj** [comment]
Right, after a slightly sea-sick afternoon I've come up with the above, which randomly shows tree images and gently skews them about, trying to disguise the lack of real 3d model for the objects.

The images are all grey-scale and tinted at run-time, this means we can move the colouring logic from the nodes (which should be grey now anyway) to the tree shapes, so background gently changes hue as you navigate through the tree.

Displaying new background objects is currently a bit naive, and needs sorting so there's more of an even spread over time.

The obvious thing I've not done is react to zoom / pan. It doesn't look like the original movies do this, and I think it makes it more obvious it's just spinny background, not actual content. I'm also not sure how to do it without lots of edge cases where you zoom/pan out of the background.

**Comment by jrosindell** [comment]
I like this solution and would suggest moving on to other issues before possibly coming back to this one.  

In particular I'd like some feedback from Naziha on it before proceeding to suggest making further changes.  Can you please update it on your server if you haven't already and send me a link to share with Naziha for quick feedback?  Meanwhile proceed with the other issues.

**Comment by lentinj** [comment]
Yep, although I want to incorporate at least the more obvious rendering differences from the other branch first.

**Comment by lentinj** [comment]
Also of note, I don't think we need a generic mechanism here. I've added a 'background-layer' class to the main stylesheet, but either:-

* The background is rendered in JS (like here), in which case the javascript can add whatever nodes it needs
* The background is CSS, in which case there's several places you could attach background images.

**Comment by jrosindell** [comment]
This sounds good... you're right that the other rendering tweaks unrelated to the background still need to be done as requested by Naziha in the most recent Skype meeting that the three of us attended together.

In terms of your solution above I agree that the background JS class doesn't have be genetic, it's bespoke to this particular project.  The one thing that isn't clear to me is 

> The background is rendered in JS (like here), in which case the javascript can add whatever nodes it needs

Are you talking about nodes on the tree here or something related to the animated background? Or is it that nodes of the tree somehow interact with and influence the animated background behaviour (I didn't think this was so from experimenting briefly but could be wrong)

**Comment by lentinj** [comment]
I'm talking about DOM nodes. On startup, the ``backgrounds.js`` adds in it's layer behind the canvas and does it's thing without needing changes to layout.html.

**Comment by lentinj** [comment]
Naziha happy with bulk of work, main issue remaining is #104
