### ISSUE TITLE
Animation frame rates

### ISSUE THREAD

**Issue by jaredkhan** [OneZoom/OZtree#910]
Animations including:
- Zooming using the +/- buttons
- Flights on the tree (e.g clicking on search results)
- Direct flights (e.g. signpost clicks)
should aim to run at the display refresh rate **and** should be frame-rate-independent so that the animation speed is similar regardless of the frame rate and of frames being dropped. This should result in these animations feeling much more pleasant to look at.

Currently, frame rates for some of these animations are set very low (zooms at 30FPS, flights at 16FPS) and all assume fixed time step which can cause a little jitteriness.

**Comment by jaredkhan** [comment]
Yeah scrolling could do with some work too but I’ll make a separate issue for that. I have a prototype of smooth scrolling that I can send you later on in fact 😊

**Comment by davidebbo** [comment]
> Yeah scrolling could do with some work too but I’ll make a separate issue for that. I have a prototype of smooth scrolling that I can send you later on in fact 😊

To make sure there is no misunderstanding, I'm referring to the scroll wheel on my mouse, which has a zoom in/out effect. Is that in fact what you meant as well?

**Comment by jaredkhan** [comment]
Mmh well I mean scrolling on a trackpad or a continuous mouse wheel as opposed to a clicky mouse wheel but similar effect I suspect. 
There's a branch here if you want to have a play, it's not really ready for a pull request yet: https://github.com/jaredkhan/OZtree/tree/fix-text-jitter

**Comment by davidebbo** [comment]
Getting a conflict on that branch. Mind fixing that up? Happy to play with it.
