### ISSUE TITLE
Visual enhancements and One Tree, One Planet theming

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#92]
1.) shading behind sections of the tree in colours that can be controlled

2.) Experiment with WebGL but lower priority and only initially to see if it's faster or of equal speed *without* the camera move needing to be utilised.

3.) Other visual effects that can be done within canvas - investigate possibilities.

4.) Design decisions... how to show signposts (must be shown in correct places, should they go over the top of the tree)

**Comment by jrosindell** [comment]
5.) design decision what should the leaves look like - probably circles

6.) add the halo effect on canvas and play with signpost position and size, after use by all it should be clearer what to do.

**Comment by lentinj** [comment]
Use one of the animations instead of the "Loading" banner

**Comment by lentinj** [comment]
re: (2), there's another half-way house. Rendering the existing output into a WebGL view. This might be an easier way of getting more visual effects and filters that would be possible with WebGL.

**Comment by jrosindell** [comment]
I'm not sure I know about the WebGL view solution but is this an environment for 2D specifically, or is it an environment without a camera move option?

**Comment by jrosindell** [comment]
Sounds like a good idea to me - especially if it provides performance advantages - do you think this would be the case? Is it a great deal of work?

**Comment by lentinj** [comment]
Taming the signposts for OTOP is proving tricky, signpost nodes from children appear to bubble up to parent nodes, but after any under_signpost consideration---this is resulting in lots of overlapping nodes. I can't spot where this may be coming from yet.

Also I'm not sure the bounding boxes for polytomy are being calculated correctly, resulting in distant branches sticking out (exactly what @jrosindell wanted, conveniently).

**Comment by jrosindell** [comment]
I'm not following - signposts don't currently overlap on Polytomy view (or used not to) - they rippled down the tree rather than up and once the size was optimal ceased rippling down so there is never a situation where signposts are shown for one node as well as for one of its descendent nodes.

There might be some code which requires the details of a node to be visible before it ceases to act as a signpost - the logic behind this was that it's wierd if 'mammals' disappears entirely from screen when you zoom in instead of disappearing from the signpost and appearing in the mammals node itself. Maybe it's this that's causing the signpost taming issues?

For OTOP I think we probably want to consider text only signposts as being distinct from text and graphic signposts - so the 'mammals' + image signpost can be replaced with a 'mammals' text only signpost when there is space enough to draw several images further down the tree. What do you think? I hope I'm being clear and also have got the right end of the stick from your comment.

**Comment by jrosindell** [comment]
Ah I see what you mean...

**Comment by jrosindell** [comment]
<img width="354" alt="untitled" src="https://user-images.githubusercontent.com/3009279/40043302-ffcdcc4e-581b-11e8-9fe3-dfccb5c75463.png">

**Comment by jrosindell** [comment]
Only one of these 4 signposts should appear - something must have changed unless I'm mistaken.

**Comment by lentinj** [comment]
Yeah, but it's not that only one of those 4 should appear---that logic is working. The problem is that the arrow worms signpost should sit on the node above and to the right. All of the signposts are sitting on their parents.

**Comment by jrosindell** [comment]
Ah - I think the code drawing them must still be coming from the correct place but the positioning code is positioning back to the parents - could that be it?

**Comment by lentinj** [comment]
Think I see the problem: https://github.com/OneZoom/OZtree/blob/3.3/OZprivate/rawJS/OZTreeModule/src/projection/layout/polytomy/signpost_layout.js#L19

Should be ``node.arcx``, not ``node.ex``

**Comment by jrosindell** [comment]
Ah yes that makes sense.  arcx,arcy give the positions of the node circle ex and ey give the end positions of the bezier curve.  You might well not want to stick to just arcx and move the signpost a little way back down the branch from the node for aesthetic reasons.  

While I'm messaging on this thread can I draw your attention to #87 which I've added some requirements to and which would really benefit from a look form you during this sprint - thanks!

**Comment by lentinj** [comment]
Is this a bug with signpost_layout, or just something I need to change for OTOP? I'm not quite sure what "over the circular horizon of the node" means.

**Comment by jrosindell** [comment]
I don't think we observed any bugs in the signposts of the other views right? In which case this is for OTOP only (though possibly the code is a little obscure and could do with additional comments)

I presume you're talking about

`    // need to change the centre point to be over the circular horizon of the node
    calc_center_point(node) {
        this.centerx = node.xvar + node.rvar * node.ex;
        this.centery = node.yvar + node.rvar * node.ey;
        this.centerr = node.rvar;
    }`

I think that the comment is a bad one - this is about the positioning of a signpost not the overall horizon of the node - however the calculation for the signpost depends on the horizon because the signpost needs to partly (but not entirely) cover the area that the signposts refers to.  In signpost_layout_helper the non polytomy case is defined in function calc_center_point(node) which is then overwritten by the code above for the special case of polytomy.

The non polytomy related calculation is related to two possible ways of getting signpost position 1.) from the horizon to cover the area occupied by node + children 2.) from the node itself (ignoring children) same position by much larger radius.  In the end I didn't choose one or the other of these solutions but linearly mixed them in different ways that looked good for the different (non polytomy) view.

node.ex = Math.cos(angle);
node.ey = Math.sin(angle);

is calculated in polytomy precalc for efficiency and thus can be used to linearly move the centre of the signpost away from the centre of the node circle in an appropriate direction. (angle is the orientation of that whole part of the tree).  I expect that what you really want is 

'this.centerx = node.xvar + node.rvar * node.arcx + tweak_factor_1 * node.rvar *node.ex;
        this.centery = node.yvar + node.rvar * node.arcy + tweak_factor_1 * node.rvar * node.ey;
        this.centerr = node.rvar * tweak_factor_2;'

tweak_factor_1 will enable the position of the signpost to be retracted up the branch and away from the node itself as discussed with Naziah and tweak_factor_2 will enable the size of the signpost to be changed.

**Comment by jrosindell** [comment]
Ah I see what you mean. In my mind the only difference between OTOP and polytomy view is the colour scheme and background elements as the existing polytomy view is not released yet. If there is a difference in future it'll probably be in order to have smooth curves but for now it's probably easiest and best to keep them identical for leaf, node and signpost layout.

**Comment by lentinj** [comment]
Right, 3.3 now has an otop.html with a first pass at a OTOP theme. It's not too far off but there's still plenty of tweaks that could be done. For starters...

* The sponsorship text isn't disappearing from the nodes, only leaves.
* The line drawing hasn't been customised yet.
* A dark UIKit theme needs to be turned on.

...hopefully there's some easier ones to knobble today, then will look at installing a minimum version(s) somewhere.

**Comment by jrosindell** [comment]
Hi Jamie - thanks for this.  It looks **really** great!

I've got a few thoughts about it so far...

1.) I like the fact the colours are not the same everywhere, but we should probably think about the logic that determines which colour to show (this is science / art decision and probably involves Naziha)  E.g. can we consider making them relate to conservation status still and choose 6 colours for that which appear as rings around the outside of images or fill for nodes when there is no image.  I also think the current colours need black text over them for leaves, not white, but I do like the palette chosen - pastel and attractive colours.

2.) I feel that the signposts are a bit too transparent and it's strange that they don't respond to mouseover at all given that they are clickable.

3.) Coloured highlights probably still need work on the lines and an antialiasing solution is also needed.

4.) Sponsorship is also not entirely turned off for leaves.  There is a variable to turn sponsorship off somewhere in the code already - did you find that?  yan added it at some point.  Probably we want the ring of space that would have been filled with sponsorship text to be occupied instead by expanding the size of the node details themselves proportionately.

5.) I think that we probably want two types of signpost - text only and text + image.  When we zoom into a signpost at present with text + image it disappears entirely and new signposts appear, but the text needn't have disappeared and could have been visible in larger text over the top of a node.  I suggest this is probably easiest implemented by having another node style for when nodes are really zoomed out - in which the node is drawn with text that is allowed to be outside the boundary of the node itself.  I hope this is clear enough  - it's hard to explain what I mean - will attach a couple of screenshots in a moment.

Sorry it's a long list - I want to reiterate how great it is already as my last comment!

**Comment by jrosindell** [comment]
![untitled](https://user-images.githubusercontent.com/3009279/40132173-f9e76380-5933-11e8-81f8-450c695af5f4.png)
![untitled 2](https://user-images.githubusercontent.com/3009279/40132177-fb72e6f2-5933-11e8-9ddd-1836b350e862.png)
![untitled 3](https://user-images.githubusercontent.com/3009279/40132181-fd7a4e9a-5933-11e8-8f8a-24159abcaab0.png)

**Comment by jrosindell** [comment]
In the middle of the three images I can no longer see where 'monkeys and apes' are though it is intermediate in terms of zoom

**Comment by lentinj** [comment]
> 1.) I like the fact the colours are not the same everywhere, but we should probably think about the logic that determines which colour to show (this is science / art decision and probably involves Naziha)

Currently it's the node gets a hue relative to it's position in raw_data. I'm definitely not sold on the node colours as-is (the colours were chosen as a wash to apply over the signpost images, not to be solid on the screen), but like you say I think we need to see where Naziha takes it.

> appear as rings around the outside of images

I don't think that rings around nodes will fit with Naziha's thinking. What I'd like to do is blur the edges of nodes, but I've not seen an easy way to do that.

> 2.) I feel that the signposts are a bit too transparent and it's strange that they don't respond to mouseover 

The text is supposed to change on mouseover, but it seems very buggy. I suspect there's some state not being cleared by the render object pools.

> 3.) Coloured highlights probably still need work on the lines and an antialiasing solution is also needed.

Yeah, I'm not done yet here.

> 4.) Sponsorship is also not entirely turned off for leaves

It is now. A wee bug-ette. I found the flag, but not an obvious way to turn it on/off from the html without copying layout.html. My solution was:-

https://github.com/OneZoom/OZtree/commit/6ba0dc807c76db569c6628e62dbe535bd4213622
..and https://github.com/OneZoom/OZtree/commit/ce3128a0fae78beb1bda69b8049201be7bcf8049#diff-f01bfdd5bb43bde84ba85b9dacaf3538R41

...I'll be happily corrected if I've missed something.

> 5.) I think that we probably want two types of signpost

I see what you mean. In the video mockups the "Monkeys and Apes" node would have had a label above it which would possibly solve this. However, the layout would get very awkward if the text was big enough to easily read and not get obscured by the tree.

Ideally the larger signpost would still be fading out as the smaller signposts are fading in, but that would mean some annoying re-jiggling in signpost_common.

**Comment by jrosindell** [comment]
All sounds good...

> I don't think that rings around nodes will fit with Naziha's thinking. What I'd like to do is blur the edges of nodes, but I've not seen an easy way to do that.

I meant only the leaf nodes because leaves are fundamentally very different to signposts and thus should look different on screen in a more substantial way than just less transparency.  Also, without the rings leaves look too different depending on whether they have images or not and the information encoded in the colour of the leaf is permanently lost for leaves with images.

> I see what you mean. In the video mockups the "Monkeys and Apes" node would have had a label above it which would possibly solve this. However, the layout would get very awkward if the text was big enough to easily read and not get obscured by the tree.

> Ideally the larger signpost would still be fading out as the smaller signposts are fading in, but that would mean some annoying re-jiggling in signpost_common.

Hmmm, I'm not convinced about this - I think signposts fading in and out could easily be too visually complex for the user, it's very intuitive to have just a semantic zooming solution as currently.  I see what you mean though - sometimes the layout demands nodes that are very close together and if those nodes were side by side and both with names then it's a problem.

How about this.... the text only signposts are also drawn in a way that ripples down the tree (like the signposts), and as soon as a stop condition is hit the rippling stops - spatially close and adjacent nodes would be one such stop condition and thus the higher of the two nodes would get a name and the lower of the two would only get a name when the nodes are large enough for there to be space.

Another thing I've wondered about is whether interior nodes with no names should be drawn at all, or whether they should be drawn as much smaller dots or joins rather than as significant circles.

**Comment by lentinj** [comment]
This seems done now, if there's further issues with the theme then we should raise more specific tickets.
