### ISSUE TITLE
Site can get into a mode where the UI doesn't refresh properly

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/OZtree#922]
@jaredkhan this is new to the high res change. I don't have a consistent repro, but I've now seen it 3 times. It happens in the morning after I wake my machine up and connects it back to my main monitor. This is on Windows 11 / Chrome.

It ends up in a state where things don't properly refresh outside of a smaller rectangle as I pan around or zoom in/out, e.g.

![image](https://github.com/user-attachments/assets/8cdddedd-15d4-493a-a00f-82a51adb57f1)

Resizing the window fixes it. I think it somehow misses a resolution change event, and still acts as if it's on my smaller laptop screen, instead of the high res big screen. However, if it's in a good state and I simply move the window from the small to the big screen, it doesn't happen (in fact, I see it 'flash' as it redraws).

It's not a huge deal all things considered, as it happens rarely and is easy to fix, but there is a refresh bug somewhere.

**Comment by jaredkhan** [comment]
Yeah, that's not great! The screenshot is helpful.

Is that the whole window you've screenshotted or just a portion of it?

It's interesting too that the screenshot shows a branch with no leaf at the end of it, suggesting that we're seeing something that the renderer doesn't think we can see.
It's all consistent with the scale on the context not being set. If I comment out the line that sets the scale I get this:

<img width="1581" alt="image" src="https://github.com/user-attachments/assets/da53f34b-d77f-408f-9515-533fe1d7dce5">

but I can't see any obvious reason that the canvas width would be changed without the scale getting set. Will 

- This is on `master`?
- Have you seen it on the extant tree at all? I'm not exactly clear how the extinct page is setup. Perhaps @hyanwong can explain how it works? I imagine it's not that, just checking that this is using the exact same code.

**Comment by jaredkhan** [comment]
Fix would be something like this if so:
https://github.com/OneZoom/OZtree/pull/923

**Comment by davidebbo** [comment]
> Is that the whole window you've screenshotted or just a portion of it?

It was a portion.

> This is on the `main` branch?

Saw it both on https://www.onezoom.org/extinct/life/, which has main, and on my own server, which had another change of yours I was testing.

> Have you seen it on the extant tree at all? I'm not exactly clear how the extinct page is setup. Perhaps @hyanwong can explain how it works? I imagine it's not that, just checking that this is using the exact same code.

No, the extant tree has not been updated with your changes yet. I only saw it on the extinct tree.

I have pulled #923, so I'll see what happens after a while running. Thanks!

**Comment by jaredkhan** [comment]
Thanks @davidebbo!

**Comment by davidebbo** [comment]
I had both a version with and without the fix running in different tabs, and only the one without got into that state this morning. So there is some evidence that the fix is effective.

**Comment by hyanwong** [comment]
Shall I merge #923 then, or does it need more testing. Should we have a test for it somehow?

**Comment by jaredkhan** [comment]
Yeah good to go I reckon, @hyanwong. Low risk, and sounds like it could have helped this situation.

**Comment by hyanwong** [comment]
Done. I'll update the extinct tree in a bit.
