### ISSUE TITLE
Buttons have pointy corners sticking out

### ISSUE THREAD

**Issue by jaredkhan** [OneZoom/OZtree#924]
Bit of a silly one but nonetheless...
<img width="145" alt="image" src="https://github.com/user-attachments/assets/507ea9d0-f8ed-4469-a25c-0eb38b72da79">

(Seen on Chrome on macOS)

**Comment by davidebbo** [comment]
I had to zoom in to 500% to see this! The devil is (hiding) in the details. 😃
