### ISSUE TITLE
Grunt compile has warnings

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#96]
(node:12258) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Running "clean:compile" (clean) task

It would be good to fix this issue

**Comment by hyanwong** [comment]
This is probably some outdated package in the npm requirements. Would be nice to find and update somehow.

**Comment by hyanwong** [comment]
I've tried to fix all these now. Reopen if more happen
