### ISSUE TITLE
Overhaul "Loading..." mechanism

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#99]
For OTOP the Loading... message obviously needs some work. I think there's 2 directions to do so:-

(1) Move the hard coded colours into the theme, so we can change the fill color of the text for OTOP

(2) Replace the canvas-based rendering with CSS-based rendering - the controller sets/removes a loading class on the canvas, and CSS rules put the "Loading..." text on top.

The latter is obviously a lot more flexible (we can then include a loading video in the OTOP theme), but a lot more invasive. @jrosindell any preferences?

**Comment by lentinj** [comment]
Yeah, no rush.

**Comment by hyanwong** [comment]
We already pass some callback-like UI functions to the OZ instance, e.g. for when popup windows are called etc (see https://github.com/OneZoom/OZtree/blob/15c06c866ef7a053f14b0bea01623730b8159cb0/OZprivate/rawJS/OZTreeModule/src/OZentry.js#L30). I think it would be reasonable to pass another UI function that is called once the OZ instance is ready. The "Loading" pic does seem more like a UI thing. I don't think it needs to be very invasive.

**Comment by lentinj** [comment]
My point about being invasive was more that it would change the mechanism for all of OneZoom, rather than just a hook that only OTOP uses.

**Comment by hyanwong** [comment]
ISWYM - but I think this is a reasonable change for the whole of OneZoom if it is easy to implement.

**Comment by lentinj** [comment]
What do you make of the above? Note it's a spinner now, not a "Loading..." message. I would claim that it looks more modern but my main motivation was to avoid figuring out the translation.

The spinner blends nicely with the OTOP theme too, so just leaving it there.

**Comment by hyanwong** [comment]
Neat. Nice to remove code from the viewer JS too.
